import type { ResourceArticle } from './types';

export const docs: ResourceArticle[] = [
  {
    id: 'getting-started',
    category: 'docs',
    readMin: 10,
    es: {
      title: 'Primeros pasos para coaches',
      subtitle: 'Configura tu cuenta, personaliza tu marca, invita a tu primer cliente y conoce el Panel de Control.',
    },
    en: {
      title: 'Getting started for coaches',
      subtitle: 'Set up your account, customize your brand, invite your first client and tour the Dashboard.',
    },
    blocks: [
      {
        type: 'p',
        es: 'Esta guía de referencia te lleva paso a paso, clic a clic, por la puesta en marcha inicial de la plataforma: desde verificar tu cuenta hasta tener a tu primer cliente activo dentro de su propio espacio con un onboarding asignado. Sigue los bloques en orden; cada uno deja la cuenta lista para el siguiente y va acompañado de la pantalla real que verás.',
        en: 'This reference walks you through the initial setup of the platform step by step, click by click: from verifying your account to having your first client active inside their own space with an onboarding assigned. Follow the blocks in order; each one leaves your account ready for the next and is paired with the actual screen you will see.',
      },
      {
        type: 'h',
        es: '1. Configura tu cuenta y tu marca',
        en: '1. Set up your account and brand',
      },
      {
        type: 'p',
        es: 'Toda la configuración vive en la sección Configuración, accesible desde el menú lateral izquierdo. Dentro encontrarás cuatro pestañas: Apariencia/Tema, Seguridad, Facturación e Integraciones. Empieza por dejar la cuenta segura y con tu identidad visual aplicada antes de invitar a nadie.',
        en: 'All configuration lives in the Settings section, reachable from the left-hand sidebar. Inside you will find four tabs: Appearance/Theme, Security, Billing and Integrations. Start by leaving the account secure and with your visual identity applied before inviting anyone.',
      },
      {
        type: 'steps',
        es: [
          'Confirma tu email desde el enlace de verificación que recibes al registrarte; sin verificar no podrás invitar clientes.',
          'En el menú lateral pulsa Configuración y abre la pestaña Apariencia/Tema.',
          'Sube tu logotipo (PNG o SVG con fondo transparente recomendado) y elige tu color de marca: ese tono se aplica a botones, enlaces y acentos en el espacio del cliente.',
          'Cambia entre modo claro y oscuro con el conmutador de tema y comprueba que tu color de marca se lee bien en ambos.',
          'Abre la pestaña Seguridad y activa la autenticación en dos pasos (2FA) si gestionas datos de varios clientes.',
          'Revisa la pestaña Facturación para confirmar tu plan, y la pestaña Integraciones por si quieres conectar herramientas externas más adelante.',
        ],
        en: [
          'Confirm your email from the verification link you receive when you sign up; until verified you cannot invite clients.',
          'In the sidebar click Settings and open the Appearance/Theme tab.',
          'Upload your logo (PNG or SVG with transparent background recommended) and pick your brand colour: that tone is applied to buttons, links and accents in the client space.',
          'Toggle between light and dark mode with the theme switch and check that your brand colour reads well in both.',
          'Open the Security tab and enable two-step authentication (2FA) if you manage data for several clients.',
          'Review the Billing tab to confirm your plan, and the Integrations tab in case you want to connect external tools later on.',
        ],
      },
      {
        type: 'img',
        src: '/landing/feature-settings.png',
        gradient: 'gradient-bg-privacy',
        alt: 'Pantalla de Configuración con las pestañas Apariencia/Tema, Seguridad, Facturación e Integraciones',
        es: 'En Configuración controlas el tema, la seguridad, la facturación y las integraciones desde sus cuatro pestañas.',
        en: 'In Settings you control theme, security, billing and integrations from its four tabs.',
      },
      {
        type: 'tip',
        es: 'Usa un color de marca con suficiente contraste sobre fondo claro y oscuro. La plataforma tiene modo oscuro y un acento demasiado claro se vuelve ilegible sobre blanco. Previsualiza siempre el tema oscuro antes de guardar.',
        en: 'Use a brand colour with enough contrast on both light and dark backgrounds. The platform has dark mode and an accent that is too light becomes unreadable on white. Always preview dark theme before saving.',
      },
      {
        type: 'h',
        es: '2. Invita a tu primer cliente',
        en: '2. Invite your first client',
      },
      {
        type: 'p',
        es: 'Los clientes se crean desde la sección Clientes del menú lateral. El alta genera automáticamente las credenciales de acceso del cliente, así que no necesitas inventar contraseñas ni enviar enlaces manualmente.',
        en: 'Clients are created from the Clients section in the sidebar. The sign-up automatically generates the client access credentials, so you don’t need to invent passwords or send links manually.',
      },
      {
        type: 'steps',
        es: [
          'En el menú lateral pulsa Clientes para abrir la lista de clientes.',
          'Pulsa el botón "Nuevo Cliente" en la parte superior derecha de la lista.',
          'Rellena el formulario: nombre, email y objetivo principal del cliente.',
          'Registra los datos de partida que ya tengas: peso, altura, edad y nivel de actividad.',
          'Observa el bloque de credenciales autogeneradas: la plataforma crea el usuario y una contraseña inicial que podrás compartir con el cliente.',
          'Pulsa "Crear Cliente"; el cliente aparece en la lista y puede acceder de inmediato a su propio espacio.',
        ],
        en: [
          'In the sidebar click Clients to open the clients list.',
          'Press the "New Client" button in the top right of the list.',
          'Fill in the form: name, email and the client’s main goal.',
          'Record any baseline data you already have: weight, height, age and activity level.',
          'Notice the autogenerated credentials block: the platform creates the user and an initial password you can share with the client.',
          'Press "Create Client"; the client appears in the list and can immediately access their own space.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-new-client.png',
        gradient: 'gradient-bg-writing',
        alt: 'Formulario Nuevo Cliente con credenciales autogeneradas y el botón Crear Cliente',
        es: 'El formulario Nuevo Cliente genera las credenciales de acceso automáticamente; solo tienes que pulsar Crear Cliente.',
        en: 'The New Client form generates the access credentials automatically; you only need to press Create Client.',
      },
      {
        type: 'h',
        es: '3. Recorre el Panel de Control',
        en: '3. Tour the Dashboard',
      },
      {
        type: 'p',
        es: 'El Panel de Control es la primera pantalla que ves al entrar y la que usarás cada día. Reúne tus tareas pendientes, tus clientes activos y las novedades para que sepas qué atender sin buscar por las distintas secciones.',
        en: 'The Dashboard is the first screen you see when you log in and the one you will use every day. It gathers your pending tasks, your active clients and recent activity so you know what to attend to without hunting across the different sections.',
      },
      {
        type: 'img',
        src: '/landing/feature-dashboard.png',
        gradient: 'gradient-bg-planning',
        alt: 'Panel de Control del coach con tareas pendientes, clientes activos y novedades',
        es: 'El Panel de Control reúne tus tareas pendientes, los clientes activos y las novedades en un único lugar.',
        en: 'The Dashboard gathers your pending tasks, active clients and recent activity in a single place.',
      },
      {
        type: 'ul',
        es: [
          'Tareas pendientes: check-ins por revisar, planes que caducan y avisos de Automatizaciones.',
          'Clientes activos: acceso rápido a cada ficha, su adherencia y su próxima cita.',
          'Novedades: lo último que ha hecho cada cliente desde tu última sesión.',
          'Accesos directos a Clientes, Onboarding, Automatizaciones y Check-ins desde el menú lateral.',
        ],
        en: [
          'Pending tasks: check-ins to review, plans about to expire and Automations alerts.',
          'Active clients: quick access to each profile, their adherence and next appointment.',
          'Recent activity: the latest each client has done since your last session.',
          'Quick links to Clients, Onboarding, Automations and Check-ins from the sidebar.',
        ],
      },
      {
        type: 'h',
        es: '4. Asigna un onboarding a tu cliente',
        en: '4. Assign an onboarding to your client',
      },
      {
        type: 'p',
        es: 'La sección Onboarding contiene plantillas reutilizables que guían al cliente en sus primeros días: cuestionarios iniciales, recogida de medidas, consentimientos y primeras tareas. Asignar un onboarding ahorra trabajo manual y arranca la relación con orden.',
        en: 'The Onboarding section holds reusable templates that guide the client through their first days: initial questionnaires, measurement collection, consents and first tasks. Assigning an onboarding saves manual work and starts the relationship in an orderly way.',
      },
      {
        type: 'steps',
        es: [
          'En el menú lateral pulsa Onboarding para ver tus plantillas disponibles.',
          'Si necesitas una nueva, pulsa "Crear Plantilla" y define sus pasos; si ya tienes una válida, salta este paso.',
          'Vuelve a la ficha del cliente o usa el botón "Asignar Onboarding".',
          'Elige la plantilla adecuada para ese cliente y confirma la asignación.',
          'Comprueba que el progreso del onboarding aparece en la ficha del cliente y en tus tareas pendientes del Panel de Control.',
        ],
        en: [
          'In the sidebar click Onboarding to see your available templates.',
          'If you need a new one, press "Create Template" and define its steps; if you already have a valid one, skip this step.',
          'Go back to the client profile or use the "Assign Onboarding" button.',
          'Choose the right template for that client and confirm the assignment.',
          'Check that the onboarding progress appears in the client profile and in your pending tasks on the Dashboard.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-onboarding-templates.png',
        gradient: 'gradient-bg-learning',
        alt: 'Plantillas de onboarding con sus pasos y el botón Crear Plantilla',
        es: 'Las plantillas de Onboarding reúnen los pasos de incorporación que asignas a cada nuevo cliente.',
        en: 'Onboarding templates gather the incorporation steps you assign to each new client.',
      },
      {
        type: 'p',
        es: 'Con la cuenta configurada, tu marca aplicada, un cliente activo y su onboarding en marcha, ya puedes empezar a construir planes y, cuando lo necesites, automatizar el seguimiento. Continúa con la guía de configuración de Automatizaciones.',
        en: 'With your account set up, your brand applied, an active client and their onboarding under way, you can start building plans and, when you need it, automate follow-ups. Continue with the Automations setup guide.',
      },
    ],
  },
  {
    id: 'automations-setup',
    category: 'docs',
    readMin: 10,
    es: {
      title: 'Configuración de automatizaciones',
      subtitle: 'Simple Automation frente al constructor visual de workflows: disparadores, condiciones y acciones.',
    },
    en: {
      title: 'Setting up automations',
      subtitle: 'Simple Automation versus the visual Workflow Builder: triggers, conditions and actions.',
    },
    blocks: [
      {
        type: 'p',
        es: 'Las Automatizaciones se ocupan del seguimiento repetitivo para que tú dediques tu tiempo al coaching real. Desde la sección Automatizaciones del menú lateral creas nuevas reglas con el botón "Nueva Automatización", que despliega un menú con dos opciones: Simple Automation y Advanced Workflow. Esta referencia explica cuándo usar cada una y cómo construirlas clic a clic.',
        en: 'Automations take care of the repetitive follow-up so you can spend your time on real coaching. From the Automations section in the sidebar you create new rules with the "New Automation" button, which opens a menu with two options: Simple Automation and Advanced Workflow. This reference explains when to use each and how to build them click by click.',
      },
      {
        type: 'img',
        src: '/landing/wt-new-automation.png',
        gradient: 'gradient-bg-writing',
        alt: 'Menú Nueva Automatización con las opciones Simple Automation y Advanced Workflow',
        es: 'El botón "Nueva Automatización" despliega un menú para elegir entre Simple Automation y Advanced Workflow.',
        en: 'The "New Automation" button opens a menu to choose between Simple Automation and Advanced Workflow.',
      },
      {
        type: 'h',
        es: 'Simple Automation',
        en: 'Simple Automation',
      },
      {
        type: 'p',
        es: 'Una Simple Automation es una regla de un solo paso: "cuando ocurre X, haz Y". Es ideal para recordatorios y avisos que no dependen del estado del cliente. Las gestionas desde la lista de automatizaciones, donde cada regla muestra su disparador y un interruptor para activarla o desactivarla.',
        en: 'A Simple Automation is a single-step rule: "when X happens, do Y". It is ideal for reminders and alerts that don’t depend on the client’s state. You manage them from the automations list, where each rule shows its trigger and a toggle to enable or disable it.',
      },
      {
        type: 'steps',
        es: [
          'En el menú lateral abre Automatizaciones y pulsa "Nueva Automatización".',
          'En el menú elige Simple Automation.',
          'Selecciona un disparador (por ejemplo, Check-in semanal).',
          'Selecciona una única acción (por ejemplo, enviar un Mensaje con plantilla).',
          'Pulsa Guardar; la regla aparece en la lista con su interruptor activado.',
        ],
        en: [
          'In the sidebar open Automations and press "New Automation".',
          'In the menu choose Simple Automation.',
          'Select a trigger (for example, Weekly check-in).',
          'Select a single action (for example, send a templated Message).',
          'Press Save; the rule appears in the list with its toggle on.',
        ],
      },
      {
        type: 'img',
        src: '/landing/feature-automations.png',
        gradient: 'gradient-bg-learning',
        alt: 'Lista de automatizaciones: renovación de plan, check-in semanal y radar de bajas con interruptores',
        es: 'La lista de Automatizaciones muestra cada regla con su disparador y un interruptor para activarla.',
        en: 'The Automations list shows each rule with its trigger and a toggle to enable it.',
      },
      {
        type: 'h',
        es: 'El Advanced Workflow (constructor visual)',
        en: 'The Advanced Workflow (visual builder)',
      },
      {
        type: 'p',
        es: 'Cuando necesitas lógica ramificada (por ejemplo, avisar solo si el cliente lleva varios días inactivo y además su plan está a punto de caducar), elige Advanced Workflow en el menú "Nueva Automatización". Se abre el constructor visual: un lienzo donde arrastras bloques y los conectas. Empieza por un disparador, añade las condiciones que filtran a quién aplica y termina con una o varias acciones.',
        en: 'When you need branching logic (for example, alerting only if the client has been inactive for several days and their plan is about to expire), choose Advanced Workflow in the "New Automation" menu. The visual builder opens: a canvas where you drag blocks and connect them. Start with a trigger, add the conditions that filter who it applies to, and end with one or more actions.',
      },
      {
        type: 'img',
        src: '/landing/feature-workflow.png',
        gradient: 'gradient-bg-planning',
        alt: 'Constructor visual de workflows con bloques de disparador, condición y acción conectados en el lienzo',
        es: 'En el constructor visual conectas disparadores, condiciones y acciones sobre el lienzo para construir flujos a medida.',
        en: 'In the visual builder you connect triggers, conditions and actions on the canvas to build custom workflows.',
      },
      {
        type: 'h',
        es: 'Disparadores',
        en: 'Triggers',
      },
      {
        type: 'ul',
        es: [
          'Caducidad de plan: el plan o la suscripción del cliente está a punto de expirar (eliges con cuántos días de antelación).',
          'Check-in semanal: llega la fecha del check-in programado del cliente.',
          'Inactividad: el cliente no ha registrado actividad ni entrado a su espacio durante X días.',
          'Riesgo de baja: el radar de bajas detecta una caída de adherencia o de actividad que suele preceder a un abandono.',
        ],
        en: [
          'Plan expiry: the client’s plan or subscription is about to expire (you choose how many days in advance).',
          'Weekly check-in: the date of the client’s scheduled check-in arrives.',
          'Inactivity: the client hasn’t logged activity or entered their space for X days.',
          'Churn risk: the churn radar detects a drop in adherence or activity that usually precedes a drop-off.',
        ],
      },
      {
        type: 'h',
        es: 'Condiciones',
        en: 'Conditions',
      },
      {
        type: 'ul',
        es: [
          'Filtran qué clientes pasan el flujo: por objetivo, por etiqueta, por nivel de adherencia o por estado del plan.',
          'Se combinan con Y / O para crear reglas tan precisas como necesites.',
          'Si no añades condiciones, el flujo se aplica a todos los clientes que cumplen el disparador.',
        ],
        en: [
          'They filter which clients flow through: by goal, by tag, by adherence level or by plan status.',
          'They combine with AND / OR to create rules as precise as you need.',
          'If you add no conditions, the workflow applies to every client that meets the trigger.',
        ],
      },
      {
        type: 'h',
        es: 'Acciones',
        en: 'Actions',
      },
      {
        type: 'ul',
        es: [
          'Mensaje: envía al cliente un mensaje (puedes usar plantillas con su nombre y datos).',
          'Tarea: crea una tarea para ti en el Panel de Control, por ejemplo "revisar el check-in de Marta".',
          'Alerta: te notifica a ti como coach sin tocar al cliente, útil para el radar de bajas.',
        ],
        en: [
          'Message: sends the client a message (you can use templates with their name and data).',
          'Task: creates a task for you on the Dashboard, for example "review Marta’s check-in".',
          'Alert: notifies you as the coach without touching the client, useful for the churn radar.',
        ],
      },
      {
        type: 'h',
        es: 'Crear tu primer Advanced Workflow',
        en: 'Build your first Advanced Workflow',
      },
      {
        type: 'steps',
        es: [
          'En Automatizaciones pulsa "Nueva Automatización" y elige Advanced Workflow para abrir el constructor visual.',
          'Arrastra el disparador "Inactividad" al lienzo y ajústalo a 7 días.',
          'Conecta una condición que limite el flujo a clientes con el plan activo.',
          'Añade una acción de Mensaje con una plantilla amable de "¿todo bien?" y, en paralelo, una acción de Alerta para ti.',
          'Pulsa Guardar y activa el flujo desde la lista de automatizaciones con su interruptor.',
          'Pruébalo con un cliente de ejemplo antes de aplicarlo a todos.',
        ],
        en: [
          'In Automations press "New Automation" and choose Advanced Workflow to open the visual builder.',
          'Drag the "Inactivity" trigger onto the canvas and set it to 7 days.',
          'Connect a condition that limits the flow to clients with an active plan.',
          'Add a Message action with a friendly "everything ok?" template and, in parallel, an Alert action for you.',
          'Press Save and enable the workflow from the automations list with its toggle.',
          'Test it with a sample client before rolling it out to everyone.',
        ],
      },
      {
        type: 'tip',
        es: 'Empieza por Simple Automation y pásate al Advanced Workflow solo cuando notes que repites la misma decisión manual. Un flujo demasiado complejo es difícil de depurar; varias reglas simples claras suelen mantenerse mejor.',
        en: 'Start with Simple Automation and move to the Advanced Workflow only when you notice you keep making the same manual decision. An over-complex workflow is hard to debug; several clear simple rules are usually easier to maintain.',
      },
    ],
  },
  {
    id: 'api-exports',
    category: 'docs',
    readMin: 6,
    es: {
      title: 'API y exportaciones de datos',
      subtitle: 'Cómo exportar tus datos en CSV, gestionar solicitudes RGPD y qué esperar de la futura API.',
    },
    en: {
      title: 'API and data exports',
      subtitle: 'How to export your data to CSV, handle GDPR requests and what to expect from the future API.',
    },
    blocks: [
      {
        type: 'p',
        es: 'Tus datos son tuyos. Esta referencia explica cómo exportar la información de tus clientes y check-ins desde Configuración, cómo atender una solicitud de datos bajo el RGPD y qué tienes previsto encontrar en la API cuando esté disponible.',
        en: 'Your data is yours. This reference explains how to export your clients and check-ins from Settings, how to handle a GDPR data request, and what to expect from the API when it becomes available.',
      },
      {
        type: 'h',
        es: 'Exportar clientes y check-ins (CSV)',
        en: 'Export clients and check-ins (CSV)',
      },
      {
        type: 'p',
        es: 'La exportación se hace desde la sección Configuración, en su apartado de datos. Genera un archivo CSV con codificación UTF-8 que puedes abrir en cualquier hoja de cálculo o importar en otra herramienta.',
        en: 'Exporting is done from the Settings section, in its data area. It generates a CSV file encoded in UTF-8 that you can open in any spreadsheet or import into another tool.',
      },
      {
        type: 'steps',
        es: [
          'En el menú lateral pulsa Configuración.',
          'Dentro de Configuración abre el apartado Datos y exportaciones.',
          'Elige qué exportar: lista de clientes, historial de check-ins o ambos.',
          'Selecciona el rango de fechas que quieres incluir.',
          'Pulsa Exportar; recibirás un archivo CSV con codificación UTF-8.',
          'Abre el CSV en tu hoja de cálculo o impórtalo en otra herramienta; las columnas incluyen identificador, fecha y métricas.',
        ],
        en: [
          'In the sidebar click Settings.',
          'Inside Settings open the Data and exports area.',
          'Choose what to export: clients list, check-in history or both.',
          'Select the date range you want to include.',
          'Press Export; you’ll receive a CSV file encoded in UTF-8.',
          'Open the CSV in your spreadsheet or import it into another tool; columns include identifier, date and metrics.',
        ],
      },
      {
        type: 'tip',
        es: 'La exportación es completa y portable: si algún día dejas de usar la plataforma, te llevas tus datos contigo. No hay bloqueo de proveedor sobre la información de tus clientes.',
        en: 'The export is complete and portable: if you ever stop using the platform, you take your data with you. There is no vendor lock-in over your clients’ information.',
      },
      {
        type: 'h',
        es: 'Solicitudes de datos RGPD',
        en: 'GDPR data requests',
      },
      {
        type: 'ul',
        es: [
          'Acceso: un cliente puede pedirte una copia de sus datos; usa la exportación filtrada por ese cliente para entregársela.',
          'Rectificación: corrige cualquier dato inexacto directamente desde su ficha en la sección Clientes.',
          'Supresión: al eliminar un cliente, sus datos personales se borran de forma transaccional; conserva antes una copia si la necesitas para tu contabilidad.',
          'Plazo: atiende las solicitudes en un máximo de 30 días, como exige el RGPD.',
        ],
        en: [
          'Access: a client can ask you for a copy of their data; use the export filtered by that client to provide it.',
          'Rectification: correct any inaccurate data directly from their profile in the Clients section.',
          'Erasure: when you delete a client, their personal data is removed transactionally; keep a copy beforehand if you need it for your records.',
          'Deadline: handle requests within a maximum of 30 days, as the GDPR requires.',
        ],
      },
      {
        type: 'tip',
        es: 'Para una solicitud de acceso RGPD, exporta primero en CSV filtrando por ese cliente y entrégale el archivo en un formato legible. Documenta la fecha de la solicitud y de la entrega para tu propio registro de cumplimiento.',
        en: 'For a GDPR access request, first export to CSV filtered by that client and hand them the file in a readable format. Document the request and delivery dates for your own compliance record.',
      },
      {
        type: 'h',
        es: 'API (próximamente)',
        en: 'API (coming soon)',
      },
      {
        type: 'p',
        es: 'Estamos trabajando en una API REST que te permitirá leer tus clientes y check-ins de forma programática para integrarlos con tus propias herramientas. Los ejemplos siguientes son ilustrativos y muestran la forma prevista de las peticiones y respuestas; los endpoints definitivos se publicarán cuando la API esté disponible.',
        en: 'We are working on a REST API that will let you read your clients and check-ins programmatically to integrate them with your own tools. The following examples are illustrative and show the planned shape of requests and responses; the final endpoints will be published when the API is available.',
      },
      {
        type: 'code',
        lang: 'bash',
        content: '# Ilustrativo / illustrative - aun no disponible / not live yet\n# Listar clientes / list clients\ncurl https://api.example.com/v1/clients \\\n  -H "Authorization: Bearer YOUR_API_KEY" \\\n  -H "Accept: application/json"\n\n# Filtrar por estado / filter by status\ncurl "https://api.example.com/v1/clients?status=active&limit=50" \\\n  -H "Authorization: Bearer YOUR_API_KEY"',
      },
      {
        type: 'code',
        lang: 'json',
        content: '{\n  "data": [\n    {\n      "id": "cl_8f2a",\n      "name": "Marta Ruiz",\n      "goal": "fat_loss",\n      "status": "active",\n      "last_check_in": "2026-05-25",\n      "check_ins": [\n        { "date": "2026-05-25", "weight_kg": 68.4, "adherence": 0.92 }\n      ]\n    }\n  ],\n  "has_more": false,\n  "next_cursor": null\n}',
      },
      {
        type: 'p',
        es: 'Mientras la API llega, la exportación CSV desde Configuración cubre la mayoría de necesidades de integración y copia de seguridad. Suscríbete al changelog para enterarte en cuanto se publiquen los primeros endpoints y la documentación de autenticación.',
        en: 'Until the API arrives, the CSV export from Settings covers most integration and backup needs. Subscribe to the changelog to be notified as soon as the first endpoints and authentication docs are published.',
      },
    ],
  },
];
