import type { ResourceArticle } from './types';

export const guides: ResourceArticle[] = [
  {
    id: 'first-month',
    category: 'guides',
    readMin: 11,
    es: {
      title: 'Cómo configurar tu primer mes con la plataforma',
      subtitle: 'De la primera alta de cliente al primer check-in semanal, clic a clic y sin perderte por el camino.',
    },
    en: {
      title: 'Setting up your first month',
      subtitle: 'From your first client onboarding to your first weekly check-in, click by click, without getting lost.',
    },
    blocks: [
      {
        type: 'p',
        es: 'El primer mes marca el ritmo de toda la relación con tu cliente. No necesitas tenerlo todo perfecto desde el día uno: necesitas que el cliente esté dado de alta, tenga un plan claro y sepa cuándo y cómo va a reportar su progreso. Esta guía te lleva por esos hitos en el orden correcto, indicándote exactamente qué botón pulsar en cada paso.',
        en: 'The first month sets the tone for the whole relationship with your client. You don’t need everything perfect on day one: you need the client onboarded, with a clear plan, and knowing when and how they’ll report progress. This guide walks you through those milestones in the right order, telling you exactly which button to click at each step.',
      },
      {
        type: 'img',
        src: '/landing/feature-dashboard.png',
        gradient: 'gradient-bg-planning',
        alt: 'Panel del entrenador con tareas pendientes, clientes activos y novedades',
        es: 'Empiezas en el Panel de Control: reúne las tareas pendientes, los clientes activos y las novedades en un solo lugar.',
        en: 'You start at the Dashboard: it gathers pending tasks, active clients and updates in a single place.',
      },
      {
        type: 'h',
        es: '1. Da de alta a tu cliente',
        en: '1. Onboard your client',
      },
      {
        type: 'steps',
        es: [
          'En la barra lateral, pulsa "Clientes" para abrir la lista de clientes.',
          'Haz clic en el botón "Nuevo Cliente", arriba a la derecha.',
          'Rellena el bloque "Información Personal": Nombre, Apellido, Email y Teléfono.',
          'Revisa el bloque "Acceso a la Cuenta": las credenciales se autogeneran; deja activado el toggle "Enviar datos por email" para que el cliente reciba su acceso.',
          'Pulsa "Crear Cliente" para guardar el alta y enviar la invitación.',
        ],
        en: [
          'In the sidebar, click "Clientes" (Clients) to open the clients list.',
          'Click the "Nuevo Cliente" (New Client) button, top right.',
          'Fill in the "Información Personal" block: First name, Last name, Email and Phone.',
          'Check the "Acceso a la Cuenta" (Account Access) block: credentials are auto-generated; keep the "Enviar datos por email" (Send details by email) toggle on so the client receives their access.',
          'Click "Crear Cliente" (Create Client) to save the client and send the invitation.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-new-client.png',
        gradient: 'gradient-bg-writing',
        alt: 'Formulario de Nuevo Cliente con Información Personal y Acceso a la Cuenta',
        es: 'El formulario "Nuevo Cliente": Información Personal arriba, Acceso a la Cuenta con credenciales autogeneradas debajo, y el botón "Crear Cliente".',
        en: 'The "New Client" form: Personal Information on top, Account Access with auto-generated credentials below, and the "Create Client" button.',
      },
      {
        type: 'tip',
        es: 'Dedica los primeros 10 minutos a las restricciones y el contexto (alergias, lesiones, horarios, tiempo para cocinar), no a las kilocalorías. Un plan que el cliente no puede cumplir es peor que uno menos óptimo que sí encaja en su vida.',
        en: 'Spend the first 10 minutes on restrictions and context (allergies, injuries, schedule, time to cook), not on calories. A plan the client can’t follow is worse than a less optimal one that actually fits their life.',
      },
      {
        type: 'h',
        es: '2. Asígnale el onboarding',
        en: '2. Assign the onboarding',
      },
      {
        type: 'steps',
        es: [
          'En la barra lateral, pulsa "Onboarding".',
          'Abre "Plantillas de Onboarding" para ver la biblioteca de cuestionarios disponibles.',
          'Elige la plantilla que mejor encaje con el objetivo del cliente (revisa qué datos de partida recoge).',
          'Pulsa "Asignar Onboarding" y selecciona al cliente que acabas de crear.',
        ],
        en: [
          'In the sidebar, click "Onboarding".',
          'Open "Plantillas de Onboarding" (Onboarding Templates) to see the library of available questionnaires.',
          'Pick the template that best matches the client’s goal (check which baseline data it collects).',
          'Click "Asignar Onboarding" (Assign Onboarding) and select the client you just created.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-onboarding-templates.png',
        gradient: 'gradient-bg-learning',
        alt: 'Biblioteca de plantillas de onboarding',
        es: 'La biblioteca de "Plantillas de Onboarding": elige una y úsala con "Asignar Onboarding" para que el cliente complete sus datos de partida.',
        en: 'The "Onboarding Templates" library: pick one and use "Assign Onboarding" so the client fills in their baseline data.',
      },
      {
        type: 'h',
        es: '3. Construye el primer plan de nutrición',
        en: '3. Build the first nutrition plan',
      },
      {
        type: 'steps',
        es: [
          'En la barra lateral, pulsa "Nutrición" y luego "Crear Nuevo Plan" (o entra en el cliente y pulsa "Asignar Plan").',
          'En el editor, elige "Empezar desde una Plantilla" y selecciona una base como "Pérdida de Grasa Básico" o "Corte Cetogénico".',
          'Abre el panel "Configuración del Plan" y fija las "Calorías objetivo" a partir de un objetivo realista (p. ej. déficit del 10-20 %).',
          'Ajusta el "Reparto de macros": 1,6-2,2 g de proteína por kg, grasas en torno al 25-30 % de las calorías y el resto en hidratos.',
          'Revisa la "Estructura diaria" (número y orden de comidas) y guarda el plan.',
        ],
        en: [
          'In the sidebar, click "Nutrición" (Nutrition) then "Crear Nuevo Plan" (Create New Plan) — or open the client and click "Asignar Plan" (Assign Plan).',
          'In the editor, choose "Empezar desde una Plantilla" (Start from a Template) and select a base like "Pérdida de Grasa Básico" (Basic Fat Loss) or "Corte Cetogénico" (Keto Cut).',
          'Open the "Configuración del Plan" (Plan Settings) panel and set "Calorías objetivo" (Target calories) from a realistic goal (e.g. a 10-20% deficit).',
          'Adjust the "Reparto de macros" (Macro split): 1.6-2.2 g of protein per kg, fats around 25-30% of calories and the rest from carbs.',
          'Review the "Estructura diaria" (Daily structure — number and order of meals) and save the plan.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-nutrition-plan.png',
        gradient: 'gradient-bg-shopping',
        alt: 'Editor de plan de nutrición con plantillas, reparto de macros y Configuración del Plan',
        es: 'El editor de plan: "Empezar desde una Plantilla", el reparto de macros y el panel "Configuración del Plan" con calorías y estructura diaria.',
        en: 'The plan editor: "Start from a Template", the macro split, and the "Plan Settings" panel with calories and daily structure.',
      },
      {
        type: 'p',
        es: 'Para el primer plan, prioriza que sea sostenible por encima de que sea perfecto. Deja margen para ajustar en la segunda semana: el primer check-in te dirá más sobre cómo afinar las cifras que cualquier cálculo inicial.',
        en: 'For the first plan, prioritise sustainability over perfection. Leave room to adjust in week two: the first check-in will tell you more about how to fine-tune the numbers than any initial calculation.',
      },
      {
        type: 'h',
        es: '4. Programa el primer check-in',
        en: '4. Schedule the first check-in',
      },
      {
        type: 'steps',
        es: [
          'En la barra lateral, pulsa "Check-ins".',
          'Abre "Plantillas de Check-in" y elige el "Check-in Semanal" (o crea uno con "Crear Plantilla").',
          'Asigna la plantilla al cliente y fija la fecha para 7 días después del alta.',
          'Avísale de qué le vas a pedir (peso en ayunas, adherencia, sensaciones) para que llegue preparado.',
        ],
        en: [
          'In the sidebar, click "Check-ins".',
          'Open "Plantillas de Check-in" (Check-in Templates) and pick the "Check-in Semanal" (Weekly Check-in) — or create one with "Crear Plantilla" (Create Template).',
          'Assign the template to the client and set the date for 7 days after onboarding.',
          'Tell them what you’ll ask for (fasted weight, adherence, how they feel) so they come prepared.',
        ],
      },
      {
        type: 'img',
        src: '/landing/feature-checkins.png',
        gradient: 'gradient-bg-privacy',
        alt: 'Panel de check-ins con puntuación de adherencia y último peso',
        es: 'El panel de Check-ins resume la adherencia y el último peso para que decidas en segundos qué ajustar.',
        en: 'The Check-ins panel summarises adherence and last weight so you can decide in seconds what to adjust.',
      },
      {
        type: 'h',
        es: '5. Rompe el hielo con el primer mensaje',
        en: '5. Break the ice with the first message',
      },
      {
        type: 'p',
        es: 'Cierra el alta entrando en "Mensajes" desde la barra lateral y escribiéndole al cliente un mensaje de bienvenida: confírmale que ya tiene plan y check-in, dile dónde encontrarlos y qué se espera de él la primera semana. Ese primer contacto reduce las dudas y arranca la relación con buen pie.',
        en: 'Close the setup by opening "Mensajes" (Messages) from the sidebar and sending the client a welcome message: confirm they now have a plan and a check-in, tell them where to find them and what’s expected in week one. That first contact cuts down questions and starts the relationship on the right foot.',
      },
      {
        type: 'img',
        src: '/landing/feature-messages.png',
        gradient: 'gradient-bg-writing',
        alt: 'Bandeja de mensajería uno a uno con el cliente',
        es: 'La mensajería uno a uno: tu canal directo para la bienvenida y para cerrar cada check-in con una acción concreta.',
        en: 'The 1-on-1 messaging inbox: your direct channel for the welcome and for closing each check-in with a concrete action.',
      },
      {
        type: 'tip',
        es: 'Repite este recorrido (Clientes → Onboarding → Nutrición → Check-ins → Mensajes) con cada alta nueva. En la segunda o tercera vez lo harás en pocos minutos y sin saltarte ningún paso.',
        en: 'Repeat this route (Clients → Onboarding → Nutrition → Check-ins → Messages) with every new client. By the second or third time you’ll do it in minutes without skipping a step.',
      },
    ],
  },
  {
    id: 'plan-templates',
    category: 'guides',
    readMin: 9,
    es: {
      title: 'Plantillas de planes que funcionan en la práctica',
      subtitle: 'Reutiliza lo que ya funciona, personaliza lo que importa y deja de empezar de cero cada vez.',
    },
    en: {
      title: 'Plan templates that work in practice',
      subtitle: 'Reuse what already works, personalise what matters, and stop starting from scratch every time.',
    },
    blocks: [
      {
        type: 'p',
        es: 'Crear cada plan desde cero no te hace mejor entrenador, solo más lento. Las plantillas te dan una base sólida que repites en segundos y reservan tu tiempo para lo que de verdad cambia entre clientes. La clave está en saber qué dejar fijo en la plantilla y qué tocar siempre a mano.',
        en: 'Building every plan from scratch doesn’t make you a better coach, just a slower one. Templates give you a solid base you can reuse in seconds and free up your time for what truly differs between clients. The key is knowing what to keep fixed in the template and what to always adjust by hand.',
      },
      {
        type: 'h',
        es: 'Qué meter en una plantilla',
        en: 'What to put in a template',
      },
      {
        type: 'ul',
        es: [
          'Estructura de comidas y reparto de macros por comida (por ejemplo, proteína en cada toma, hidratos alrededor del entreno).',
          'Presets de macros por objetivo: pérdida de grasa, mantenimiento y volumen, cada uno con su rango de proteína, grasa e hidratos.',
          'Listas de alimentos intercambiables por grupo, para que el cliente pueda variar sin descuadrar las cifras.',
          'Recetas reutilizables ya creadas en la biblioteca, con sus macros calculados.',
        ],
        en: [
          'Meal structure and macro split per meal (for example, protein at every meal, carbs around training).',
          'Macro presets by goal: fat loss, maintenance and bulk, each with its protein, fat and carb ranges.',
          'Interchangeable food lists per group, so the client can vary meals without breaking the numbers.',
          'Reusable recipes already created in the library, with their macros calculated.',
        ],
      },
      {
        type: 'h',
        es: 'Crea tu primera plantilla de plan',
        en: 'Create your first plan template',
      },
      {
        type: 'steps',
        es: [
          'En la barra lateral, pulsa "Nutrición" y luego "Crear Nuevo Plan".',
          'Selecciona "Empezar desde una Plantilla" y elige una base (p. ej. "Pérdida de Grasa Básico" o "Corte Cetogénico").',
          'Abre "Configuración del Plan" y ajusta las "Calorías objetivo" al rango típico de ese objetivo.',
          'Define el "Reparto de macros" y la "Estructura diaria" que quieras dejar fijos como punto de partida.',
          'Guarda el resultado como plantilla nueva para reutilizarlo con futuros clientes.',
        ],
        en: [
          'In the sidebar, click "Nutrición" (Nutrition) then "Crear Nuevo Plan" (Create New Plan).',
          'Select "Empezar desde una Plantilla" (Start from a Template) and choose a base (e.g. "Basic Fat Loss" or "Keto Cut").',
          'Open "Configuración del Plan" (Plan Settings) and set "Calorías objetivo" (Target calories) to the typical range for that goal.',
          'Define the "Reparto de macros" (Macro split) and "Estructura diaria" (Daily structure) you want fixed as a starting point.',
          'Save the result as a new template to reuse it with future clients.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-nutrition-plan.png',
        gradient: 'gradient-bg-writing',
        alt: 'Editor de plan con Empezar desde una Plantilla y Configuración del Plan',
        es: 'El editor de plan: parte de "Empezar desde una Plantilla" y afina calorías, macros y estructura en "Configuración del Plan".',
        en: 'The plan editor: start from "Start from a Template" and fine-tune calories, macros and structure in "Plan Settings".',
      },
      {
        type: 'h',
        es: 'Apóyate en la biblioteca de recetas',
        en: 'Lean on the recipe library',
      },
      {
        type: 'steps',
        es: [
          'En la barra lateral, pulsa "Alimentos" para abrir tu biblioteca de recetas y alimentos.',
          'Pulsa "Nueva Receta" y añade los ingredientes; las kcal y los macros se calculan solos.',
          'Guarda la receta y ábrela para revisar su ficha (ingredientes, macros y botón "Editar Receta").',
          'Reutiliza esas recetas dentro de tus plantillas de plan para montar listas intercambiables sin recalcular nada.',
        ],
        en: [
          'In the sidebar, click "Alimentos" (Foods) to open your recipe and food library.',
          'Click "Nueva Receta" (New Recipe) and add the ingredients; kcal and macros are calculated automatically.',
          'Save the recipe and open it to review its detail page (ingredients, macros and "Editar Receta" / Edit Recipe button).',
          'Reuse those recipes inside your plan templates to build interchangeable lists without recalculating anything.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-new-recipe.png',
        gradient: 'gradient-bg-shopping',
        alt: 'Formulario de nueva receta con ingredientes y macros',
        es: 'El formulario "Nueva Receta": añade ingredientes y la plataforma calcula kcal y macros por ti.',
        en: 'The "New Recipe" form: add ingredients and the platform calculates kcal and macros for you.',
      },
      {
        type: 'img',
        src: '/landing/wt-recipe-detail.png',
        gradient: 'gradient-bg-learning',
        alt: 'Ficha de receta con ingredientes, macros y botón Editar Receta',
        es: 'La ficha de receta muestra ingredientes y macros; con "Editar Receta" la ajustas y la reutilizas en cualquier plantilla.',
        en: 'The recipe detail page shows ingredients and macros; with "Edit Recipe" you tweak it and reuse it in any template.',
      },
      {
        type: 'h',
        es: 'Reutilizar o personalizar',
        en: 'Reuse or personalise',
      },
      {
        type: 'p',
        es: 'Reutiliza la estructura y los presets; personaliza siempre las cifras absolutas y la selección de alimentos. Dos clientes con el mismo objetivo pueden partir de la misma plantilla, pero sus kilocalorías, sus horarios y los alimentos que toleran serán distintos. La plantilla te da el esqueleto en segundos; tú pones encima lo que hace que el plan sea suyo.',
        en: 'Reuse the structure and presets; always personalise the absolute numbers and food selection. Two clients with the same goal can start from the same template, but their calories, schedules and tolerated foods will differ. The template gives you the skeleton in seconds; you add on top what makes the plan theirs.',
      },
      {
        type: 'tip',
        es: 'Revisa tus plantillas cada pocos meses. Una plantilla es un punto de partida vivo, no una tabla grabada en piedra: si un patrón deja de funcionar con tus clientes, cámbialo en la plantilla y no en veinte planes uno a uno.',
        en: 'Review your templates every few months. A template is a living starting point, not a tablet of stone: if a pattern stops working for your clients, change it in the template instead of fixing twenty plans one by one.',
      },
    ],
  },
  {
    id: 'weekly-checkins',
    category: 'guides',
    readMin: 8,
    es: {
      title: 'Diseño de check-ins semanales eficaces',
      subtitle: 'Las preguntas que de verdad importan, con qué frecuencia y cómo revisarlas en minutos.',
    },
    en: {
      title: 'Designing effective weekly check-ins',
      subtitle: 'The questions that truly matter, how often to ask them, and how to review them in minutes.',
    },
    blocks: [
      {
        type: 'p',
        es: 'Un buen check-in no es un cuestionario interminable: son las pocas señales que te permiten decidir si el plan sigue igual o cambia. Si pides demasiado, el cliente lo rellena con desgana y tú te pierdes en el ruido. Si pides lo justo, conviertes cada semana en una decisión clara.',
        en: 'A good check-in isn’t an endless questionnaire: it’s the few signals that let you decide whether the plan stays the same or changes. Ask for too much and the client fills it in half-heartedly while you drown in noise. Ask for just enough and every week turns into a clear decision.',
      },
      {
        type: 'h',
        es: 'Crea tu plantilla de check-in',
        en: 'Create your check-in template',
      },
      {
        type: 'steps',
        es: [
          'En la barra lateral, pulsa "Check-ins".',
          'Abre "Plantillas de Check-in" para ver las plantillas existentes (Check-in Semanal, General) y su número de pasos.',
          'Pulsa "Crear Plantilla" para empezar una nueva desde cero.',
          'Añade los pasos con las preguntas clave (peso, perímetros, adherencia, sueño, ánimo, molestias).',
          'Pulsa "Establecer como Predeterminada" para que se asigne automáticamente a tus nuevos clientes.',
        ],
        en: [
          'In the sidebar, click "Check-ins".',
          'Open "Plantillas de Check-in" (Check-in Templates) to see existing templates (Weekly Check-in, General) and their number of steps.',
          'Click "Crear Plantilla" (Create Template) to start a new one from scratch.',
          'Add the steps with the key questions (weight, measurements, adherence, sleep, mood, discomfort).',
          'Click "Establecer como Predeterminada" (Set as Default) so it’s automatically assigned to your new clients.',
        ],
      },
      {
        type: 'img',
        src: '/landing/wt-checkin-templates.png',
        gradient: 'gradient-bg-privacy',
        alt: 'Biblioteca de plantillas de check-in con Crear Plantilla y número de pasos',
        es: 'La biblioteca de "Plantillas de Check-in": usa "Crear Plantilla", revisa el nº de pasos y marca una como predeterminada.',
        en: 'The "Check-in Templates" library: use "Create Template", review the number of steps and mark one as default.',
      },
      {
        type: 'h',
        es: 'Qué preguntar cada semana',
        en: 'What to ask every week',
      },
      {
        type: 'ul',
        es: [
          'Peso: la media de la semana pesa más que un dato suelto; pide varias mediciones en ayunas si es posible.',
          'Perímetros: cintura y cadera cada 2-4 semanas bastan para ver tendencia sin obsesionar.',
          'Adherencia: un porcentaje honesto de cumplimiento del plan, más útil que cualquier promesa de "lo he hecho bien".',
          'Sueño: horas y calidad, porque condicionan hambre, energía y recuperación.',
          'Estado de ánimo y energía: para detectar pronto la fatiga o un déficit demasiado agresivo.',
          'Dolor o molestias: avisos de lesión que conviene cazar antes de que paren el entreno.',
        ],
        en: [
          'Weight: the weekly average matters more than a single reading; ask for several fasted measurements if possible.',
          'Measurements: waist and hips every 2-4 weeks are enough to see a trend without obsessing.',
          'Adherence: an honest percentage of how much of the plan was followed, far more useful than any promise that "it went well".',
          'Sleep: hours and quality, since they drive hunger, energy and recovery.',
          'Mood and energy: to catch fatigue or an overly aggressive deficit early.',
          'Pain or discomfort: injury warnings worth catching before they stop training.',
        ],
      },
      {
        type: 'tip',
        es: 'Mantén la plantilla corta: 5-7 preguntas bien elegidas se responden con sinceridad; veinte se rellenan a desgana. Puedes alargar los perímetros y las fotos a una cadencia quincenal para no saturar cada semana.',
        en: 'Keep the template short: 5-7 well-chosen questions get honest answers; twenty get filled in reluctantly. You can move measurements and photos to a fortnightly cadence so you don’t overload every week.',
      },
      {
        type: 'h',
        es: 'Cadencia y revisión por lotes',
        en: 'Cadence and batch review',
      },
      {
        type: 'p',
        es: 'Semanal es la cadencia por defecto para la mayoría: suficiente para corregir el rumbo, sin saturar al cliente. Para revisarlos rápido, entra en "Check-ins" y procésalos por lotes: mira primero la tendencia de peso y la adherencia de cada uno. Si la adherencia es alta y el peso no se mueve en la dirección esperada, ajusta el plan; si la adherencia es baja, el problema no son las cifras, es el cumplimiento, y ahí toca conversación, no recalcular macros.',
        en: 'Weekly is the default cadence for most clients: enough to course-correct without overwhelming them. To review fast, open "Check-ins" and process them in batches: look first at each client’s weight trend and adherence. If adherence is high and weight isn’t moving as expected, adjust the plan; if adherence is low, the problem isn’t the numbers but the follow-through, and that calls for a conversation, not recalculating macros.',
      },
      {
        type: 'img',
        src: '/landing/feature-checkins.png',
        gradient: 'gradient-bg-learning',
        alt: 'Panel de check-ins semanales con puntuación de adherencia y último peso',
        es: 'El panel de Check-ins resume la adherencia y el último peso de cada cliente para que decidas en segundos y revises por lotes.',
        en: 'The Check-ins panel summarises each client’s adherence and last weight so you can decide in seconds and review in batches.',
      },
      {
        type: 'tip',
        es: 'Responde siempre con una sola acción concreta para la semana ("sube 20 g de hidratos en la comida post-entreno"). Un check-in sin una instrucción clara deja al cliente igual que estaba.',
        en: 'Always reply with a single concrete action for the week ("add 20 g of carbs to your post-workout meal"). A check-in without a clear instruction leaves the client exactly where they were.',
      },
    ],
  },
];
