/**
 * English content library for seed_planning_roadmaps.mjs.
 * EN_LIB[goal] = [phase0..phase3]; each phase = { en: { n, t } }.
 */
export const EN_LIB = {
  fat_loss: [
    { en: {
      n: { title: 'Metabolic adaptation', kcal: 'Maintenance', macros: '40 / 35 / 25', freq: '4 meals/day', water: '2.5–3 L/day',
        sum: 'A bridge phase before the deficit: habits, meal timing and food logging are consolidated so the cut starts from a stable base. No weight loss is sought yet — only control and consistency.',
        po: 'Stabilise weight at true maintenance calories and set a protein intake of 1.8–2.2 g/kg that will hold for the whole program.',
        so: ['Set a regular, repeatable weekday meal schedule', 'Learn to log portions with a scale for 14 days', 'Establish a hydration and 7–9 h sleep routine'],
        kpi: ['Food-logging adherence ≥ 90% of days', 'Weekly weight variation within ±0.5%', 'Daily protein ≥ 1.8 g/kg on 90% of days', 'Daily steps stabilised in the target range'],
        sc: ['The client logs every meal with no friction', 'Weight stays stable for 2 consecutive weeks', 'Hydration and sleep habits consolidated'],
        notes: 'It is common to discover here that true maintenance differs from the estimate: adjust calories from the 10–14 day weight trend, never from a single data point. Do not start the deficit until logging is reliable.',
        risk: ['Starting the deficit before maintenance is reliable', 'Under-logging oils, sauces and drinks', 'Client expecting weight loss already in this phase'] },
      t: { title: 'Strength readaptation', focus: 'Full-body strength', vol: '10–12 sets/muscle/wk', int: 'Moderate (RIR 3–4)', cardio: '2 LISS sessions, 30 min',
        sum: 'Strength training is reintroduced with conservative loads to recover technique and movement patterns before demanding intensity. The goal is to build tolerance, not fatigue.',
        po: 'Recover technique on the basic patterns (squat, hinge, push, pull) and work capacity at RIR 3–4.',
        so: ['Establish 3 sustainable weekly strength sessions', 'Document starting loads for each key lift', 'Introduce low-intensity cardio without hurting strength'],
        kpi: ['Attendance ≥ 90% of scheduled sessions', 'Technique validated by video on the 4 basic patterns', 'Load progression logged week to week', 'No joint pain after sessions'],
        sc: ['3 weekly sessions completed without discomfort', 'Stable technique on basics at RIR 3–4', 'Cardio integrated without hurting recovery'],
        notes: 'Prioritise movement quality over load. If the client is coming off a long break, expect marked soreness in the first two weeks; do not mistake it for overtraining.',
        risk: ['Progressing load too fast and causing joint pain', 'Excess cardio interfering with recovery', 'Skipping the warm-up due to lack of time'],
        it: ['RIR 3–4 on main sets', 'Specific warm-up 8–10 min', 'LISS cardio at 60–65% HRmax'] } } },
    { en: {
      n: { title: 'Progressive deficit', kcal: '−15% deficit', macros: '45 / 30 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'First real fat-loss phase: a moderate, sustainable deficit prioritising protein and satiety. The target rate is conservative to preserve lean mass and performance.',
        po: 'Drive fat loss of 0.5–0.75% of body weight per week while keeping muscle mass and training energy.',
        so: ['Keep protein high to maximise satiety', 'Prioritise nutrient-dense, high-volume foods', 'Manage hunger with fibre, fluids and meal spacing'],
        kpi: ['Weight loss averaging 0.5–0.75%/week', 'Calorie adherence ≥ 90% of days', 'Daily protein ≥ 2.0 g/kg', 'Strength held on the main lifts'],
        sc: ['Steady loss with no sharp drop in performance', 'Hunger reported as manageable', 'No relevant strength loss on basics'],
        notes: 'Review the deficit every 2 weeks: if loss exceeds 1%/wk, raise calories to limit lean-mass loss. Schedule one flexible meal a week to improve adherence.',
        risk: ['Deficit too aggressive with muscle-mass loss', 'Adherence dropping on weekends', 'NEAT falling from fatigue (fewer spontaneous steps)'] },
      t: { title: 'Strength & conditioning', focus: 'Strength + metabolic', vol: '12–16 sets/muscle/wk', int: 'Moderate-high (RIR 2–3)', cardio: '3 sessions (2 LISS + 1 HIIT)',
        sum: 'Training keeps the strength stimulus as the muscle-mass insurance and adds metabolic work to raise expenditure. Intensity rises in a controlled way.',
        po: 'Preserve strength and muscle mass through the deficit while increasing energy expenditure with conditioning.',
        so: ['Maintain or progress loads despite the deficit', 'Add metabolic work without hurting recovery', 'Sustain a high daily step volume'],
        kpi: ['Loads held within ±5% on the basics', 'Attendance ≥ 90% to strength and conditioning', 'Daily steps on target 90% of days', 'Session RPE within plan'],
        sc: ['Strength preserved on squat, deadlift and press', 'Conditioning completed without accumulated fatigue', 'Adequate recovery between sessions'],
        notes: 'In a deficit, strength is the key sign that muscle is being kept: if it falls steadily the problem is nutritional, not training. Match HIIT to the client’s real recovery.',
        risk: ['Accumulating fatigue from too much HIIT in a deficit', 'Cutting loads "because it is diet time" with no need', 'Neglecting sleep and hurting recovery'],
        it: ['RIR 2–3 on main sets', 'HIIT 8–10 intervals at 85–90% HRmax', 'LISS 60–65% HRmax 30–40 min'] } } },
    { en: {
      n: { title: 'Intensive cut', kcal: '−20% deficit', macros: '45 / 30 / 25', freq: '4–5 meals/day', water: '3–3.5 L/day',
        sum: 'The most demanding stretch: the deficit deepens to speed up loss once the client has solid habits. It requires close monitoring of performance and recovery.',
        po: 'Maximise fat loss while preserving muscle mass, bringing the client to the target physique without compromising health.',
        so: ['Maximise satiety with protein and a high vegetable volume', 'Schedule strategic refeeds to sustain performance', 'Monitor fatigue, hunger and mood signals'],
        kpi: ['Loss of 0.5–1%/week depending on composition', 'Adherence ≥ 92% despite the deeper deficit', 'Daily protein ≥ 2.2 g/kg', 'Fatigue markers within range'],
        sc: ['Target physique reached or very close', 'No marked loss of strength or health', 'Client reaches a stable maintenance phase'],
        notes: 'This phase should not run more than 4–6 consecutive weeks. If clear metabolic-fatigue signs appear (extreme hunger, insomnia, performance drop), introduce a diet break at maintenance.',
        risk: ['Extending the deep deficit longer than advisable', 'Muscle loss from insufficient protein or stimulus', 'Negative impact on sleep, hormones or mood'] },
      t: { title: 'Intensification & retention', focus: 'Heavy strength + cardio', vol: '10–14 sets/muscle/wk', int: 'High (RIR 1–2)', cardio: '3–4 mixed sessions',
        sum: 'Volume drops slightly and intensity rises: heavy work is the signal that protects muscle mass when calories are lowest. Cardio covers the remaining expenditure.',
        po: 'Deliver a high-intensity strength stimulus that retains muscle mass while the deficit is at its deepest.',
        so: ['Keep loads high while cutting volume to manage fatigue', 'Cover the target expenditure with cardio without cannibalising recovery', 'Protect technique when fatigue is high'],
        kpi: ['Main loads held despite the deficit', 'Attendance ≥ 90% to every session', 'Cardio expenditure within the weekly target', 'RPE controlled and recovery reported as sufficient'],
        sc: ['Strength retained to the end of the deficit', 'No injuries or niggles from accumulated fatigue', 'Transition to maintenance with no muscle loss'],
        notes: 'Cut volume before intensity: keeping loads high with fewer sets is the best muscle-retention strategy in a deep deficit. Watch technique on the last reps.',
        risk: ['Injury from training heavy while fatigued', 'Volume too high to recover from', 'Cardio displacing energy the strength work needs'],
        it: ['RIR 1–2 on main sets', 'Mixed LISS + HIIT cardio per expenditure', 'Scheduled deload if RPE spikes'] } } },
    { en: {
      n: { title: 'Reverse & maintenance', kcal: 'Reverse → Maintenance', macros: '40 / 35 / 25', freq: '4 meals/day', water: '2.5–3 L/day',
        sum: 'The exit phase: calories rise gradually and in a controlled way to the new maintenance, avoiding rebound and locking in the result. It is as important as the deficit itself.',
        po: 'Restore energy balance by raising calories progressively and stabilise weight at the new maintenance.',
        so: ['Raise calories 5–8% per week prioritising carbohydrates', 'Keep protein high through the whole transition', 'Educate the client to sustain the result long term'],
        kpi: ['Weight stable within ±1% after the increase', 'Adherence to the reverse plan ≥ 90%', 'Energy and performance recovering upward', 'Relationship with food reported as healthy'],
        sc: ['Weight stabilised at the new maintenance', 'No significant fat rebound', 'Client autonomous with sustainable habits'],
        notes: 'Communicate clearly that a slight weight rise from glycogen and water is expected and is not fat. The success of this phase is stability, not continued loss.',
        risk: ['Jumping back to high calories and causing rebound', 'Client anxiety over the scale rising', 'Dropping logging too soon'] },
      t: { title: 'Maintenance & consolidation', focus: 'General strength', vol: '12–14 sets/muscle/wk', int: 'Moderate (RIR 2–3)', cardio: '2 optional LISS sessions',
        sum: 'Training returns to a volume and intensity sustainable long term. With more energy available it is time to rebuild strength and consolidate the habit.',
        po: 'Recover and consolidate strength performance using the calorie increase, leaving a sustainable routine.',
        so: ['Rebuild loads on the basics with the new energy intake', 'Cut cardio to a maintenance minimum', 'Set a routine the client can sustain alone'],
        kpi: ['Strength progressing as calories recover', 'Attendance ≥ 85% in the maintenance phase', 'Cardio reduced with no composition loss', 'Routine rated as sustainable by the client'],
        sc: ['Strength recovering or above the start', 'Stable routine the client keeps autonomously', 'Body composition preserved'],
        notes: 'Use the higher-energy window to beat strength records: it reinforces adherence and leaves the program ready for a new cycle if wanted.',
        risk: ['Quitting training once the "goal" is met', 'Keeping cardio unnecessarily high', 'Not planning the next block and losing the habit'],
        it: ['RIR 2–3 on main sets', 'Long-term sustainable volume', 'Cardio reduced to maintenance'] } } },
  ],
  muscle_gain: [
    { en: {
      n: { title: 'Surplus foundations', kcal: '+5% surplus', macros: '30 / 50 / 20', freq: '4–5 meals/day', water: '3 L/day',
        sum: 'Bulk start: a slight, clean surplus is set to begin the gain while minimising fat accumulation. Protein and peri-workout carbohydrates are prioritised.',
        po: 'Set a controlled +5% surplus with 1.8–2.2 g/kg of protein to begin muscle gain without excess fat.',
        so: ['Spread protein across 4–5 daily feedings', 'Concentrate carbohydrates around training', 'Build the habit of eating regularly and sufficiently'],
        kpi: ['Weight gain of 0.25–0.5%/week', 'Protein ≥ 1.8 g/kg on 90% of days', 'Calorie adherence ≥ 90%', 'Peri-workout carbohydrates met'],
        sc: ['Slow, controlled weight gain', 'No noticeable fat accumulation', 'Sufficient-eating habit consolidated'],
        notes: 'If the client "cannot eat that much", prioritise calorie density (whole dairy, nuts, oils) over food volume. Gain must be slow to be quality gain.',
        risk: ['Excessive surplus with disproportionate fat gain', 'Insufficient protein when raising carbohydrates', 'Skipping meals due to low appetite'] },
      t: { title: 'Hypertrophy base', focus: 'Full-body hypertrophy', vol: '12–14 sets/muscle/wk', int: 'Moderate (RIR 2–3)', cardio: '1–2 LISS sessions',
        sum: 'A phase of technical build-up and tolerable volume. The aim is to master the exercises and create work capacity before raising the demand.',
        po: 'Master the technique of the key exercises and set a volume base that can be progressed safely.',
        so: ['Standardise technique on every main exercise', 'Log starting loads and reps', 'Build tolerance to training volume'],
        kpi: ['Technique validated on all main exercises', 'Attendance ≥ 90%', 'Progression logged week to week', 'Mind-muscle connection reported as good'],
        sc: ['Solid technique on all patterns', 'Base volume tolerated without excess fatigue', 'Starting loads documented'],
        notes: 'Do not rush load increases: flawless technique now multiplies the results of later phases. Cardio stays minimal so it does not compete for resources.',
        risk: ['Prioritising load over technique from the start', 'Initial volume too high and early fatigue', 'Excess cardio stealing recovery'],
        it: ['RIR 2–3 on main sets', 'Controlled tempo on the eccentric', 'Mind-muscle connection as a priority'] } } },
    { en: {
      n: { title: 'Volume', kcal: '+10% surplus', macros: '30 / 50 / 20', freq: '5 meals/day', water: '3–3.5 L/day',
        sum: 'The central, highest-gain phase: the surplus widens to support the rise in training volume and intensity. Protein and peri-workout carbohydrates are non-negotiable.',
        po: 'Sustain a +10% surplus that supports load progression and maximises protein synthesis.',
        so: ['Increase carbohydrates to support training volume', 'Keep protein at 2.0–2.2 g/kg', 'Ensure complete pre- and post-workout meals'],
        kpi: ['Weight gain of 0.25–0.5%/week sustained', 'Calorie adherence ≥ 90%', 'Training energy reported as high', 'Daily carbohydrate target met'],
        sc: ['Continuous gain without excess fat', 'Workouts with energy and good performance', 'Progression supported by nutrition'],
        notes: 'If weight gain stalls for two weeks, raise calories 5%. Watch body-fat: if it rises too fast, trim the surplus rather than cutting the phase.',
        risk: ['Stalling from an insufficient surplus', 'Fat gain from a surplus that is too wide', 'Insufficient carbohydrates and a performance drop'] },
      t: { title: 'Progressive overload', focus: 'Block hypertrophy', vol: '16–20 sets/muscle/wk', int: 'High (RIR 1–2)', cardio: '1 optional LISS session',
        sum: 'The engine of the gain: volume and intensity rise systematically applying progressive overload week to week on already-consolidated technique.',
        po: 'Apply sustained progressive overload — more load, reps or sets — to maximise the hypertrophy stimulus.',
        so: ['Progress load or reps every microcycle', 'Increase volume gradually and tolerably', 'Take effective sets close to failure with good technique'],
        kpi: ['Weekly progression on at least one parameter per exercise', 'Target volume completed without failed sessions', 'Attendance ≥ 90%', 'Real RIR in the 1–2 range on key sets'],
        sc: ['Loads and reps rising steadily', 'High volume tolerated with good recovery', 'No prolonged plateaus'],
        notes: 'Progressive overload must be measurable: if a week shows no progress, check sleep, nutrition and fatigue management before adding more volume.',
        risk: ['Stalling from a lack of planned progression', 'Volume beyond recovery capacity', 'Losing technique while chasing failure'],
        it: ['RIR 1–2 on effective sets', 'Documented progressive overload', 'Deload every 4–6 weeks per fatigue'] } } },
    { en: {
      n: { title: 'Intensification', kcal: '+8% surplus', macros: '32 / 48 / 20', freq: '5 meals/day', water: '3.5 L/day',
        sum: 'The surplus is trimmed slightly to refine the quality of the gain while training enters its most intense phase. Peri-workout nutrition is maximal.',
        po: 'Refine the composition of the gain with a slightly more conservative surplus, keeping fuel for intense training.',
        so: ['Adjust the surplus to limit fat gain', 'Maximise peri-workout nutrition to support intensity', 'Keep protein high for recovery'],
        kpi: ['Quality weight gain ≤ 0.4%/week', 'Body-fat controlled', 'Adherence ≥ 90%', 'Between-session recovery reported as sufficient'],
        sc: ['Muscle gain with body-fat under control', 'Enough energy for the intense sessions', 'Good recovery despite the higher demand'],
        notes: 'Here the goal shifts from "gain as much as possible" to "gain as well as possible". If body-fat rises, protect quality by trimming the surplus, never the protein.',
        risk: ['Keeping a wide surplus when it is no longer needed', 'Insufficient recovery from the intensity jump', 'Neglecting peri-workout nutrition'] },
      t: { title: 'Strength-hypertrophy peak', focus: 'Strength + hypertrophy', vol: '12–16 sets/muscle/wk', int: 'Very high (RIR 0–1)', cardio: 'Minimal',
        sum: 'Volume drops to allow maximal intensities: working in strength ranges boosts the gains and consolidates the muscle built in the volume block.',
        po: 'Expose the muscle to maximal loads in strength ranges to boost the gains from the volume block.',
        so: ['Train the basics in 3–6 rep ranges', 'Reduce volume to sustain intensity', 'Manage fatigue with timely deloads'],
        kpi: ['Strength records on the main lifts', 'RIR 0–1 reached with intact technique', 'Attendance ≥ 90%', 'Fatigue managed with no performance drops'],
        sc: ['Strength marks beaten', 'Muscle from the previous block consolidated', 'No injuries from the high intensity'],
        notes: 'Maximal intensity demands respect: thorough warm-up, perfect technique and timely deloads. A well-timed deload pays off more than a forced week.',
        risk: ['Injury from high intensity with compromised technique', 'Skipping deloads and accumulating fatigue', 'Keeping high volume incompatible with the intensity'],
        it: ['RIR 0–1 on main sets', '3–6 rep ranges on basics', 'Scheduled deload at the end of the block'] } } },
    { en: {
      n: { title: 'Consolidation', kcal: 'Maintenance', macros: '30 / 45 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'Closing phase: calories return to maintenance to stabilise the gained weight and let the body assimilate the adaptations. It prepares the transition to the next goal.',
        po: 'Stabilise the achieved weight and composition, consolidating habits before a possible cutting deficit.',
        so: ['Bring calories to the new maintenance in a controlled way', 'Keep protein high to preserve mass', 'Decide the next goal with the client'],
        kpi: ['Weight stable within ±1%', 'Muscle mass preserved', 'Adherence ≥ 85%', 'Energy and digestion reported as good'],
        sc: ['Weight and composition stabilised', 'Gained mass preserved with no losses', 'Clear plan for the next cycle'],
        notes: 'Do not chain bulk after bulk indefinitely. This phase lets you assess results clearly and decide whether a mini-cut is worthwhile before gaining again.',
        risk: ['Staying in surplus with no need and accumulating fat', 'Cutting protein when dropping to maintenance', 'Not planning the next block'] },
      t: { title: 'Gain maintenance', focus: 'General hypertrophy', vol: '10–12 sets/muscle/wk', int: 'Moderate (RIR 2–3)', cardio: '1–2 LISS sessions',
        sum: 'Training drops to a maintenance volume that keeps the built muscle with less fatigue. It is a consolidation phase, not aggressive progression.',
        po: 'Preserve the gained muscle and strength with a sustainable volume while the body recovers from the intense block.',
        so: ['Keep loads with a reduced maintenance volume', 'Allow full nervous-system recovery', 'Close the cycle leaving the routine ready for the next goal'],
        kpi: ['Loads held with reduced volume', 'Attendance ≥ 85%', 'Fatigue indicators normalised', 'Client recovered and motivated for the next block'],
        sc: ['Muscle and strength preserved', 'Fatigue from the intense block dissipated', 'Client ready for the next cycle'],
        notes: 'A maintenance volume (half the progression volume) is enough to keep the gains. Use it to fix imbalances and mobility.',
        risk: ['Cutting the stimulus so much that muscle is lost', 'Prolonging maintenance with no new goal', 'Neglecting mobility and imbalances'],
        it: ['RIR 2–3 on main sets', 'Maintenance volume', 'Mobility and corrective work'] } } },
  ],
  body_recomposition: [
    { en: {
      n: { title: 'Recalibration', kcal: 'Maintenance', macros: '40 / 35 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'Recomposition demands precision: this phase establishes true maintenance and high protein, the conditions required to gain muscle and lose fat at once.',
        po: 'Determine true maintenance calories and set protein at 2.0–2.4 g/kg as the base of the whole recomposition.',
        so: ['Validate maintenance with the 2-week weight trend', 'Establish very high, constant protein', 'Build the habit of precise food logging'],
        kpi: ['Weight stable within ±0.5% at maintenance', 'Protein ≥ 2.0 g/kg on 95% of days', 'Logging adherence ≥ 90%', 'Consistently high food quality'],
        sc: ['True maintenance reliably identified', 'High protein consolidated as a habit', 'Precise, frictionless food logging'],
        notes: 'Recomposition is slow and barely shows on the scale: explain from the start that progress will be measured with photos, measurements and strength, not weight alone.',
        risk: ['Expecting fast changes on the scale', 'Insufficient protein slowing muscle gain', 'Imprecise logging that invalidates adjustments'] },
      t: { title: 'Strength base', focus: 'Full-body strength', vol: '12–14 sets/muscle/wk', int: 'Moderate (RIR 2–3)', cardio: '2 LISS sessions',
        sum: 'The strength stimulus drives recomposition: this phase builds the technique and base that muscle gain in a slight deficit will depend on.',
        po: 'Build a solid base of strength and technique that allows progress even at neutral or slightly negative energy balance.',
        so: ['Consolidate technique on the basic patterns', 'Document starting loads', 'Establish a sustainable 3–4 session routine'],
        kpi: ['Technique validated on the basic patterns', 'Attendance ≥ 90%', 'Load progression logged', 'Adequate recovery between sessions'],
        sc: ['Solid technical base on all patterns', 'Stable, sustainable routine', 'Starting loads documented'],
        notes: 'In recomposition, strength progress is the best sign that muscle is being gained, since the scale barely moves. Make it the primary KPI.',
        risk: ['Prioritising load over technique', 'Excessive initial volume', 'Not documenting loads and losing the progress reference'],
        it: ['RIR 2–3 on main sets', 'Technique as a priority', 'Strength progress as the central KPI'] } } },
    { en: {
      n: { title: 'Recomposition — Block A', kcal: 'Cyclic ±10%', macros: '42 / 33 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'Cyclic nutrition is introduced: a slight surplus on training days and a slight deficit on rest days. This steers calories toward muscle and fat loss.',
        po: 'Apply a cyclic calorie split that places energy on training days and the deficit on rest days.',
        so: ['Concentrate carbohydrates on training days', 'Slightly reduce calories on rest days', 'Keep protein constant regardless of the day'],
        kpi: ['Weight stable or a very slight drop (≤ 0.25%/wk)', 'Adherence to the cyclic scheme ≥ 90%', 'Daily protein ≥ 2.2 g/kg', 'Measurements and photos showing composition improvement'],
        sc: ['Body composition improving with stable weight', 'Cyclic scheme applied with adherence', 'Strength progressing'],
        notes: 'Success here is not losing weight — it is the waist going down and strength going up with weight almost unchanged. Measure every 2 weeks with photos and girths.',
        risk: ['Confusing the cyclic split and unbalancing the week', 'Frustration over the scale not moving', 'Protein varying by day'] },
      t: { title: 'Hypertrophy', focus: 'Hypertrophy split', vol: '14–18 sets/muscle/wk', int: 'High (RIR 1–2)', cardio: '2 LISS sessions',
        sum: 'Volume rises to maximise the hypertrophy stimulus: with cyclic nutrition steered toward muscle, this is the block that contributes the most gain.',
        po: 'Maximise the hypertrophy stimulus with high volume, using the energy of training days.',
        so: ['Increase effective volume per muscle group', 'Progress loads on surplus days', 'Sustain low-intensity cardio without interference'],
        kpi: ['Target volume completed per muscle group', 'Load progression on training days', 'Attendance ≥ 90%', 'Muscle girths increasing'],
        sc: ['Muscle gain visible in measurements and photos', 'High volume well tolerated', 'Strength progressing steadily'],
        notes: 'Use the higher-energy days for the most demanding sessions and place weak groups at the start of the week. Keep cardio easy so it does not compete.',
        risk: ['Volume above recovery capacity at tight balance', 'Excess cardio interfering with hypertrophy', 'Poor weekly volume distribution'],
        it: ['RIR 1–2 on effective sets', 'High progressive volume', 'Hard sessions on surplus days'] } } },
    { en: {
      n: { title: 'Recomposition — Block B', kcal: 'Cyclic ±10%', macros: '42 / 33 / 25', freq: '4–5 meals/day', water: '3–3.5 L/day',
        sum: 'The cyclic scheme continues, fine-tuned to the individual response. Peri-workout nutrition gains importance as intensity rises.',
        po: 'Sustain cyclic nutrition, adjusting it to the client’s real response, and reinforce peri-workout nutrition.',
        so: ['Adjust the amplitude of the cycling per results', 'Reinforce pre- and post-workout meals', 'Keep protein very high for recovery'],
        kpi: ['Continuous composition improvement with stable weight', 'Adherence ≥ 90%', 'Protein ≥ 2.2 g/kg', 'Strength at program highs'],
        sc: ['Composition clearly improved from the start', 'Cyclic scheme fine-tuned and effective', 'Strength at peak levels'],
        notes: 'If after 4 weeks composition is not improving, the issue is almost always the total weekly balance: check it before touching the per-day split.',
        risk: ['Not adjusting the plan to the individual response', 'Insufficient peri-workout nutrition for the intensity', 'Real weekly balance differing from the plan'] },
      t: { title: 'Strength-hypertrophy', focus: 'Strength + hypertrophy', vol: '12–16 sets/muscle/wk', int: 'Very high (RIR 0–2)', cardio: '2 LISS sessions',
        sum: 'The block combines heavy strength work with hypertrophy to consolidate muscle and raise performance, closing the most demanding phase.',
        po: 'Combine heavy strength and hypertrophy to consolidate muscle mass and maximise performance.',
        so: ['Include heavy strength work on the basics', 'Keep hypertrophy on the accessories', 'Manage fatigue with planned deloads'],
        kpi: ['Strength records on the main lifts', 'Hypertrophy volume completed on accessories', 'Attendance ≥ 90%', 'Fatigue controlled with deloads'],
        sc: ['Program-best strength reached', 'Muscle consolidated and visible', 'No injuries from the high intensity'],
        notes: 'Place heavy work at the start of the session (fresh nervous system) and hypertrophy after. Respect deloads: they are part of progress, not a pause.',
        risk: ['Accumulating fatigue by stacking heavy strength and hypertrophy', 'Skipping deloads', 'Losing technique on heavy sets'],
        it: ['RIR 0–1 on strength, RIR 1–2 on accessories', 'Heavy first, hypertrophy after', 'Deload at the end of the block'] } } },
    { en: {
      n: { title: 'Consolidation', kcal: 'Maintenance', macros: '40 / 35 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'Closing the process: calories stabilise at maintenance and the recomposition result is assessed with every metric. The next step is planned.',
        po: 'Stabilise maintenance and consolidate the new body composition, leaving sustainable habits.',
        so: ['Set stable post-recomposition maintenance', 'Keep protein as a permanent habit', 'Assess results and plan the next goal'],
        kpi: ['Weight and composition stable', 'Adherence ≥ 85%', 'High protein kept as a habit', 'Client autonomous with their nutrition'],
        sc: ['New composition consolidated and stable', 'Sustainable nutritional habits', 'Clear plan for the next cycle'],
        notes: 'Review the start vs. end photos with the client: in recomposition the visual change is usually far greater than the scale change.',
        risk: ['Dropping the habits when the program ends', 'Not assessing the result with objective metrics', 'Lack of a new goal'] },
      t: { title: 'Maintenance', focus: 'General strength', vol: '10–12 sets/muscle/wk', int: 'Moderate (RIR 2–3)', cardio: '2 LISS sessions',
        sum: 'Training settles into a sustainable volume that keeps the gains and allows recovery from the intense block, leaving a long-term routine.',
        po: 'Preserve the achieved strength and mass with a sustainable routine and recover accumulated fatigue.',
        so: ['Keep loads with a sustainable volume', 'Allow full recovery', 'Leave a routine the client sustains autonomously'],
        kpi: ['Loads preserved', 'Attendance ≥ 85%', 'Fatigue normalised', 'Routine rated as sustainable'],
        sc: ['Strength and composition gains preserved', 'Fatigue dissipated', 'Autonomous routine established'],
        notes: 'Document the full strength progress: it is the best motivation tool and the starting point of the next cycle.',
        risk: ['Losing the habit when the program closes', 'Volume so low that gains are lost', 'Not planning continuity'],
        it: ['RIR 2–3 on main sets', 'Sustainable volume', 'Mobility work'] } } },
  ],
  performance: [
    { en: {
      n: { title: 'Accumulation — energy support', kcal: 'High maintenance', macros: '25 / 55 / 20', freq: '4–5 meals/day', water: '3–3.5 L/day',
        sum: 'Performance nutrition prioritises energy availability: in accumulation, carbohydrates are high to support work volume and recovery.',
        po: 'Cover the high energy demand of accumulation, guaranteeing enough glycogen session to session.',
        so: ['Keep carbohydrates high for work volume', 'Ensure protein for tissue recovery', 'Establish hydration and electrolyte protocols'],
        kpi: ['Training energy reported as high', 'Daily carbohydrate target met', 'Weight stable (no involuntary deficit)', 'Adequate between-session recovery'],
        sc: ['The client trains with energy all week', 'No signs of low energy availability', 'Recovery sufficient for the volume'],
        notes: 'Low energy availability is the most common error in athletes: make sure weight does not fall involuntarily with the high volume.',
        risk: ['Involuntary energy deficit from high volume', 'Insufficient carbohydrates and a performance drop', 'Neglected hydration and electrolytes'] },
      t: { title: 'Accumulation', focus: 'Volume + work capacity', vol: 'High — general base', int: 'Moderate (RIR 2–4)', cardio: 'Base aerobic conditioning',
        sum: 'A base-building phase: general work volume is accumulated to develop capacity, endurance and the base on which power will be built.',
        po: 'Develop a broad base of work capacity and endurance that supports the higher-intensity phases.',
        so: ['Accumulate training volume progressively', 'Develop the aerobic base and work capacity', 'Reinforce weak points and injury prevention'],
        kpi: ['Weekly volume completed as planned', 'Improvement in work-capacity tests', 'Attendance ≥ 90%', 'Tolerance to rising load'],
        sc: ['Work-capacity base established', 'High volume tolerated without injury', 'Weak points reinforced'],
        notes: 'In accumulation, intensity is secondary: the priority is tolerable volume and prevention. Build the engine before pressing the accelerator.',
        risk: ['Raising intensity too early', 'Volume beyond recovery capacity', 'Neglecting injury prevention'],
        it: ['RIR 2–4 on most work', 'Volume progressing week to week', 'Base aerobic work'] } } },
    { en: {
      n: { title: 'Transformation — sustained energy', kcal: 'High maintenance', macros: '25 / 55 / 20', freq: '5 meals/day', water: '3.5 L/day',
        sum: 'With training shifting to strength and power, nutrition ensures carbohydrate availability for high-quality sessions and full recovery.',
        po: 'Guarantee energy and recovery for high-quality strength-power sessions.',
        so: ['Concentrate carbohydrates around key sessions', 'Optimise recovery with protein and micronutrients', 'Adjust intake to higher- and lower-load days'],
        kpi: ['Quality of intense sessions maintained', 'Optimal between-session recovery', 'Weight and energy stable', 'Hydration within protocol'],
        sc: ['Power sessions executed with quality', 'Full recovery between stimuli', 'No energy dips'],
        notes: 'Here peri-workout nutrition is decisive: a power session without glycogen is a wasted session. Periodise carbohydrates to the day’s load.',
        risk: ['Insufficient carbohydrates on key-session days', 'Incomplete recovery between intense sessions', 'Not periodising intake to load'] },
      t: { title: 'Transformation', focus: 'Strength-power', vol: 'Medium — quality over quantity', int: 'High (RIR 1–3)', cardio: 'Specific conditioning',
        sum: 'Accumulated volume is transformed into strength and power: sessions prioritise the quality and intent of each rep over the amount of work.',
        po: 'Convert the capacity base into maximal strength and power applicable to the sport movement.',
        so: ['Train maximal strength on the main patterns', 'Introduce power and speed work', 'Reduce volume to sustain quality'],
        kpi: ['Maximal-strength improvements on the basics', 'Execution speed maintained on power work', 'Attendance ≥ 90%', 'Technical quality intact under fatigue'],
        sc: ['Strength and power clearly progressing', 'Quality work with no residual fatigue', 'More efficient sport movement'],
        notes: 'Power demands freshness: program explosive work at the start of the session and discard reps where speed clearly drops.',
        risk: ['Accumulating fatigue that degrades power quality', 'Keeping volume incompatible with the intensity', 'Training power in a fatigued state'],
        it: ['RIR 1–2 on maximal strength', 'Maximal intentional speed on power', 'Reduced volume, high quality'] } } },
    { en: {
      n: { title: 'Realisation — fine-tuning', kcal: 'Maintenance', macros: '25 / 55 / 20', freq: '4–5 meals/day', water: '3.5 L/day',
        sum: 'A fine-tuning phase toward the performance peak: nutrition optimises energy and recovery and prepares the carbohydrate-loading strategy for competition.',
        po: 'Optimise energy stores and recovery to reach the performance peak in optimal condition.',
        so: ['Keep glycogen full with less training volume', 'Rehearse the competition nutrition strategy', 'Maximise recovery and rest'],
        kpi: ['Sense of freshness and energy rising', 'Competition strategy rehearsed and validated', 'Weight stable in the competition range', 'Recovery perceived as complete'],
        sc: ['Client fresh with maximal energy', 'Competition protocol tested with no surprises', 'Energy stores optimised'],
        notes: 'Never try anything new on competition day: every loading, hydration or supplementation strategy must have been rehearsed in training.',
        risk: ['Trying new strategies on competition day', 'Poorly executed carbohydrate loading', 'Neglecting rest in the home stretch'] },
      t: { title: 'Performance peak', focus: 'Power + specific technique', vol: 'Low — fine-tuning', int: 'Very high (RIR 0–2)', cardio: 'Specific, reduced volume',
        sum: 'Loads are fine-tuned: low volume and high intensity to express the built performance without accumulating fatigue. Competition technique is the focus.',
        po: 'Express maximal performance by reducing volume and keeping intensity, arriving fresh at the peak.',
        so: ['Reduce volume to dissipate fatigue', 'Keep intensity to preserve adaptations', 'Polish competition-specific technique'],
        kpi: ['Performance marks at highs', 'Minimal residual fatigue', 'Competition technique consolidated', 'Attendance ≥ 90% to key sessions'],
        sc: ['Performance expressed at the highest level', 'Client fresh, no accumulated fatigue', 'Specific technique mastered'],
        notes: 'The classic mistake is over-training in the home stretch out of nerves. Keep intensity but cut volume without fear: the form is already built.',
        risk: ['Overtraining out of anxiety in the home stretch', 'Cutting intensity and losing adaptations', 'Arriving at the peak with residual fatigue'],
        it: ['RIR 0–2 on key sessions', 'Volume cut, intensity kept', 'Focus on competition technique'] } } },
    { en: {
      n: { title: 'Maintenance & recovery', kcal: 'Maintenance', macros: '28 / 50 / 22', freq: '4 meals/day', water: '3 L/day',
        sum: 'After the peak, nutrition supports recovery from the effort and keeps a solid base during transition or active rest.',
        po: 'Support post-competition recovery and sustain a solid nutritional base in the transition.',
        so: ['Ensure protein and micronutrients for recovery', 'Adjust calories to the lower training volume', 'Keep good habits during active rest'],
        kpi: ['Recovery perceived as complete', 'Weight stable despite lower volume', 'Adherence ≥ 85%', 'Energy and mood restored'],
        sc: ['Client recovered from the competitive effort', 'Nutritional base maintained', 'Good readiness for the next cycle'],
        notes: 'Adjust calories down as volume drops to avoid unnecessary fat gain, but without a deficit that would hinder recovery.',
        risk: ['Keeping loading-phase calories with little training', 'Dropping habits during the rest', 'Incomplete recovery before the next cycle'] },
      t: { title: 'Deload & maintenance', focus: 'Recovery + general base', vol: 'Low — deload', int: 'Low-moderate (RIR 3–5)', cardio: 'Easy regenerative aerobic',
        sum: 'A deload phase: the body assimilates the competitive cycle with light work that keeps the habit and prevents loss of adaptations.',
        po: 'Dissipate fatigue from the competitive cycle and keep a base level of activity and adaptations.',
        so: ['Reduce volume and intensity to recover', 'Keep the training habit with light work', 'Attend to mobility and any niggles'],
        kpi: ['Fatigue indicators normalised', 'Adherence ≥ 80% to light work', 'Mobility and niggles resolved', 'Motivation recovered for the next cycle'],
        sc: ['Cycle fatigue fully dissipated', 'Base adaptations preserved', 'Client ready and motivated to restart'],
        notes: 'A deload is not doing nothing: light regenerative work speeds recovery more than total rest. Use it to resolve niggles.',
        risk: ['Total rest that lets the athlete go stale', 'Returning to high volume with no prior deload', 'Ignoring niggles carried from competition'],
        it: ['RIR 3–5 on all work', 'Reduced volume and intensity', 'Regenerative and mobility work'] } } },
  ],
  endurance_focus: [
    { en: {
      n: { title: 'Aerobic base — support', kcal: 'Maintenance', macros: '20 / 60 / 20', freq: '4 meals/day', water: '3 L/day + electrolytes',
        sum: 'Endurance nutrition revolves around carbohydrates: in the base phase an intake is set that sustains running volume and hydration.',
        po: 'Cover the carbohydrate demand of base volume and consolidate hydration and electrolyte protocols.',
        so: ['Ensure enough carbohydrates for running volume', 'Establish hydration and electrolyte routines', 'Keep protein for muscle recovery'],
        kpi: ['Stable energy on runs', 'Daily carbohydrate target met', 'Hydration per protocol on every session', 'Weight stable during the phase'],
        sc: ['Runs completed with energy', 'Hydration protocol internalised', 'No signs of low energy availability'],
        notes: 'In runners, low energy availability is very common and silent: watch weight, energy and, in women, menstrual regularity.',
        risk: ['Low energy availability from rising volume', 'Insufficient hydration on long sessions', 'Carbohydrates below demand'] },
      t: { title: 'Aerobic base', focus: 'Base aerobic volume', vol: 'Progressive — easy runs', int: 'Low (Zone 2)', cardio: 'Core of the block',
        sum: 'Building the aerobic engine: easy, continuous runs that develop the endurance base on which all performance will be built.',
        po: 'Develop a broad aerobic base with progressive Zone 2 running volume.',
        so: ['Increase weekly volume gradually (10% rule)', 'Work mostly in Zone 2', 'Introduce preventive strength for the runner'],
        kpi: ['Weekly volume increased safely', 'Heart rate controlled in Zone 2', 'Efficiency improved (pace at equal HR)', 'No impact-related niggles'],
        sc: ['Aerobic base solidly broadened', 'Volume tolerated without injury', 'Running efficiency improved'],
        notes: 'The temptation to always run fast ruins the base: most volume must be comfortable. Preventive strength lowers impact-injury risk.',
        risk: ['Raising volume faster than the 10% rule', 'Running in zones too high and not building base', 'Impact injuries without preventive strength'],
        it: ['Most volume in Zone 2', 'Increase ≤ 10% per week', 'Preventive strength 1–2 sessions/wk'] } } },
    { en: {
      n: { title: 'Build — energy for quality', kcal: 'High maintenance', macros: '20 / 62 / 18', freq: '4–5 meals/day', water: '3.5 L/day + electrolytes',
        sum: 'As quality work (tempo and threshold) is introduced, carbohydrates rise to support harder sessions and intra-session fuelling is rehearsed.',
        po: 'Raise carbohydrate availability to support quality sessions and begin rehearsing intra-session nutrition.',
        so: ['Increase carbohydrates for tempo and intervals', 'Rehearse gels and drinks on long runs', 'Optimise recovery between quality sessions'],
        kpi: ['Quality sessions completed with energy', 'Intra-workout strategy rehearsed', 'Adequate between-session recovery', 'Digestive tolerance to in-run fuelling'],
        sc: ['Tempo and threshold executed with good energy', 'Intra-workout nutrition tolerated', 'Sufficient recovery between hard sessions'],
        notes: 'Digestive tolerance is trainable: start testing gels and drinks now, on long sessions, so the stomach does not fail on race day.',
        risk: ['Quality sessions without enough carbohydrates', 'Testing race nutrition without rehearsing it', 'Insufficient recovery between hard sessions'] },
      t: { title: 'Tempo & threshold', focus: 'Threshold and goal pace', vol: 'High — with quality work', int: 'Moderate-high (Zone 3–4)', cardio: 'Core of the block',
        sum: 'Quality work is introduced: tempo and threshold raise sustainable speed while base volume stays high.',
        po: 'Raise the threshold and consolidate goal pace by combining base volume with quality work.',
        so: ['Introduce weekly tempo and threshold sessions', 'Keep the base volume of easy running', 'Work the race goal pace'],
        kpi: ['Improvement in threshold pace', 'Goal pace sustainable for longer', 'Base volume kept alongside quality', 'Adequate recovery after hard sessions'],
        sc: ['Threshold clearly improved', 'Goal pace increasingly comfortable', 'Balance between volume and quality'],
        notes: 'Respect the 80/20 rule: quality work pays off only if most of the volume stays easy. Two quality sessions a week are usually enough.',
        risk: ['Too many quality sessions and accumulated fatigue', 'Sacrificing base volume for intensity', 'Poorly calibrated quality paces'],
        it: ['Tempo in Zone 3, intervals in Zone 4', '80/20 volume/quality rule', 'Goal pace on specific sessions'] } } },
    { en: {
      n: { title: 'Specific — competition fuelling', kcal: 'High maintenance', macros: '18 / 64 / 18', freq: '5 meals/day', water: '3.5 L/day + electrolytes',
        sum: 'In the specific phase nutrition focuses on maximising glycogen for key sessions and consolidating the race fuelling strategy.',
        po: 'Maximise glycogen stores for specific sessions and definitively validate the race strategy.',
        so: ['Ensure full glycogen on key sessions', 'Lock the fuelling strategy (what, how much, when)', 'Maximise recovery between specific sessions'],
        kpi: ['Specific sessions with maximal energy', 'Fuelling strategy defined and validated', 'Full recovery between key sessions', 'No digestive issues in-run'],
        sc: ['Specific sessions completed at goal pace', 'Fuelling plan finalised', 'Digestive tolerance confirmed'],
        notes: 'Write down the race fuelling plan: kilometre, product and amount. Improvised race nutrition is the #1 cause of DNF.',
        risk: ['Key sessions without enough glycogen', 'Fuelling strategy left unfinished', 'Unresolved digestive issues'] },
      t: { title: 'Specific work', focus: 'Intervals and race pace', vol: 'Medium-high — specific', int: 'High (Zone 4–5)', cardio: 'Core of the block',
        sum: 'Sessions replicate the demands of the race: intervals at competition pace that adapt the client to the real effort of the key day.',
        po: 'Adapt the client to the specific demands of the race with competition-pace sessions.',
        so: ['Run intervals at goal pace', 'Simulate race conditions (terrain, pace)', 'Sharpen pacing and effort management'],
        kpi: ['Intervals completed at goal pace', 'Sense of control over competition pace', 'Attendance ≥ 90% to key sessions', 'Adequate recovery despite the intensity'],
        sc: ['Competition pace mastered and sustainable', 'Specific sessions cleared with control', 'Client ready for the race demands'],
        notes: 'Simulate the race as much as possible: same time of day, similar terrain and the nutrition you will use. Confidence comes from having rehearsed it.',
        risk: ['Specific intensity without a sufficient base', 'Not simulating the real race conditions', 'Accumulating fatigue that carries into the taper'],
        it: ['Intervals in Zone 4–5', 'Race pace on specific sessions', 'Simulation of race conditions'] } } },
    { en: {
      n: { title: 'Tapering — carbohydrate loading', kcal: 'Carbohydrate loading', macros: '15 / 70 / 15', freq: '5–6 meals/day', water: '3.5 L/day + electrolytes',
        sum: 'Home stretch: volume drops and carbohydrate loading is executed to reach the race with full glycogen stores and the right weight.',
        po: 'Fill glycogen stores to the maximum through carbohydrate loading and reach the race in optimal condition.',
        so: ['Run the carbohydrate-loading protocol 2–3 days before', 'Keep hydration and electrolytes up', 'Choose familiar, easy-to-digest foods'],
        kpi: ['Carbohydrate loading executed per protocol', 'Weight slightly up from glycogen and water (expected)', 'No digestive issues in the days before', 'Energy and freshness perceived as maximal'],
        sc: ['Glycogen stores full for the race', 'Client arrives fresh with no digestive issues', 'Nutritional strategy fully finalised'],
        notes: 'Warn the client they will gain 1–2 kg of water and glycogen with the load: that is expected and it is fuel, not fat. Nothing new on the plate these days.',
        risk: ['Poorly executed or late carbohydrate loading', 'Trying new foods in the home stretch', 'Anxiety over the loading weight gain'] },
      t: { title: 'Tapering', focus: 'Volume reduction, freshness', vol: 'Low — progressive taper', int: 'Kept in short sessions', cardio: 'Core of the block, much reduced',
        sum: 'Volume drops sharply while keeping some intensity in short sessions: this dissipates fatigue without losing the built form.',
        po: 'Dissipate accumulated fatigue by cutting volume and reach the race fresh with form intact.',
        so: ['Cut volume 40–60% progressively', 'Keep touches of intensity in short sessions', 'Prioritise rest and sleep'],
        kpi: ['Volume reduced per the taper plan', 'Sense of freshness and "light legs"', 'Intensity kept in short sessions', 'Rest and sleep optimised'],
        sc: ['Fatigue fully dissipated', 'Fitness preserved despite lower volume', 'Client arrives fresh and confident at the race'],
        notes: 'Tapering makes runners nervous: explain that the feeling of "doing little" is a good sign. The form is built; now it is just rest.',
        risk: ['Over-training out of anxiety and arriving fatigued', 'Removing all intensity and losing sharpness', 'Neglecting rest in the home stretch'],
        it: ['Volume −40–60% progressive', 'Touches of intensity in short sessions', 'Rest and sleep as a priority'] } } },
  ],
  health: [
    { en: {
      n: { title: 'Habit activation', kcal: 'Maintenance', macros: '30 / 45 / 25', freq: '3–4 meals/day', water: '2–2.5 L/day',
        sum: 'The starting point toward a healthier life: meals are organised and diet quality improves with no aggressive restriction. Consistency is the priority.',
        po: 'Organise meal timing and improve food quality while building sustainable habits.',
        so: ['Establish a regular meal pattern', 'Increase vegetable, fruit and protein intake', 'Gradually reduce ultra-processed foods and sugary drinks'],
        kpi: ['Regular meals on 90% of days', 'A vegetable/fruit serving in every main meal', 'Measurable reduction of ultra-processed foods', 'Daily hydration on target'],
        sc: ['Stable, sustainable meal pattern', 'Clear improvement in diet quality', 'Basic hydration habits in place'],
        notes: 'Do not impose a rigid plan: in health, success is sustainability. Change one habit at a time and reinforce wins to keep motivation up.',
        risk: ['Imposing a too-restrictive, unsustainable diet', 'Changing too many habits at once', 'Focusing everything on weight rather than health'] },
      t: { title: 'Activation', focus: 'Mobility + basic strength', vol: 'Low — short sessions', int: 'Low (RIR 4–5)', cardio: 'Daily walking + 1 easy session',
        sum: 'The goal is to build the habit of moving: short, achievable sessions that create adherence without intimidating or causing excessive soreness.',
        po: 'Instil the physical-activity habit with short, safe and motivating sessions.',
        so: ['Establish 2–3 short weekly sessions', 'Reach a daily step goal', 'Improve mobility and reduce day-to-day niggles'],
        kpi: ['Attendance ≥ 80% to sessions', 'Daily step goal met', 'Subjective improvement in energy and mobility', 'No niggles after training'],
        sc: ['Movement habit established', 'Daily steps on target', 'More energy and fewer niggles reported'],
        notes: 'The barrier here is psychological, not physical: short, achievable sessions create more adherence than ambitious workouts the client abandons.',
        risk: ['Sessions too long or hard that cause rejection', 'Excessive soreness that demotivates', 'Setting unrealistic goals'],
        it: ['RIR 4–5, far from failure', 'Short, achievable sessions', 'Daily steps as the base'] } } },
    { en: {
      n: { title: 'Progression', kcal: 'Maintenance', macros: '30 / 45 / 25', freq: '4 meals/day', water: '2.5 L/day',
        sum: 'On top of the established habits, portions and meal composition are fine-tuned to the client’s specific goal (weight, energy, health).',
        po: 'Fine-tune portions and meal composition to align them with the client’s personal goal.',
        so: ['Adjust portions to the goal (maintain, lose, improve energy)', 'Improve the macro balance of each meal', 'Build the client’s autonomy in their choices'],
        kpi: ['Portions consistently adjusted to the goal', 'Balanced meals on 90% of days', 'Progress toward the personal goal', 'The client decides well without constant supervision'],
        sc: ['Nutrition aligned with the personal goal', 'Greater autonomy in day-to-day decisions', 'Visible progress toward the goal'],
        notes: 'Start transferring decisions to the client: teach them to choose, not just to follow. Autonomy is what makes the result last.',
        risk: ['Keeping the client dependent on the plan', 'Portion adjustments too abrupt', 'Losing sight of the real personal goal'] },
      t: { title: 'Progression', focus: 'Functional strength', vol: 'Moderate', int: 'Moderate (RIR 3–4)', cardio: '2 moderate sessions',
        sum: 'With the habit consolidated, load and exercise variety rise: the body is ready for a bigger stimulus that keeps producing improvements.',
        po: 'Increase load, variety and training quality on an already-consolidated habit base.',
        so: ['Introduce load progression on the base exercises', 'Broaden the variety of movement patterns', 'Moderately increase volume and intensity'],
        kpi: ['Load progression logged', 'Attendance ≥ 85%', 'Improvement in strength and functional capacity', 'Good tolerance to the load increase'],
        sc: ['Functional strength clearly improving', 'Exercise variety mastered', 'Load progressed without niggles'],
        notes: 'Here the client starts to feel capable: use strength progress as positive reinforcement to definitively consolidate adherence.',
        risk: ['Raising load faster than adaptation', 'Too much variety preventing progress in anything', 'Forgetting the mobility component'],
        it: ['RIR 3–4 on main sets', 'Gradual load progression', 'Variety of functional patterns'] } } },
    { en: {
      n: { title: 'Consolidation', kcal: 'Maintenance', macros: '30 / 45 / 25', freq: '4 meals/day', water: '2.5 L/day',
        sum: 'A sustainable, flexible way of eating is consolidated that the client can keep without supervision, integrating social life and unexpected events.',
        po: 'Consolidate flexible, sustainable eating that the client keeps autonomously.',
        so: ['Integrate social meals and flexibility without guilt', 'Reinforce strategies for unexpected events and travel', 'Confirm the client’s full autonomy'],
        kpi: ['The client handles social meals without derailing', 'Adherence ≥ 85% without close supervision', 'Strategies for unexpected events applied successfully', 'Healthy relationship with food reported'],
        sc: ['Flexible, sustainable eating consolidated', 'Client autonomous in any context', 'Healthy relationship with food'],
        notes: 'The success marker is not a perfect plate — it is the client knowing how to return to track after a deviation, with no guilt or rebound.',
        risk: ['Rigidity that does not survive social life', 'Guilt over any deviation', 'Residual dependence on the coach'] },
      t: { title: 'Consolidation', focus: 'Strength + mobility', vol: 'Moderate', int: 'Moderate (RIR 3–4)', cardio: '2 moderate sessions',
        sum: 'Training settles into a balanced strength-and-mobility routine the client can sustain indefinitely with good results.',
        po: 'Consolidate a balanced, sustainable routine that maintains strength, mobility and energy long term.',
        so: ['Balance strength, mobility and cardiovascular work', 'Ensure the routine fits the client’s life', 'Encourage autonomy in execution'],
        kpi: ['Routine sustained with autonomy', 'Attendance ≥ 85%', 'Strength and mobility stable or improving', 'Daily energy reported as high'],
        sc: ['Balanced, sustainable routine consolidated', 'Client autonomous and consistent', 'Good level of strength, mobility and energy'],
        notes: 'Make sure the routine is realistic for the client’s schedule: a perfect routine that does not fit their week is worthless.',
        risk: ['Routine unrealistic for the client’s schedule', 'Neglecting mobility by focusing on strength', 'Lack of variety reducing adherence'],
        it: ['RIR 3–4 on main sets', 'Strength/mobility/cardio balance', 'Routine adapted to real life'] } } },
    { en: {
      n: { title: 'Lifelong maintenance', kcal: 'Maintenance', macros: '30 / 45 / 25', freq: '4 meals/day', water: '2.5 L/day',
        sum: 'Final phase: healthy eating is now a lifestyle. The coach’s role shifts to light follow-up and occasional reinforcement.',
        po: 'Indefinitely maintain the healthy eating habits already consolidated.',
        so: ['Sustain habits without close supervision', 'Run periodic follow-up reviews', 'Adapt nutrition to the different life stages'],
        kpi: ['Habits maintained autonomously', 'Follow-up reviews with no relevant deviations', 'Health and energy stable over time', 'Client satisfaction with their lifestyle'],
        sc: ['Healthy eating turned into a lifestyle', 'Client fully autonomous', 'Health results maintained over time'],
        notes: 'Schedule spaced reviews (every 1–3 months) more as support and accountability than as control. Success is no longer needing you daily.',
        risk: ['Gradual relaxation of habits without follow-up', 'Not adapting nutrition to new life stages', 'Loss of motivation with no new goal'] },
      t: { title: 'Maintenance', focus: 'Sustainable activity', vol: 'Moderate sustainable', int: 'Moderate (RIR 3–4)', cardio: 'Regular varied activity',
        sum: 'Physical activity is now a life habit. The program is kept with enough variety to sustain motivation long term.',
        po: 'Indefinitely sustain a healthy, motivating level of physical activity.',
        so: ['Keep training regularity', 'Provide variety to sustain motivation', 'Set small challenges that keep interest alive'],
        kpi: ['Training regularity maintained', 'Enough variety reported as motivating', 'Fitness stable or improving', 'Adherence ≥ 80% long term'],
        sc: ['Physical activity consolidated as a life habit', 'Motivation sustained over time', 'Healthy fitness maintained'],
        notes: 'Variety and small challenges are the key to long-term adherence. Refresh the program periodically so it does not become monotonous.',
        risk: ['Monotony eroding motivation', 'No new challenges or goals', 'Dropping out after a change in life routine'],
        it: ['RIR 3–4 on main sets', 'Variety to sustain motivation', 'Periodic small challenges'] } } },
  ],
  metabolic_reset: [
    { en: {
      n: { title: 'Initial reverse', kcal: 'Reverse +5%/week', macros: '35 / 40 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'The metabolic reset begins by raising calories gradually out of a prolonged deficit, to recover the metabolism without triggering fat gain.',
        po: 'Raise calories progressively (~5%/week) out of the deficit and reactivate the metabolism.',
        so: ['Increase calories in a controlled way, mostly carbohydrates', 'Keep protein high during the rise', 'Educate the client on why the reverse is necessary'],
        kpi: ['Calories raised per the weekly plan', 'Weight stable or a very slight rise (expected)', 'Energy, sleep and mood improving', 'Adherence to the reverse protocol ≥ 90%'],
        sc: ['Calories increased without sharp fat gain', 'Wellbeing markers (energy, sleep) rising', 'Client understands and accepts the process'],
        notes: 'The reverse requires managing mindset: the client comes from "eating little = good". Explain that recovering the metabolism is what will make the next goal possible.',
        risk: ['Client fear of raising calories and gaining weight', 'Raising calories too fast', 'Cutting protein when increasing carbohydrates'] },
      t: { title: 'Reactivation', focus: 'Full-body strength', vol: '10–12 sets/muscle/wk', int: 'Moderate (RIR 2–4)', cardio: 'Reduced — only 1–2 LISS',
        sum: 'Strength training gives the incoming calories a destination: with more energy available, the body prioritises rebuilding muscle and performance.',
        po: 'Reactivate strength training to steer the recovered calories toward muscle.',
        so: ['Resume strength work with moderate loads', 'Cut the excess cardio carried from the deficit', 'Use the extra energy to progress'],
        kpi: ['Strength progression as calories recover', 'Attendance ≥ 90%', 'Cardio reduced to a reasonable minimum', 'Between-session recovery improving'],
        sc: ['Strength progressing with the calorie increase', 'Excess cardio trimmed', 'Better recovery reported'],
        notes: 'Many reset clients carry excess cardio from the deficit: cut it. The strength stimulus is what uses the calories that now do come in.',
        risk: ['Keeping excessive cardio that hinders recovery', 'Not using the extra energy to progress', 'Volume too high on restart'],
        it: ['RIR 2–4 on main sets', 'Cardio reduced to a minimum', 'Progression using the extra energy'] } } },
    { en: {
      n: { title: 'Stabilisation', kcal: 'Recovered maintenance', macros: '32 / 43 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'Calories stabilise at the new maintenance, higher than the starting one. This is the core goal of the reset: eating more while keeping composition.',
        po: 'Stabilise intake at the new metabolic maintenance, higher and more sustainable than the initial one.',
        so: ['Keep calories at the new maintenance', 'Confirm weight stability over several weeks', 'Consolidate a healthy, flexible relationship with food'],
        kpi: ['Weight stable at the new maintenance (±1%)', 'Maintenance calories notably higher than at the start', 'Energy and performance stabilising upward', 'Adherence ≥ 90%'],
        sc: ['New higher maintenance confirmed and stable', 'Weight and composition under control', 'Freer relationship with food'],
        notes: 'This is where the reset proves itself: the client eats considerably more than at the start and their weight is stable. Document it to reinforce confidence.',
        risk: ['Cutting calories again "out of habit"', 'Client insecurity with the higher intake', 'Not confirming stability before moving on'] },
      t: { title: 'Stabilisation', focus: 'General strength', vol: '12–14 sets/muscle/wk', int: 'Moderate (RIR 2–3)', cardio: '1–2 LISS sessions',
        sum: 'Training consolidates strength using the new stable energy intake, building on the previous phase’s reactivation.',
        po: 'Consolidate strength and work capacity backed by the new energy maintenance.',
        so: ['Progress loads with the now-stable energy', 'Moderately increase training volume', 'Consolidate a sustainable routine'],
        kpi: ['Sustained strength progression', 'Attendance ≥ 90%', 'Volume increased and well tolerated', 'Recovery reported as complete'],
        sc: ['Strength consolidated and progressing', 'Training volume successfully broadened', 'Stable, sustainable routine'],
        notes: 'With the metabolism recovered, performance should clearly improve: use it as tangible proof that eating more was the right call.',
        risk: ['Not using the stable energy to progress', 'Excessive volume too soon', 'Neglecting recovery'],
        it: ['RIR 2–3 on main sets', 'Sustained load progression', 'Moderate volume increasing'] } } },
    { en: {
      n: { title: 'Consolidation', kcal: 'Recovered maintenance', macros: '32 / 43 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'The recovered maintenance is consolidated and the client is prepared for their next goal — now from a much higher, healthier metabolic base.',
        po: 'Definitively consolidate the recovered maintenance and prepare the next goal.',
        so: ['Sustain the high maintenance stably', 'Reinforce flexibility and food autonomy', 'Decide the next step with the client (recomposition, gain...)'],
        kpi: ['High maintenance sustained with stability', 'Adherence ≥ 88%', 'Wellbeing markers consolidated', 'Clear plan for the next goal'],
        sc: ['Recovered maintenance fully consolidated', 'Client autonomous with a good relationship with food', 'Next goal defined'],
        notes: 'The reset is the means, not the end: the client can now face a deficit or surplus from a much higher base, with more room and a better response.',
        risk: ['Staying in the reset with no follow-up goal', 'Relapse into restrictive patterns', 'Not planning the next phase'] },
      t: { title: 'Consolidation', focus: 'General strength', vol: '12–14 sets/muscle/wk', int: 'Moderate-high (RIR 1–3)', cardio: '1–2 LISS sessions',
        sum: 'Training keeps a solid progression that fully uses the recovered metabolism, leaving the client ready for the next cycle.',
        po: 'Sustain solid strength progression that leaves the client ready for their next goal.',
        so: ['Keep load progression', 'Consolidate the recovered work capacity', 'Leave the routine ready for the next block'],
        kpi: ['Strength at program-high levels', 'Attendance ≥ 88%', 'Work capacity fully recovered', 'Client ready for the next cycle'],
        sc: ['Strength and work capacity at their best level', 'Routine ready for the next goal', 'Client motivated to continue'],
        notes: 'Close the cycle by documenting the full improvement: more food, more strength and stable weight is the proof of a well-executed reset.',
        risk: ['Closing the process with no planned continuity', 'Losing progression for lack of a goal', 'Neglecting recovery at the end of the cycle'],
        it: ['RIR 1–3 on main sets', 'Sustained progression', 'Routine ready for the next block'] } } },
    { en: {
      n: { title: 'Long-term maintenance', kcal: 'Recovered maintenance', macros: '30 / 45 / 25', freq: '4 meals/day', water: '3 L/day',
        sum: 'Closing phase: the recovered metabolism is maintained indefinitely and the client keeps a flexible, restriction-free relationship with food.',
        po: 'Indefinitely sustain the recovered metabolism and flexible, healthy eating.',
        so: ['Keep the recovered maintenance with no relapses', 'Sustain a free, flexible relationship with food', 'Run periodic follow-up reviews'],
        kpi: ['Recovered maintenance sustained over time', 'No relapse into restrictive patterns', 'Wellbeing and energy stable', 'Adherence ≥ 85% long term'],
        sc: ['Recovered metabolism kept stably', 'Healthy, flexible relationship with food consolidated', 'Client autonomous long term'],
        notes: 'The biggest long-term risk is relapsing into restriction. Reinforce with the client that their high maintenance is their new normal and their greatest achievement.',
        risk: ['Relapse into calorie restriction', 'Dropping follow-up', 'Loss of motivation with no new goal'] },
      t: { title: 'Maintenance', focus: 'Sustainable strength', vol: '10–12 sets/muscle/wk', int: 'Moderate (RIR 2–3)', cardio: '1–2 LISS sessions',
        sum: 'Training settles into a sustainable routine that keeps the strength and work capacity recovered during the reset.',
        po: 'Indefinitely preserve the strength and work capacity recovered with a sustainable routine.',
        so: ['Keep a sustainable strength routine', 'Preserve the recovered work capacity', 'Provide variety to sustain adherence'],
        kpi: ['Strength and capacity preserved', 'Attendance ≥ 80% long term', 'Routine rated as sustainable', 'Motivation maintained'],
        sc: ['Strength and work capacity preserved', 'Sustainable routine consolidated', 'Client consistent and motivated'],
        notes: 'Keep the program alive with variety and small challenges: long-term consistency is what protects everything achieved with the reset.',
        risk: ['Loss of consistency with no new goal', 'Program monotony', 'Dropping out after changes in life routine'],
        it: ['RIR 2–3 on main sets', 'Long-term sustainable routine', 'Variety and small challenges'] } } },
  ],
};
