import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { fetchWithAuth } from '../api';
import { useAuth } from './AuthContext';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string, params?: Record<string, string | number>) => string;
  isLoading: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Nav
    dashboard: "Panel de Control",
    tasks: "Tareas",
    calendar: "Calendario",
    clients: "Clientes",
    checkins: "Check-ins",
    messages: "Mensajes",
    nutrition: "Nutrición",
    training: "Entrenamiento",
    foods: "Alimentos",
    exercises: "Ejercicios",
    onboarding: "Onboarding",
    analytics: "Analítica",
    settings: "Configuración",
    
    // Dashboard (Manager)
    welcome_manager: "Buenos días, Manager",
    today: "Hoy",
    pending_attention: "Tienes {count} elementos pendientes que requieren tu atención.",
    search_clients_foods: "Buscar clientes, alimentos...",
    quick_actions: "Acciones Rápidas",
    add_new_client: "Añadir Nuevo Cliente",
    schedule_appointment: "Programar Cita",
    manage_automations: "Gestionar Automatizaciones",
    broadcast_message: "Difundir Mensaje",
    attention_required: "Atención Requerida",
    loading_items: "Cargando elementos...",
    no_pending_items: "¡No hay tareas pendientes! Gran trabajo.",
    view_all_items: "Ver Todos los Elementos",
    schedule_today: "Horario de Hoy",
    view_calendar: "Ver Calendario",
    no_events_today: "No hay eventos programados para hoy.",
    active_clients: "Clientes Activos",
    since_last_month: "desde el mes pasado",
    latest_updates: "Últimas Actualizaciones",
    fetching_updates: "Obteniendo Actualizaciones...",
    view_activity_history: "Ver Historial de Actividad",
    no_recent_activity: "No se encontró actividad reciente.",
    review: "Revisar",
    resolve: "Resolver",

    // Dashboard (Client)
    good_morning: "Buenos días",
    good_afternoon: "Buenas tardes",
    good_evening: "Buenas noches",
    log_checkin: "Registrar Check-in",
    view_meals: "Ver Comidas",
    start_workout: "Empezar Entreno",
    message_coach: "Mensaje al Coach",
    todays_plan: "Plan de Hoy",
    view_full_plan: "Ver Plan Completo",
    rest_day: "Día de descanso — sin ejercicios planeados",
    view_training_schedule: "Ver Horario de Entreno",
    meals_today: "Comidas de Hoy",
    kcal_total: "kcal totales",
    no_meals_defined: "No hay comidas definidas en tu plan",
    view_nutrition_plan: "Ver Plan de Nutrición",
    weekly_adherence: "Adherencia Semanal",
    based_on_last_7_days: "Basado en los últimos 7 días",
    current_streak: "Racha Actual",
    day: "Día",
    days: "Días",
    keep_it_up: "¡Sigue así!",
    start_journey_today: "Empieza tu viaje hoy",
    coach_notes: "Notas del Coach",
    no_coach_notes: "Sin notas de tu coach todavía.",
    open_messenger: "Abrir Mensajería",
    next_up: "Siguiente",
    units: "unidades",

    // Settings Profile
    profile_details: "Detalles del Perfil",
    full_name: "Nombre Completo",
    professional_title: "Título Profesional",
    bio: "Biografía",
    language: "Idioma",
    save_profile: "Guardar Perfil",
    discard_changes: "Descartar Cambios",
    profile_photo: "Foto de Perfil",
    profile_photo_desc: "Esto se mostrará en tu perfil.",
    change: "Cambiar",
    remove: "Eliminar",
    contact_info: "Información de Contacto",
    contact_info_desc: "Cómo pueden contactarte tus clientes.",
    email_address: "Correo Electrónico",
    phone_number: "Número de Teléfono",
    professional_address: "Dirección Profesional",
    social_profiles: "Perfiles Sociales",
    social_profiles_desc: "Conecta tus redes sociales.",
    email_not_changeable: "El correo no se puede cambiar aquí.",
    saving: "Guardando...",
    
    // Appearance
    appearance: "Apariencia",
    theme_color: "Color del Tema",
    theme_color_desc: "Selecciona un color principal para tu espacio de trabajo.",
    dark_mode: "Modo Oscuro",
    appearance_desc: "Personaliza el aspecto de tu plataforma.",

    // General & Tabs
    general: "General",
    profile: "Perfil",
    security: "Seguridad",
    integrations: "Integraciones",
    language_region: "Idioma y Región",
    configure_language_format: "Configura tu idioma preferido y formatos regionales.",
    select_language: "Seleccionar Idioma",
    spanish: "Español",
    english: "Inglés",
    timezone: "Zona Horaria",
    date_format: "Formato de Fecha",
    currency: "Moneda",

    // Settings General
    settings_header: "Configuración",
    settings_desc: "Gestiona tus preferencias de cuenta, apariencia y notificaciones.",
    sign_out: "Cerrar Sesión",
    personal_details: "Detalles Personales",
    personal_details_desc: "Actualiza tu foto y detalles personales aquí.",
    profile_saved: "¡Perfil guardado correctamente!",
    
    // Security
    change_password: "Cambiar Contraseña",
    security_desc: "Asegúrate de que tu cuenta use una contraseña larga y aleatoria.",
    new_password: "Nueva Contraseña",
    confirm_password: "Confirmar Nueva Contraseña",
    update_password: "Actualizar Contraseña",
    updating: "Actualizando...",
    password_updated: "¡Contraseña actualizada correctamente!",
    two_factor: "Autenticación de Dos Factores",
    two_factor_desc: "Añade una capa extra de seguridad usando una app de autenticación.",
    active_sessions: "Sesiones Activas",
    sessions_desc: "Gestiona los dispositivos con sesión iniciada.",
    active_now: "Activo ahora",
    revoke_session: "Cerrar sesión",
    logout_all: "Cerrar sesión en todos los dispositivos",
    login_history: "Historial de Inicio de Sesión",
    login_history_desc: "Actividad reciente de la cuenta e intentos de inicio de sesión.",
    device: "Dispositivo",
    location: "Ubicación",
    date: "Fecha",
    status: "Estado",
    no_active_sessions: "No hay otras sesiones activas.",
    
    // Billing
    billing: "Facturación",
    current_plan: "Plan Actual",
    manage_subscription: "Gestiona los detalles de tu suscripción",
    active: "Activo",
    professional_plan: "Plan Profesional",
    professional_plan_desc: "Para profesionales de nutrición en crecimiento",
    change_plan: "Cambiar Plan",
    renews_on: "Se renueva el {date}",
    payment_method: "Método de Pago",
    update_billing: "Actualiza tu información de facturación",
    visa_ending: "Visa terminada en {last4}",
    default: "Predeterminado",
    expiry: "Expira {date}",
    update: "Actualizar",
    billing_history: "Historial de Facturación",
    billing_history_desc: "Descarga tus facturas pasadas",
    invoice_date: "Fecha de Factura",
    plan: "Plan",
    amount: "Cantidad",
    invoice: "Factura",
    paid: "Pagado",

    // Integrations
    google_calendar: "Google Calendar",
    google_calendar_desc: "Sincroniza tus citas y horarios con Google Calendar.",
    connection_status: "Estado de Conexión",
    sync_active: "Sincronización activa",
    not_connected: "No conectado",
    google_api_key: "Google API Key",
    google_calendar_id: "ID del Calendario",
    google_service_account: "Google Service Account JSON",
    google_service_account_desc: "Pega el contenido del archivo JSON de tu Cuenta de Servicio.",
    sync_existing: "Sincronizar tareas existentes ahora",
    test_connection: "Probar conexión",
    stripe_payments: "Pagos con Stripe",
    stripe_payments_desc: "Conecta tu cuenta para ver tus ingresos y facturación.",
    stripe_status: "Estado de Stripe",
    connected_stripe: "Conectado a Stripe",
    publishable_key: "Publishable Key",
    secret_key: "Secret Key",
    save_all_integrations: "Guardar Todas las Integraciones",
    test_stripe: "Probar Stripe",
    
    // Notifications
    notification_preferences: "Preferencias de Notificación",
    notification_prefs_desc: "Elige cómo y cuándo quieres ser notificado.",
    event_type: "Tipo de Evento",
    email: "Email",
    push: "Push",
    new_client_check_ins_desc: "Cuando un cliente envía su progreso semanal.",
    new_messages_desc: "Mensajes directos de clientes.",
    appointment_reminders_desc: "1 hora antes de la sesión programada.",
    system_updates_desc: "Noticias del producto y mantenimiento.",
    cancel: "Cancelar",
    save_notification_prefs: "Guardar Preferencias de Notificación",

    // Nutrition
    nutrition_header: "Nutrición",
    goal: "Objetivo",
    age: "Edad",
    weight: "Peso",
    no_plan_yet: "Sin Plan Aún",
    start_from_template: "Empezar desde una Plantilla",
    create_new_plan: "Crear Nuevo Plan",
    create_new_plan_desc: "Empezar desde cero con macros personalizados",
    recommended_for_planning: "Recomendado para la planificación actual",
    week_view: "Vista Semanal",
    selected: "Seleccionado",
    plan_settings: "Configuración del Plan",
    target_calories: "Calorías Objetivo",
    daily_structure: "Estructura Diaria",
    macro_split: "Reparto de Macros",
    create_draft_plan: "Crear Plan Borrador",
    calories: "Calorías",
    meals: "Comidas",
    protein: "Proteína",
    carbs: "Carbohidratos",
    fats: "Grasas",
    fat_loss_basic: "Pérdida de Grasa Básica",
    conservative_cut: "Corte conservador",
    active_maintain: "Mantenimiento Activo",
    recommended_current_goal: "Recomendado para el objetivo actual",
    moderate_gain: "Ganancia Moderada",
    lean_bulk_approach: "Enfoque de volumen limpio",
    active_build: "Construcción Activa",
    standard_muscle_gain: "Ganancia muscular estándar",
    athlete_perform: "Rendimiento Atleta",
    sport_performance: "Rendimiento deportivo",
    mass_builder: "Constructor de Masa",
    significant_surplus: "Superávit significativo",
    power_lifting: "Powerlifting",
    strength_focus: "Enfoque en fuerza",
    extreme_bulk: "Volumen Extremo",
    maximum_surplus: "Superávit máximo",
    balanced: "Equilibrado",
    high_carb: "Alto en Carbohidratos",
    high_protein: "Alto en Proteínas",
    standard: "Estándar",
    high_energy: "Alta Energía",
    balanced_plus: "Equilibrado+",
    max_carb: "Máximo Carbohidrato",
    three_meals: "3 Comidas",
    three_meals_one_snack: "3 Comidas + 1 Snack",
    three_meals_two_snacks: "3 Comidas + 2 Snacks",
    three_meals_three_snacks: "3 Comidas + 3 Snacks",
    four_meals: "4 Comidas",
    four_meals_two_snacks: "4 Comidas + 2 Snacks",
    five_meals: "5 Comidas",
    five_meals_one_snack: "5 Comidas + 1 Snack",
    six_meals: "6 Comidas",
    monday: "Lunes",
    tuesday: "Martes",
    wednesday: "Miércoles",
    thursday: "Jueves",
    friday: "Viernes",
    saturday: "Sábado",
    sunday: "Domingo",
    training_day: "Entrenamiento",
    rest_day_active: "Descanso Activo",
    social_refeed: "Social / Refeed",
    structured_free: "Libre Estructurado",
    rest_day_label: "Descanso",
    reset: "Reset",
    meals_count: "{count} comidas",
    plan_distribution: "Distribución del Plan",
    drag_to_reorganize: "Arrastra para reorganizar los días o haz clic para editar cada uno.",
    saving_dots: "Guardando...",
    loading_distribution: "Cargando distribución semanal...",
    reassign_plan: "Reasignar Plan",
    active_plan: "Plan Activo",
    draft_not_assigned: "Borrador / No Asignado",
    plan_progress: "Progreso del Plan",
    nutrition_label: "NUTRICIÓN",
    lean_protein_source: "Fuente de Proteína Magra",
    complex_carbohydrates: "Carbohidratos Complejos",
    healthy_fats: "Grasas Saludables",
    fibrous_vegetables: "Verduras Fibrosas",
    starchy_carbohydrates: "Carbohidratos Almidonados",
    dairy_protein_shake: "Lácteos / Batido de Proteína",
    fruit: "Fruta",
    breakfast: "Desayuno",
    lunch: "Almuerzo",
    dinner: "Cena",
    afternoon_snack: "Merienda",
    morning_snack: "Snack de Mañana",
    evening_snack: "Snack de Noche",
    late_snack: "Snack Tardío",
    general_mode: "Modo General",
    example_mode: "Modo Ejemplo",
    save_plan: "Guardar Plan",
    daily_meal_plan: "Plan de Comidas Diarias",
    add_meal_block: "Añadir Bloque de Comida",
    loading_plan: "Cargando plan...",
    no_meals_in_plan: "No hay comidas en este plan",
    meal_name_placeholder: "Nombre de la comida",
    add_macro_category: "Añadir Categoría de Macro",
    drop_here_to_add: "Suelta aquí para añadir alimento",
    drag_foods_from_library: "Arrastra alimentos de la biblioteca a este bloque",
    food_library: "Biblioteca de Alimentos",
    search_healthy_foods: "Buscar alimentos saludables...",
    not_found: "No encontrado",
    try_another_search: "Intenta otra búsqueda",
    empty_plan: "Plan Vacío",
    drafting: "Borrador",
    plan_details_btn: "Detalles del Plan",
    total_daily_macros: "Macros Diarios Totales",
    planned: "Planeado",
    target: "Objetivo",
    remaining: "Restante",
    confirm_add_meal: "Confirmar Añadir Bloque de Comida",
    plan_saved_success: "Plan guardado correctamente",
    plan_save_error: "Error al guardar el plan",
    drag_foods_from_library_short: "Arrastra alimentos aquí",
    daily_macro_totals: "Totales de Macros Diarios",
    water_intake: "Ingesta de Agua",
    current: "Actual",
    goal_short: "Objetivo",
    new_meal_block: "Nuevo Bloque de Comida",
    block_name: "Nombre del Bloque",
    time_short: "Hora",
    add_block: "Añadir Bloque",
    of_total_calories: "de las calorías totales",
    view_full_library: "Ver Biblioteca Completa",
    search_foods_placeholder: "Buscar alimentos...",
    drag_categories_into_meal: "Arrastra categorías a los bloques de comida",
    nutrition_subtitle: "Asigna planes y monitoriza la adherencia dietética de los clientes",
    plan_templates_btn: "Plantillas de Plan",
    pending_setup: "Configuración pendiente",
    active_plan_status: "Plan Activo",
    new_client_status: "Nuevo Cliente",
    no_active_plan_assigned: "Sin plan activo asignado",
    streak_label: "Racha",
    weight_loss_goal: "Pérdida de Peso",
    muscle_gain_goal: "Ganancia Muscular",
    maintenance_goal: "Mantenimiento",
    keto_diet_goal: "Dieta Keto",
    client_label: "Cliente",
    daily_macros_label: "Macros Diarios",
    high_streak: "Alta",
    perfect_streak: "Perfecta",
    avg_streak: "Media",
    low_streak: "Baja",
    clients_header: "Clientes",
    clients_subtitle: "Gestiona tu base de clientes, realiza un seguimiento del progreso y organiza tu entrenamiento.",
    new_client_btn: "Nuevo Cliente",
    loading_clients: "Cargando clientes...",
    no_clients_found: "No se encontraron clientes",
    delete_client: "Eliminar Cliente",
    archive_client: "Archivar Cliente",
    view_details: "Ver Detalles",
    restore_client: "Restaurar Cliente",
    delete_permanently: "Eliminar permanentemente",
    type_to_confirm: "Escribe {name} para confirmar",
    last_checkin_label: "Último Check-in",
    next_appointment_label: "Próxima Cita",
    at_risk: "En Riesgo",
    missing_data: "Faltan Datos",
    rapid_drop: "Caída Rápida",
    missed_appt: "Cita Perdida",
    low_adherence_status: "Baja Adherencia",
    high_bp_report: "Reporte de Presión Alta",
    stalled_status: "Estancado",
    regression_status: "Regresión",
    on_track_status: "En Camino",
    not_scheduled: "No Programado",
    per_page: "por página",
    showing: "Mostrando",
    of_total: "de",

    // Calendar & Tasks
    calendar_day: "Día",
    calendar_week: "Semana",
    calendar_month: "Mes",
    new_event: "Nuevo Evento",
    high_priority: "Prioridad Alta",
    medium_priority: "Prioridad Media",
    low_priority: "Prioridad Baja",
    daily_focus: "Enfoque Diario",
    daily_focus_desc: "Prioriza tus interacciones con clientes para un máximo impacto.",
    configure: "Configurar",
    overdue_label: "ATRASADO",
    due_today_label: "PARA HOY",
    completed_label: "COMPLETADO",
    inbox_label: "BANDEJA",
    tasks_unit: "Tareas",
    done_unit: "Hecho",
    new_messages_unit: "{count} Nuevos",
    active_tab: "Activas",
    completed_tab: "Completadas",
    mark_as_complete: "Marcar como completada",
    no_tasks_completed: "Aún no hay tareas completadas hoy",
    no_tasks_completed_desc: "Marca algunas tareas para ver tu progreso diario aquí.",
    completed_status: "COMPLETADO",
    done_today: "Hecho hoy",
    with: "con",
    daily_schedule_desc: "Resumen del horario diario",
    manage_schedules_desc: "Gestiona los horarios y tareas de los clientes",
    items: "elementos",

    // Food Library
    food_library_btn: "Biblioteca de Alimentos",
    food_recipe_library: "Biblioteca de Alimentos y Recetas",
    add_custom_food: "Añadir Alimento Personalizado",
    categories: "Categorías",
    protein_label: "Proteína",
    carbs_label: "Carbos",
    fats_label: "Grasas",
    loading_templates: "Cargando plantillas...",
    recommended: "Recomendado",
    ketogenic_option: "Cetogénico (20/5/75)",

    // Training
    training_program_title: "Programa de Entrenamiento",
    assign_program: "Asignar Programa de Entrenamiento",
    create_scratch: "Crear desde Cero",
    create_scratch_desc: "Construye un programa totalmente personalizado según necesidades específicas.",
    intensity_label: "Intensidad",
    volume_label: "Volumen",
    schedule_label: "Horario",
    program_settings: "Ajustes del Programa",
    weekly_frequency: "Frecuencia Semanal",
    primary_focus: "Enfoque Principal",
    program_preview: "Vista Previa del Programa",
    assign_btn: "Asignar Programa",
    per_week: "x / semana",
    min_label: "min",
    training_plan: "Plan de Entrenamiento",
    active_plan_status_label: "Plan Activo",
    save_changes: "GUARDAR CAMBIOS",
    saving_btn: "GUARDANDO...",
    plan_distribution_label: "Distribución del Plan",
    plan_distribution_desc: "Haz clic en cada día para editar o cambiar el entrenamiento.",
    reassign_plan_btn: "REASIGNAR PLAN",
    rest_day_title: "Día de Descanso",
    sets_label: "series",
    intensity_high: "Alta",
    intensity_mod: "Moderada",
    intensity_low: "Baja",
    click_to_view_exercises: "Pulsa para ver ejercicios",
    plan_saved_alert: "Plan guardado correctamente",
    plan_save_error_alert: "Error al guardar el plan",
    training_management: "Gestión de Entrenamiento",
    training_mgmt_desc: "Asigna y monitorea planes de entrenamiento para tus clientes",
    new_workout_plan: "Nuevo Plan de Entrenamiento",
    search_client_placeholder: "Buscar cliente por nombre...",
    all_clients: "Todos los Clientes",
    needs_update_label: "Necesita Actualización",
    drafts_label: "Borradores",
    in_progress_status: "EN PROGRESO",
    needs_update_status: "ACTUALIZAR",
    draft_status_label: "BORRADOR",
    no_plan_status: "SIN PLAN",
    ended_status: "FINALIZADO",
    last_session_label: "Última Sesión",
    update_plan_btn: "Actualizar Plan",
    continue_draft_btn: "Continuar Borrador",
    renew_program_btn: "Renovar Programa",
    manage_program_btn: "Gestionar Programa",
    training_library_title: "Biblioteca de Entrenamiento",
    training_lib_desc: "Gestiona y recomienda ejercicios para tus clientes",
    add_custom_exercise: "Añadir Ejercicio Personalizado",
    search_exercises_placeholder: "Buscar ejercicios (ej. Sentadilla, Flexiones)...",
    filter_by_muscle: "Filtrar por Músculo",
    tools_label: "Herramientas",
    exercise_name_label: "Nombre del Ejercicio",
    muscle_group_label: "Grupo Muscular",
    level_label: "Nivel",
    actions_label: "Acciones",
    no_exercises_found: "No se encontraron ejercicios en esta categoría",
    create_new_exercise: "Crear Nuevo Ejercicio",
    strength_cat: "Fuerza",
    mobility_cat: "Movilidad",
    warmup_cat: "Calentamiento",
    cardio_cat: "Cardio",
    rehab_cat: "Rehabilitación",
    beginner_level: "Principiante",
    intermediate_level: "Intermedio",
    advanced_level: "Avanzado",
    exercise_explanation_label: "Explicación del ejercicio",
    exercise_explanation_placeholder: "Añade aquí una explicación o notas para el cliente...",
    exercise_explanation_sub: "Este bloque aparecerá en el móvil del cliente cuando abra el ejercicio.",
    unknown_client: "Cliente desconocido",
    no_phase: "Sin fase",
    mobility_warmup_block: "Movilidad y Calentamiento",
    warmup_protocol_sub: "Protocolo de Calentamiento",
    strength_block: "Bloque de Fuerza",
    heavy_load_sub: "Carga Pesada",
    cooldown_stretching_block: "Enfriamiento y Estiramiento",
    static_holds_sub: "Mantenimientos Estáticos",
    workout_label_title: "Entrenamiento",
    new_training_block: "Nuevo Bloque de Entrenamiento",
    custom_block_sub: "Bloque Personalizado",
    draft_not_saved: "Borrador - No guardado",
    last_autosave: "Último autoguardado: hace 2 min",
    saving_label: "Guardando...",
    drop_exercise_here: "Suelta el ejercicio aquí",
    drag_exercises_lib: "Arrastra ejercicios de la biblioteca aquí",
    video_label: "Vídeo",
    workout_summary: "Resumen del Entrenamiento",
    add_exercises_breakdown: "Añade ejercicios para ver el desglose",
    filter_by_category: "Filtrar por Categoría",
    master_list: "Lista Maestra",
    no_exercises_found_msg: "No se encontraron ejercicios",
    weight_label: "Peso",
    rest_label: "Descanso",
    mon_short: "Lun",
    tue_short: "Mar",
    wed_short: "Mié",
    thu_short: "Jue",
    fri_short: "Vie",
    sat_short: "Sáb",
    sun_short: "Dom",
    CHECK_IN: "Check-in",
    SESSION: "Sesión",
    TASK: "Tarea",
    PLAN_UPDATE: "Actualización",
    'AUTOMATIC ALERT': "Alerta Automática",
    'DIRECT MESSAGE': "Mensaje Directo",
    'WEEKLY CHECK-IN': "Check-in Semanal",
    'PLAN UPDATE': "Nueva Planificación",
    'MISSING PLAN': "Sin Plan",
    'OVERDUE CHECK-IN': "Check-in Atrasado",
    'Video Call': "Videollamada",
    'In-Person': "Presencial",
    'Training': "Entrenamiento",
    'Nutrition': "Nutrición",
    'Internal': "Interno",
    'Training Analysis': "Análisis de Entrenamiento",
    'MANUAL TASK': "Tarea Manual",
    'USER CREATED': "Creado por Usuario",
    'LOW ADHERENCE': "Baja Adherencia",
    'Review {name}\'s Status': "Revisar estado de {name}",
    'Client has missed check-in windows. Last check-in recorded: {date}.': "El cliente ha perdido ventanas de check-in. Último check-in: {date}.",
    'Investigate drop in tracking': "Investigar caída en seguimiento",
    'Client\'s overall progress is at {progress}%. May need intervention.': "El progreso general es {progress}%. Puede necesitar intervención.",
    'Assign Plan to {name}': "Asignar Plan a {name}",
    'Client has no active training or nutrition plan assigned.': "El cliente no tiene un plan de entrenamiento o nutrición activo asignado.",
    'Due Today': "Para Hoy",
    'Alert': "Alerta",
    'Overdue 2d': "Atrasado 2d"
  },
  en: {
    // Nav
    dashboard: "Dashboard",
    tasks: "Tasks",
    calendar: "Calendar",
    clients: "Clients",
    checkins: "Check-ins",
    messages: "Messages",
    nutrition: "Nutrition",
    training: "Training",
    foods: "Foods & Recipes",
    exercises: "Exercises",
    onboarding: "Onboarding",
    analytics: "Analytics",
    settings: "Settings",

    // Dashboard (Manager)
    welcome_manager: "Good Morning, Manager",
    today: "Today",
    pending_attention: "You have {count} pending items requiring your attention.",
    search_clients_foods: "Search clients, foods...",
    offer_help: "How can I help you today?",
    quick_actions: "Quick Actions",
    add_new_client: "Add New Client",
    schedule_appointment: "Schedule Appointment",
    manage_automations: "Manage Automations",
    broadcast_message: "Broadcast Message",
    attention_required: "Attention Required",
    loading_items: "Loading Items...",
    no_pending_items: "No pending attention tasks! Great job.",
    view_all_items: "View All Items",
    schedule_today: "Schedule Today",
    view_calendar: "View Calendar",
    no_events_today: "No events scheduled for today.",
    active_clients: "Active Clients",
    since_last_month: "since last month",
    latest_updates: "Latest Updates",
    fetching_updates: "Fetching Updates...",
    view_activity_history: "View Activity History",
    no_recent_activity: "No recent activity found.",
    review: "Review",
    resolve: "Resolve",

    // Dashboard (Client)
    good_morning: "Good morning",
    good_afternoon: "Good afternoon",
    good_evening: "Good evening",
    log_checkin: "Log Check-in",
    view_meals: "View Meals",
    start_workout: "Start Workout",
    message_coach: "Message Coach",
    todays_plan: "Today's Plan",
    view_full_plan: "View Full Plan",
    rest_day: "Rest day — no exercises planned",
    view_training_schedule: "View Training Schedule",
    meals_today: "Meals Today",
    kcal_total: "kcal total",
    no_meals_defined: "No meals defined in your plan",
    view_nutrition_plan: "View Nutrition Plan",
    weekly_adherence: "Weekly Adherence",
    based_on_last_7_days: "Based on last 7 days",
    current_streak: "Current Streak",
    day: "Day",
    days: "Days",
    keep_it_up: "Keep it up!",
    start_journey_today: "Start your journey today",
    coach_notes: "Coach Notes",
    no_coach_notes: "No notes from your coach yet.",
    open_messenger: "Open Messenger",
    next_up: "Next Up",
    units: "units",

    // Settings Profile
    profile_details: "Profile Details",
    full_name: "Full Name",
    professional_title: "Professional Title",
    bio: "Bio",
    language: "Language",
    save_profile: "Save Profile",
    discard_changes: "Discard Changes",
    profile_photo: "Profile Photo",
    profile_photo_desc: "This will be displayed on your profile.",
    change: "Change",
    remove: "Remove",
    contact_info: "Contact Information",
    contact_info_desc: "How clients and colleagues can reach you.",
    email_address: "Email Address",
    phone_number: "Phone Number",
    professional_address: "Professional Address",
    social_profiles: "Social Profiles",
    social_profiles_desc: "Connect your social media accounts.",
    email_not_changeable: "Email cannot be changed here.",
    saving: "Saving...",

    // Appearance
    appearance: "Appearance",
    theme_color: "Theme Color",
    theme_color_desc: "Select a primary color theme for your workspace.",
    dark_mode: "Dark Mode",
    appearance_desc: "Customize the look and feel of your platform.",

    // General & Tabs
    general: "General",
    profile: "Profile",
    security: "Security",
    integrations: "Integrations",
    language_region: "Language & Region",
    configure_language_format: "Configure your preferred language and regional formats.",
    select_language: "Select Language",
    spanish: "Spanish",
    english: "English",
    timezone: "Timezone",
    date_format: "Date Format",
    currency: "Currency",

    // Settings General
    settings_header: "Settings",
    settings_desc: "Manage your account preferences, appearance, and notifications.",
    sign_out: "Sign Out",
    personal_details: "Personal Details",
    personal_details_desc: "Update your photo and personal details here.",
    profile_saved: "Profile saved successfully!",

    // Security
    change_password: "Change Password",
    security_desc: "Ensure your account is using a long, random password to stay secure.",
    new_password: "New Password",
    confirm_password: "Confirm New Password",
    update_password: "Update Password",
    updating: "Updating...",
    password_updated: "Password updated successfully!",
    two_factor: "Two-Factor Authentication",
    two_factor_desc: "Add an extra layer of security using an authenticator app.",
    active_sessions: "Active Sessions",
    sessions_desc: "Manage devices logged into your account.",
    active_now: "Active now",
    revoke_session: "Revoke session",
    logout_all: "Logout from all devices",
    login_history: "Login History",
    login_history_desc: "Recent account activity and login attempts.",
    device: "Device",
    location: "Location",
    date: "Date",
    status: "Status",
    no_active_sessions: "No other active sessions.",

    // Billing
    billing: "Billing",
    current_plan: "Current Plan",
    manage_subscription: "Manage your subscription details",
    active: "Active",
    professional_plan: "Professional Plan",
    professional_plan_desc: "For growing nutrition practices",
    change_plan: "Change Plan",
    renews_on: "Renews on {date}",
    payment_method: "Payment Method",
    update_billing: "Update your billing information",
    visa_ending: "Visa ending in {last4}",
    default: "Default",
    expiry: "Expiry {date}",
    update: "Update",
    billing_history: "Billing History",
    billing_history_desc: "Download your past invoices",
    invoice_date: "Invoice Date",
    plan: "Plan",
    amount: "Amount",
    invoice: "Invoice",
    paid: "Paid",

    // Integrations
    google_calendar: "Google Calendar",
    google_calendar_desc: "Sync your appointments and schedules with Google Calendar.",
    connection_status: "Connection Status",
    sync_active: "Sync active",
    not_connected: "Not connected",
    google_api_key: "Google API Key",
    google_calendar_id: "Calendar ID",
    google_service_account: "Google Service Account JSON",
    google_service_account_desc: "Paste your Google Cloud Service Account JSON content here.",
    sync_existing: "Sync existing tasks now",
    test_connection: "Test connection",
    stripe_payments: "Stripe Payments",
    stripe_payments_desc: "Connect your account to see your income and billing.",
    stripe_status: "Stripe Status",
    connected_stripe: "Connected to Stripe",
    publishable_key: "Publishable Key",
    secret_key: "Secret Key",
    save_all_integrations: "Save All Integrations",
    test_stripe: "Test Stripe",

    // Notifications
    notification_preferences: "Notification Preferences",
    notification_prefs_desc: "Choose how and when you want to be notified.",
    event_type: "Event Type",
    email: "Email",
    push: "Push",
    new_client_check_ins_desc: "When a client submits their weekly progress update.",
    new_messages_desc: "Direct messages from clients.",
    appointment_reminders_desc: "1 hour before scheduled session.",
    system_updates_desc: "Product news and platform maintenance.",
    cancel: "Cancel",
    save_notification_prefs: "Save Notification Preferences",

    // Nutrition
    nutrition_header: "Nutrition",
    goal: "Goal",
    age: "Age",
    weight: "Weight",
    no_plan_yet: "No Plan Yet",
    start_from_template: "Start from a Template",
    create_new_plan: "Create New Plan",
    create_new_plan_desc: "Start from scratch with custom macros",
    recommended_for_planning: "Recommended for current planning",
    week_view: "Week View",
    selected: "Selected",
    plan_settings: "Plan Settings",
    target_calories: "Target Calories",
    daily_structure: "Daily Structure",
    macro_split: "Macro Split",
    create_draft_plan: "Create Draft Plan",
    calories: "Calories",
    meals: "Meals",
    protein: "Protein",
    carbs: "Carbs",
    fats: "Fats",
    fat_loss_basic: "Fat Loss Basic",
    conservative_cut: "Conservative cut",
    active_maintain: "Active Maintain",
    recommended_current_goal: "Recommended for current goal",
    moderate_gain: "Moderate Gain",
    lean_bulk_approach: "Lean bulk approach",
    active_build: "Active Build",
    standard_muscle_gain: "Standard muscle gain",
    athlete_perform: "Athlete Perform",
    sport_performance: "Sport performance",
    mass_builder: "Mass Builder",
    significant_surplus: "Significant surplus",
    power_lifting: "Power Lifting",
    strength_focus: "Strength focus",
    extreme_bulk: "Extreme Bulk",
    maximum_surplus: "Maximum surplus",
    balanced: "Balanced",
    high_carb: "High Carb",
    high_protein: "High Protein",
    standard: "Standard",
    high_energy: "High Energy",
    balanced_plus: "Balanced+",
    max_carb: "Max Carb",
    three_meals: "3 Meals",
    three_meals_one_snack: "3 Meals + 1 Snack",
    three_meals_two_snacks: "3 Meals + 2 Snacks",
    three_meals_three_snacks: "3 Meals + 3 Snacks",
    four_meals: "4 Meals",
    four_meals_two_snacks: "4 Meals + 2 Snacks",
    five_meals: "5 Meals",
    five_meals_one_snack: "5 Meals + 1 Snack",
    six_meals: "6 Meals",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    training_day: "Training Day",
    rest_day_active: "Active Rest",
    social_refeed: "Social / Refeed",
    structured_free: "Structured Free",
    rest_day_label: "Rest",
    reset: "Reset",
    meals_count: "{count} meals",
    plan_distribution: "Plan Distribution",
    drag_to_reorganize: "Drag to reorganize days or click to edit each one.",
    saving_dots: "Saving...",
    loading_distribution: "Loading weekly distribution...",
    reassign_plan: "Reassign Plan",
    active_plan: "Active Plan",
    draft_not_assigned: "Draft / Not Assigned",
    plan_progress: "Plan Progress",
    nutrition_label: "NUTRITION",
    lean_protein_source: "Lean Protein Source",
    complex_carbohydrates: "Complex Carbohydrates",
    healthy_fats: "Healthy Fats",
    fibrous_vegetables: "Fibrous Vegetables",
    starchy_carbohydrates: "Starchy Carbohydrates",
    dairy_protein_shake: "Dairy / Protein Shake",
    fruit: "Fruit",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    afternoon_snack: "Afternoon Snack",
    morning_snack: "Morning Snack",
    evening_snack: "Evening Snack",
    late_snack: "Late Snack",
    general_mode: "General Mode",
    example_mode: "Example Mode",
    save_plan: "Save Plan",
    daily_meal_plan: "Daily Meal Plan",
    add_meal_block: "Add Meal Block",
    loading_plan: "Loading plan...",
    no_meals_in_plan: "No meals in this plan",
    meal_name_placeholder: "Meal name",
    add_macro_category: "Add Macro Category",
    drop_here_to_add: "Drop here to add food",
    drag_foods_from_library: "Drag foods from the library into this block",
    food_library: "Food Library",
    search_healthy_foods: "Search healthy foods...",
    not_found: "Not found",
    try_another_search: "Try another search",
    empty_plan: "Empty Plan",
    drafting: "Drafting",
    plan_details_btn: "Plan Details",
    total_daily_macros: "Total Daily Macros",
    planned: "Planned",
    target: "Target",
    remaining: "Remaining",
    confirm_add_meal: "Confirm Add Meal Block",
    plan_saved_success: "Plan saved successfully",
    plan_save_error: "Error saving plan",
    drag_foods_from_library_short: "Drag foods here",
    daily_macro_totals: "Daily Macro Totals",
    water_intake: "Water Intake",
    current: "Current",
    goal_short: "Goal",
    new_meal_block: "New Meal Block",
    block_name: "Block Name",
    time_short: "Time",
    add_block: "Add Block",
    of_total_calories: "of total calories",
    view_full_library: "View Full Library",
    search_foods_placeholder: "Search foods...",
    drag_categories_into_meal: "Drag categories into meal blocks",
    nutrition_subtitle: "Assign plans and monitor client dietary adherence",
    plan_templates_btn: "Plan Templates",
    pending_setup: "Pending setup",
    active_plan_status: "Active Plan",
    new_client_status: "New Client",
    no_active_plan_assigned: "No active plan assigned",
    streak_label: "Streak",
    weight_loss_goal: "Weight Loss",
    muscle_gain_goal: "Muscle Gain",
    maintenance_goal: "Maintenance",
    keto_diet_goal: "Keto Diet",
    client_label: "Client",
    daily_macros_label: "Daily Macros",
    high_streak: "High",
    perfect_streak: "Perfect",
    avg_streak: "Avg",
    low_streak: "Low",
    clients_header: "Clients",
    clients_subtitle: "Manage your client base, track progress, and organize your coaching.",
    new_client_btn: "New Client",
    loading_clients: "Loading clients...",
    no_clients_found: "No clients found",
    delete_client: "Delete Client",
    archive_client: "Archive Client",
    view_details: "View Details",
    restore_client: "Restore Client",
    delete_permanently: "Delete permanently",
    type_to_confirm: "Type {name} to confirm",
    last_checkin_label: "Last Check-in",
    next_appointment_label: "Next Appointment",
    at_risk: "At Risk",
    missing_data: "Missing Data",
    rapid_drop: "Rapid Drop",
    missed_appt: "Missed Appt",
    low_adherence_status: "Low Adherence",
    high_bp_report: "High BP Report",
    stalled_status: "Stalled",
    regression_status: "Regression",
    on_track_status: "On Track",
    not_scheduled: "Not Scheduled",
    per_page: "per page",
    showing: "Showing",
    of_total: "of",

    // Calendar & Tasks
    calendar_day: "Day",
    calendar_week: "Week",
    calendar_month: "Month",
    new_event: "New Event",
    high_priority: "High Priority",
    medium_priority: "Medium Priority",
    low_priority: "Low Priority",
    daily_focus: "Daily Focus",
    daily_focus_desc: "Prioritize your client interactions for maximum impact.",
    configure: "Configure",
    overdue_label: "OVERDUE",
    due_today_label: "DUE TODAY",
    completed_label: "COMPLETED",
    inbox_label: "INBOX",
    tasks_unit: "Tasks",
    done_unit: "Done",
    new_messages_unit: "{count} New",
    active_tab: "Active",
    completed_tab: "Completed",
    mark_as_complete: "Mark as complete",
    no_tasks_completed: "No tasks completed yet today",
    no_tasks_completed_desc: "Check off some tasks to see your daily progress here.",
    completed_status: "COMPLETED",
    done_today: "Done today",
    with: "with",
    daily_schedule_desc: "Daily schedule overview",
    manage_schedules_desc: "Manage client schedules and tasks",
    items_count: "{count} items",
    items: "items",

    // Food Library
    food_library_btn: "Food Library",
    food_recipe_library: "Food & Recipe Library",
    add_custom_food: "Add Custom Food",
    categories: "Categories",
    protein_label: "Protein",
    carbs_label: "Carbs",
    fats_label: "Fats",
    loading_templates: "Loading templates...",
    recommended: "Recommended",
    ketogenic_option: "Ketogenic (20/5/75)",

    // Training
    training_program_title: "Training Program",
    assign_program: "Assign Training Program",
    create_scratch: "Create from Scratch",
    create_scratch_desc: "Build a fully custom program tailored to specific needs.",
    intensity_label: "Intensity",
    volume_label: "Volume",
    schedule_label: "Schedule",
    program_settings: "Program Settings",
    weekly_frequency: "Weekly Frequency",
    primary_focus: "Primary Focus",
    program_preview: "Program Preview",
    assign_btn: "Assign Program",
    per_week: "x / week",
    min_label: "min",
    training_plan: "Training Plan",
    active_plan_status_label: "Active Plan",
    save_changes: "SAVE CHANGES",
    saving_btn: "SAVING...",
    plan_distribution_label: "Plan Distribution",
    plan_distribution_desc: "Click on each day to edit or change the workout.",
    reassign_plan_btn: "REASSIGN PLAN",
    rest_day_title: "Rest Day",
    sets_label: "sets",
    intensity_high: "High",
    intensity_mod: "Moderate",
    intensity_low: "Low",
    click_to_view_exercises: "Click to view exercises",
    plan_saved_alert: "Plan saved successfully",
    plan_save_error_alert: "Error saving plan",
    training_management: "Training Management",
    training_mgmt_desc: "Assign and monitor workout plans for your clients",
    new_workout_plan: "New Workout Plan",
    search_client_placeholder: "Search client by name...",
    all_clients: "All Clients",
    needs_update_label: "Needs Update",
    drafts_label: "Drafts",
    in_progress_status: "IN PROGRESS",
    needs_update_status: "NEEDS UPDATE",
    draft_status_label: "DRAFT",
    no_plan_status: "NO PLAN",
    ended_status: "ENDED",
    last_session_label: "Last Session",
    update_plan_btn: "Update Plan",
    continue_draft_btn: "Continue Draft",
    renew_program_btn: "Renew Program",
    manage_program_btn: "Manage Program",
    training_library_title: "Training Library",
    training_lib_desc: "Manage and recommend exercises for your clients",
    add_custom_exercise: "Add Custom Exercise",
    search_exercises_placeholder: "Search exercises (e.g. Squat, Push Up)...",
    filter_by_muscle: "Filter by Muscle",
    tools_label: "Tools",
    exercise_name_label: "Exercise Name",
    muscle_group_label: "Muscle Group",
    level_label: "Level",
    actions_label: "Actions",
    no_exercises_found: "No exercises found for this category",
    create_new_exercise: "Create New Exercise",
    strength_cat: "Strength",
    mobility_cat: "Mobility",
    warmup_cat: "Warm-up",
    cardio_cat: "Cardio",
    rehab_cat: "Rehab",
    beginner_level: "Beginner",
    intermediate_level: "Intermediate",
    advanced_level: "Advanced",
    exercise_explanation_label: "Exercise Explanation",
    exercise_explanation_placeholder: "Add an explanation or notes for the client here...",
    exercise_explanation_sub: "This block will appear on the client's mobile when they open the exercise.",
    unknown_client: "Unknown Client",
    no_phase: "No phase",
    mobility_warmup_block: "Mobility & Warm-up",
    warmup_protocol_sub: "Warm-up Protocol",
    strength_block: "Strength Block",
    heavy_load_sub: "Heavy Load",
    cooldown_stretching_block: "Cool Down & Stretching",
    static_holds_sub: "Static Holds",
    workout_label_title: "Workout",
    new_training_block: "New Training Block",
    custom_block_sub: "Custom Block",
    draft_not_saved: "Draft - Not saved",
    last_autosave: "Last autosave: 2 min ago",
    saving_label: "Saving...",
    drop_exercise_here: "Drop exercise here",
    drag_exercises_lib: "Drag exercises from the library here",
    video_label: "Video",
    workout_summary: "Workout Summary",
    add_exercises_breakdown: "Add exercises to see breakdown",
    filter_by_category: "Filter by Category",
    master_list: "Master List",
    no_exercises_found_msg: "No exercises found",
    weight_label: "Weight",
    rest_label: "Rest",
    mon_short: "Mon",
    tue_short: "Tue",
    wed_short: "Wed",
    thu_short: "Thu",
    fri_short: "Fri",
    sat_short: "Sat",
    sun_short: "Sun",
    CHECK_IN: "Check-in",
    SESSION: "Session",
    TASK: "Task",
    PLAN_UPDATE: "Update",
    'AUTOMATIC ALERT': "Automatic Alert",
    'DIRECT MESSAGE': "Direct Message",
    'WEEKLY CHECK-IN': "Weekly Check-in",
    'PLAN UPDATE': "Plan Update",
    'MISSING PLAN': "Missing Plan",
    'OVERDUE CHECK-IN': "Overdue Check-in",
    'Video Call': "Video Call",
    'In-Person': "In-Person",
    'Training': "Training",
    'Nutrition': "Nutrition",
    'Internal': "Internal",
    'Training Analysis': "Training Analysis",
    'MANUAL TASK': "Manual Task",
    'USER CREATED': "User Created",
    'LOW ADHERENCE': "Low Adherence",
    'Review {name}\'s Status': "Review {name}'s Status",
    'Client has missed check-in windows. Last check-in recorded: {date}.': "Client has missed check-in windows. Last check-in recorded: {date}.",
    'Investigate drop in tracking': "Investigate drop in tracking",
    'Client\'s overall progress is at {progress}%. May need intervention.': "Client's overall progress is at {progress}%. May need intervention.",
    'Assign Plan to {name}': "Assign Plan to {name}",
    'Client has no active training or nutrition plan assigned.': "Client has no active training or nutrition plan assigned.",
    'Due Today': "Due Today",
    'Alert': "Alert",
    'Overdue 2d': "Overdue 2d"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('es');
  const [isLoading, setIsLoading] = useState(true);
  const { user } = useAuth();

  useEffect(() => {
    const loadLanguage = async () => {
      if (!user) {
        setIsLoading(false);
        return;
      }
      try {
        const data = await fetchWithAuth('/manager/profile');
        if (data && data.language) {
          setLanguageState(data.language as Language);
        }
      } catch (err) {
        console.error('Error loading language settings:', err);
      } finally {
        setIsLoading(false);
      }
    };
    loadLanguage();
  }, [user]);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    if (user) {
      try {
        // We'll store language in the profile table
        await fetchWithAuth('/manager/profile', {
          method: 'POST',
          body: JSON.stringify({ language: lang })
        });
      } catch (err) {
        console.error('Error saving language preference:', err);
      }
    }
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    // Ensure we don't crash if translations or language object is missing
    const langDict = translations[language] || translations['es'];
    let text = langDict[key] || key;
    
    if (params && typeof text === 'string') {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v?.toString() || '');
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLoading }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
