-- Create exercises table if not exists
create table if not exists public.exercises (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  category text,
  subcategory text,
  video_url text,
  description text,
  type text check (type in ('Compound', 'Isolation')),
  muscle_groups text[] default '{}'::text[],
  secondary_muscles text[] default '{}'::text[],
  tools text[] default '{}'::text[],
  difficulty_level text check (difficulty_level in ('Beginner', 'Intermediate', 'Advanced')),
  icon text default 'fitness_center',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.exercises enable row level security;

-- Policies
create policy "Anyone can view exercises" on public.exercises for select using (true);
create policy "Managers can manage exercises" on public.exercises for all using (
  exists (select 1 from public.users where id = auth.uid() and role = 'MANAGER')
);

-- Clear existing exercises if necessary (optional)
-- delete from public.exercises;

-- Bulk Insert Exercises
insert into public.exercises (name, category, subcategory, video_url, description, type, muscle_groups, tools, difficulty_level, icon) values
('Press plano con barra', 'Strength', 'Empuje horizontal', 'https://youtube.com/shorts/sQwh2Zaa6Hk?feature=share', 'Press de banca plano; pectoral mayor, tríceps y deltoides anterior. Baja la barra a la altura del pezón con escápulas retraídas y empuja hasta extensión completa.', 'Compound', '{Chest,Triceps}', '{Barbell,Bench}', 'Intermediate', 'fitness_center'),
('Press plano con mancuernas', 'Strength', 'Empuje horizontal', 'https://youtu.be/kti5E7IEoo8', 'Variante con mayor rango unilateral; codos a 45° del tronco, converge sin chocar las mancuernas.', 'Compound', '{Chest,Triceps}', '{Dumbbells,Bench}', 'Beginner', 'fitness_center'),
('Press plano en máquina', 'Strength', 'Empuje horizontal', 'https://youtube.com/shorts/zFtEziSuPVY?feature=share', 'Movimiento guiado que aísla pectoral sin exigir tanta estabilización; aprieta placas al final del recorrido.', 'Compound', '{Chest}', '{Machine}', 'Beginner', 'fitness_center'),
('Fondos en paralelas', 'Strength', 'Empuje horizontal', 'https://youtube.com/shorts/9rRo3ij03EI?feature=share', 'Énfasis en pectoral inferior y tríceps; torso ligeramente inclinado, desciende hasta 90° de codo y extiende fuerte.', 'Compound', '{Chest,Triceps}', '{Parallel Bars}', 'Intermediate', 'fitness_center'),
('Fondos en anillas', 'Strength', 'Empuje horizontal', null, 'Igual patrón pero con inestabilidad; recluta estabilizadores de hombro y core. Mantén anillas pegadas al cuerpo.', 'Compound', '{Chest,Shoulders}', '{Rings}', 'Advanced', 'fitness_center'),
('Landmine press unilateral', 'Strength', 'Empuje horizontal', null, 'Press a 45° con barra anclada; mezcla empuje horizontal/vertical y anti-rotación de core. Bloquea cadera y sigue la línea de la barra.', 'Compound', '{Shoulders,Chest}', '{Barbell,Landmine}', 'Intermediate', 'fitness_center'),
('Press inclinado con barra', 'Strength', 'Empuje horizontal', 'https://youtube.com/shorts/v1bMRJArSVg?feature=share', 'Inclinación 30-45°; busca estiramiento controlado y empuja explosivo manteniendo estabilidad escapular.', 'Compound', '{Chest,Shoulders}', '{Barbell,Incline Bench}', 'Intermediate', 'fitness_center'),
('Press inclinado en máquina', 'Strength', 'Empuje horizontal', 'https://youtu.be/92PqmpmUa-M', 'Focaliza porción clavicular del pectoral; respaldo ~30°, tempo 2-1-2 para control y estiramiento.', 'Compound', '{Chest}', '{Machine}', 'Beginner', 'fitness_center'),
('Press inclinado con mancuernas', 'Strength', 'Empuje horizontal', null, 'Inclinación 30-45°; busca estiramiento profundo y converge al centro sin colapsar hombros.', 'Compound', '{Chest,Shoulders}', '{Dumbbells,Incline Bench}', 'Beginner', 'fitness_center'),
('Press inclinado en multipower', 'Strength', 'Empuje horizontal', 'https://youtube.com/shorts/P30FqDR8R9o?feature=share', 'Barra guiada que permite cargas altas con seguridad; escápulas retraídas y pies firmes para generar fuerza.', 'Compound', '{Chest,Shoulders}', '{Smith Machine}', 'Beginner', 'fitness_center'),
('Flexiones suelo', 'Strength', 'Empuje horizontal', null, 'Push-up básico; cuerpo alineado, codos a 45°, pecho al suelo y extensión completa manteniendo core firme.', 'Compound', '{Chest,Triceps}', '{Bodyweight}', 'Beginner', 'fitness_center'),
('Flexiones anillas', 'Strength', 'Empuje horizontal', null, 'Push-up con inestabilidad; mayor activación de pectoral y serrato. Anillas paralelas y muñecas neutras.', 'Compound', '{Chest,Shoulders}', '{Rings}', 'Advanced', 'fitness_center'),
('Flexiones pies elevados', 'Strength', 'Empuje horizontal', null, 'Eleva pies 30-60 cm para cargar pectoral superior; evita arquear la zona lumbar.', 'Compound', '{Chest}', '{Bodyweight,Bench}', 'Intermediate', 'fitness_center'),
('Flexiones con lastre', 'Strength', 'Empuje horizontal', null, 'Añade chaleco o disco sobre la espalda para progresar fuerza; controla la bajada en ~3 s.', 'Compound', '{Chest,Triceps}', '{Weight Vest,Plate}', 'Intermediate', 'fitness_center'),
('Flexiones con tempo', 'Strength', 'Empuje horizontal', null, 'Push-up con tempo (p. ej. 3-1-1); aumenta tiempo bajo tensión y control técnico en cada fase.', 'Compound', '{Chest}', '{Bodyweight}', 'Beginner', 'fitness_center'),
('Press militar con barra de pie', 'Strength', 'Empuje vertical', 'https://youtube.com/shorts/PrETnc4UZ0Y?feature=share', 'Impulsa desde clavículas con pies a la anchura de caderas, glúteos y abdomen firmes. Empuja en ligera “J” hasta que los bíceps queden a la altura de las orejas.', 'Compound', '{Shoulders,Triceps}', '{Barbell}', 'Intermediate', 'fitness_center'),
('Press militar con barra sentado', 'Strength', 'Empuje vertical', 'https://youtube.com/shorts/LgfkUCovaG8?feature=share', 'Postura erguida y neutra; antebrazos verticales durante todo el gesto. Sube la barra exploisvo y baja controlado.', 'Compound', '{Shoulders,Triceps}', '{Barbell,Bench}', 'Intermediate', 'fitness_center'),
('Press militar con mancuernas', 'Strength', 'Empuje vertical', 'https://youtube.com/shorts/2WN6e58K95U?feature=share', 'Postura erguida y neutra; antebrazos verticales durante todo el gesto. Sube las mancuernas en arco convergente.', 'Compound', '{Shoulders,Triceps}', '{Dumbbells}', 'Beginner', 'fitness_center'),
('Press militar en máquina', 'Strength', 'Empuje vertical', null, 'Ajusta el asiento para que los agarres queden a la altura de la barbilla. Retracción escapular suave, mirada al frente.', 'Compound', '{Shoulders}', '{Machine}', 'Beginner', 'fitness_center'),
('Push press', 'Strength', 'Empuje vertical', null, 'Pequeño dip de rodillas–cadera (10–15°) con torso vertical, talones en contacto. Explota hacia arriba.', 'Compound', '{Shoulders,Legs}', '{Barbell}', 'Intermediate', 'fitness_center'),
('Push jerk', 'Strength', 'Empuje vertical', null, 'Igual dip–drive que el push press pero “te sientas” para recibir la barra con brazos extendidos.', 'Compound', '{Shoulders,Legs}', '{Barbell}', 'Advanced', 'fitness_center'),
('Handstand push–up', 'Strength', 'Empuje vertical', null, 'Manos a la anchura de hombros, crea un trípode estable con cabeza; desciende hasta tocar suavemente.', 'Compound', '{Shoulders,Triceps}', '{Bodyweight}', 'Advanced', 'fitness_center'),
('Press militar en multipower', 'Strength', 'Empuje vertical', null, 'Coloca banco o pies de forma que la barra baje sobre la línea media de las clavículas.', 'Compound', '{Shoulders}', '{Smith Machine}', 'Beginner', 'fitness_center'),
('Press muy inclinado en multipower', 'Strength', 'Empuje vertical', null, 'Énfasis en pectoral clavicular y deltoides anterior; agarre algo más ancho que hombros.', 'Compound', '{Chest,Shoulders}', '{Smith Machine}', 'Beginner', 'fitness_center'),
('Remo con barra', 'Strength', 'Tracción horizontal', null, 'Torsión de cadera ~45°, barra cerca de tibias. Tira codos hacia atrás y abajo, comprime escapulas.', 'Compound', '{Back,Biceps}', '{Barbell}', 'Intermediate', 'fitness_center'),
('Remo Pendlay', 'Strength', 'Tracción horizontal', null, 'Inicia desde el suelo en cada rep; espalda paralela al suelo, codos altos y explosivos.', 'Compound', '{Back}', '{Barbell}', 'Advanced', 'fitness_center'),
('Seal row con mancuernas', 'Strength', 'Tracción horizontal', null, 'Pecho apoyado en banco inclinado; mancuernas en manos. Tira hacia cadera manteniendo torso inmóvil.', 'Compound', '{Back}', '{Dumbbells,Bench}', 'Intermediate', 'fitness_center'),
('Remo con mancuernas bilateral', 'Strength', 'Tracción horizontal', null, 'Torso estable en hip hinge, tira ambas mancuernas al mismo tiempo hacia cadera, palmas neutrales.', 'Compound', '{Back}', '{Dumbbells}', 'Beginner', 'fitness_center'),
('Remo con mancuerna unilateral', 'Strength', 'Tracción horizontal', null, 'Apoya rodilla y mano opuesta en banco, tira mancuerna hacia cadera con codo pegado.', 'Compound', '{Back}', '{Dumbbell,Bench}', 'Beginner', 'fitness_center'),
('Remo en T', 'Strength', 'Tracción horizontal', null, 'Coge barra en V handle con torso inclinado ~45°, pies firmes. Tira al ombligo.', 'Compound', '{Back}', '{T-Bar}', 'Intermediate', 'fitness_center'),
('Remo Gironda', 'Strength', 'Tracción horizontal', null, 'Torso inclinado ~30°, agarre supino. Lleva codos hacia abajo y atrás, rotación escapular.', 'Compound', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Remo Gironda agarre neutro', 'Strength', 'Tracción horizontal', null, 'Misma forma que Gironda, pero palmas enfrentadas. Reduce tensión en muñecas.', 'Compound', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Remo Gironda agarre prono', 'Strength', 'Tracción horizontal', null, 'Agarre pronado; fuerza hombros hacia atrás y baja codos para activar parte superior del trapecio.', 'Compound', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Remo Gironda agarre supino', 'Strength', 'Tracción horizontal', null, 'Agarre supino; enfatiza dorsal largo y bíceps. Mantén torso estable y pull force hacia cóccix.', 'Compound', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Remo pecho apoyado prono', 'Strength', 'Tracción horizontal', null, 'Pecho apoyado; codos altos con agarre prono, retrae escapulas y desciende controlado.', 'Compound', '{Back}', '{Machine}', 'Beginner', 'fitness_center'),
('Remo pecho apoyado neutro', 'Strength', 'Tracción horizontal', null, 'Pecho apoyado, enfásis en protraer y retrater escápulas. Mayor confort en muñecas.', 'Compound', '{Back}', '{Machine}', 'Beginner', 'fitness_center'),
('Remo unilateral en polea', 'Strength', 'Tracción horizontal', null, 'Un brazo a la polea baja con torso neutro. Tira mano a cadera, escápula retrayendo.', 'Compound', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Dominadas supinas', 'Strength', 'Tracción vertical', null, 'Manos en supinación a la anchura de hombros; retrae escapulas, lleva el pecho a la barra.', 'Compound', '{Back,Biceps}', '{Pull Up Bar}', 'Intermediate', 'fitness_center'),
('Dominadas pronas', 'Strength', 'Tracción vertical', null, 'Agarre prono algo más ancho que hombros; empuja hombros abajo–atrás, acerca la barra al pecho.', 'Compound', '{Back,Shoulders}', '{Pull Up Bar}', 'Advanced', 'fitness_center'),
('Dominadas neutras', 'Strength', 'Tracción vertical', null, 'Manos enfrentadas; sube hasta que la barbilla supere la barra, mantiene tensión en dorsal.', 'Compound', '{Back}', '{Pull Up Bar}', 'Intermediate', 'fitness_center'),
('Pull–over en polea con barra recta (de pie)', 'Strength', 'Tracción vertical', null, 'Baja la barra en arco amplio desde encima de la cabeza hasta las caderas sin flexionar codos.', 'Isolation', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Pull–over en polea con cuerda (de pie)', 'Strength', 'Tracción vertical', null, 'Misma posición; separa las manos al descender para enfatizar dorsal externo.', 'Isolation', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Face–pull', 'Strength', 'Tracción vertical', null, 'Polea alta con cuerda; tira hacia la cara con codos elevados y rota externamente hombros.', 'Isolation', '{Shoulders,Back}', '{Cable Machine,Rope}', 'Beginner', 'fitness_center'),
('Jalón al pecho neutro', 'Strength', 'Tracción vertical', null, 'Agarre neutro; torso estable, lleva maneral al esternón con codos pegados.', 'Compound', '{Back}', '{Lat Pulldown Machine}', 'Beginner', 'fitness_center'),
('Jalón al pecho prono', 'Strength', 'Tracción vertical', null, 'Agarre prono ancho; inclina torso levemente atrás, tira codos hacia abajo–atrás.', 'Compound', '{Back}', '{Lat Pulldown Machine}', 'Beginner', 'fitness_center'),
('Jalón al pecho supino', 'Strength', 'Tracción vertical', null, 'Agarre supino estrecho; baja la barra a la clavícula enfatizando bíceps y dorsal largo.', 'Compound', '{Back,Biceps}', '{Lat Pulldown Machine}', 'Beginner', 'fitness_center'),
('Jalón unilateral en polea', 'Strength', 'Tracción vertical', null, 'Sujeta maneral con un brazo; tira hasta la línea del hombro con codo cerca del costado.', 'Compound', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Pullover unilateral', 'Strength', 'Tracción vertical', null, 'Polea alta con cuerda; con un brazo baja maneral detrás de cabeza con torso estable.', 'Isolation', '{Back}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Jalón en máquina prono', 'Strength', 'Tracción vertical', null, 'Ajusta asiento para que agarres queden a la altura adecuada; con palmas al suelo.', 'Compound', '{Back}', '{Machine}', 'Beginner', 'fitness_center'),
('Jalón en máquina neutro', 'Strength', 'Tracción vertical', null, 'Agarre neutro; torso erguido, tira hasta el esternón con codos pegados.', 'Compound', '{Back}', '{Machine}', 'Beginner', 'fitness_center'),
('Jalón en máquina supino', 'Strength', 'Tracción vertical', null, 'Agarre supino; baja agarres hacia la parte alta del abdomen, enfocándote en bíceps y dorsal.', 'Compound', '{Back,Biceps}', '{Machine}', 'Beginner', 'fitness_center'),
('Sentadilla barra libre alta', 'Strength', 'Dominio de rodilla', null, 'Barra sobre trapecio; pies a anchura de hombros. Baja empujando caderas atrás y rodillas afuera.', 'Compound', '{Quads,Glutes}', '{Barbell,Rack}', 'Intermediate', 'fitness_center'),
('Sentadilla barra libre low–bar', 'Strength', 'Dominio de rodilla', null, 'Barra sobre deltoides posteriores; torso algo inclinado. Inicia con caderas atrás.', 'Compound', '{Glutes,Lower Back}', '{Barbell,Rack}', 'Intermediate', 'fitness_center'),
('Sentadilla frontal', 'Strength', 'Dominio de rodilla', null, 'Barra en deltoides anteriores, codos altos. Desciende preservando tronco vertical.', 'Compound', '{Quads,Core}', '{Barbell,Rack}', 'Advanced', 'fitness_center'),
('Sentadilla Zercher', 'Strength', 'Dominio de rodilla', null, 'Barra en pliegue de codos; core firme. Baja con pecho alto y caderas atrás.', 'Compound', '{Quads,Core}', '{Barbell}', 'Advanced', 'fitness_center'),
('Sentadilla Goblet', 'Strength', 'Dominio de rodilla', null, 'Mancuerna frente al pecho; codos abajo. Baja controlado, mantén talones firmes.', 'Compound', '{Quads,Glutes}', '{Dumbbell}', 'Beginner', 'fitness_center'),
('Sentadilla multipower', 'Strength', 'Dominio de rodilla', null, 'Barra guiada; pies algo adelantados. Desciende en línea vertical, columna neutra.', 'Compound', '{Quads}', '{Smith Machine}', 'Beginner', 'fitness_center'),
('Sentadilla Hack', 'Strength', 'Dominio de rodilla', null, 'Máquina hack; pies adelantados, espalda apoyada. Desciende hasta ángulo cómodo.', 'Compound', '{Quads}', '{Machine}', 'Beginner', 'fitness_center'),
('Zancada caminando', 'Strength', 'Dominio de rodilla', null, 'Paso largo alterno; rodilla delantera alineada con tobillo y trasera cercana al suelo.', 'Compound', '{Quads,Glutes}', '{Bodyweight}', 'Beginner', 'fitness_center'),
('Zancada en sitio', 'Strength', 'Dominio de rodilla', null, 'Posición dividida fija; desciende verticalmente y asciende empujando con talón delantero.', 'Compound', '{Quads,Glutes}', '{Bodyweight}', 'Beginner', 'fitness_center'),
('Step–up', 'Strength', 'Dominio de rodilla', null, 'Pie completo sobre banco; torso erguido. Eleva cadera empujando desde el talón.', 'Compound', '{Quads,Glutes}', '{Bench}', 'Beginner', 'fitness_center'),
('Cossack squat', 'Strength', 'Dominio de rodilla', null, 'Pies amplios; desplaza cadera a un lado manteniendo pierna opuesta extendida.', 'Compound', '{Quads,Adductors}', '{Bodyweight}', 'Intermediate', 'fitness_center'),
('Prensa 45º', 'Strength', 'Dominio de rodilla', null, 'Espalda en respaldo, pies a anchura de hombros; empuja la plataforma hasta extensión completa.', 'Compound', '{Quads,Glutes}', '{Machine}', 'Beginner', 'fitness_center'),
('Prensa 45º unilateral', 'Strength', 'Dominio de rodilla', null, 'Mismo set–up con una pierna; empuja la plataforma y guía el descenso suave.', 'Compound', '{Quads}', '{Machine}', 'Beginner', 'fitness_center'),
('Prensa horizontal bilateral', 'Strength', 'Dominio de rodilla', null, 'Espalda neutra, pies a altura media. Extiende totalmente y vuelve controlado.', 'Compound', '{Quads}', '{Machine}', 'Beginner', 'fitness_center'),
('Prensa horizontal unilateral', 'Strength', 'Dominio de rodilla', null, 'Igual configuración; empuje con una pierna, evita rotar pelvis y controla el regreso.', 'Compound', '{Quads}', '{Machine}', 'Beginner', 'fitness_center'),
('Sentadilla búlgara con mancuerna contralateral', 'Strength', 'Dominio de rodilla', null, 'Mancuerna en mano opuesta a pierna de apoyo; pie trasero elevado.', 'Compound', '{Quads,Glutes}', '{Dumbbell,Bench}', 'Intermediate', 'fitness_center'),
('Sentadilla búlgara con mancuernas', 'Strength', 'Dominio de rodilla', null, 'Mancuernas a los lados; baja rodilla trasera y sube con fuerza en pierna delantera.', 'Compound', '{Quads,Glutes}', '{Dumbbells,Bench}', 'Intermediate', 'fitness_center'),
('Sentadilla búlgara en multipower', 'Strength', 'Dominio de rodilla', null, 'Barra guiada; ajusta paso para línea de fuerza. Desciende controlado.', 'Compound', '{Quads}', '{Smith Machine,Bench}', 'Intermediate', 'fitness_center'),
('Zancada estática', 'Strength', 'Dominio de rodilla', null, 'Igual set–up; baja rodilla trasera al suelo y sube conservando pecho erguido.', 'Compound', '{Quads,Glutes}', '{Bodyweight}', 'Beginner', 'fitness_center'),
('Step-up con mancuerna', 'Strength', 'Dominio de rodilla', null, 'Sostén mancuerna con mano contraria al pie que hace fuerza; pie en banco completo.', 'Compound', '{Quads,Glutes}', '{Dumbbell,Bench}', 'Beginner', 'fitness_center'),
('Patrón de sentadilla', 'Mobility', 'Dominio de rodilla', null, 'Sin carga, practica rango completo y alineación de rodillas.', 'Compound', '{Quads,Full Body}', '{Bodyweight}', 'Beginner', 'fitness_center'),
('Peso muerto convencional', 'Strength', 'Dominio de cadera', null, 'Pies a la anchura de caderas; inicia con caderas y rodillas flexionadas.', 'Compound', '{Back,Glutes,Hamstrings}', '{Barbell}', 'Intermediate', 'fitness_center'),
('Peso muerto sumo', 'Strength', 'Dominio de cadera', null, 'Postura amplia con pies rotados; manos dentro de piernas. Caderas bajan verticalmente.', 'Compound', '{Adductors,Glutes}', '{Barbell}', 'Intermediate', 'fitness_center'),
('Peso muerto piernas rígidas', 'Strength', 'Dominio de cadera', null, 'Piernas casi extendidas, caderas atrás; baja barra sintiendo tensión en isquios.', 'Compound', '{Hamstrings}', '{Barbell}', 'Intermediate', 'fitness_center'),
('Buenos días', 'Strength', 'Dominio de cadera', null, 'Barra sobre trapecio alto; caderas atrás y torso inclinado con curva lumbar neutra.', 'Compound', '{Hamstrings,Lower Back}', '{Barbell}', 'Advanced', 'fitness_center'),
('Kettlebell swing', 'Strength', 'Dominio de cadera', null, 'Pies a anchura de caderas; balancea pesa con caderas atrás.', 'Compound', '{Glutes,Hamstrings}', '{Kettlebell}', 'Intermediate', 'fitness_center'),
('Landmine single–leg RDL', 'Strength', 'Dominio de cadera', null, 'Barra anclada, torso neutro y una pierna de apoyo; baja barra por tibias.', 'Compound', '{Hamstrings,Balance}', '{Barbell,Landmine}', 'Intermediate', 'fitness_center'),
('Peso muerto rumano con barra', 'Strength', 'Dominio de cadera', null, 'Agarre prono y piernas semiestáticas; caderas atrás bajan barra hasta media tibia.', 'Compound', '{Hamstrings,Glutes}', '{Barbell}', 'Intermediate', 'fitness_center'),
('Peso muerto rumano con mancuernas', 'Strength', 'Dominio de cadera', null, 'Mancuernas a los lados, torso estable; caderas atrás hasta rodillas.', 'Compound', '{Hamstrings,Glutes}', '{Dumbbells}', 'Beginner', 'fitness_center'),
('Peso muerto rumano unilateral con mancuerna', 'Strength', 'Dominio de cadera', null, 'Mancuerna en mano opuesta a pierna de apoyo; torso alineado baja peso.', 'Compound', '{Hamstrings,Balance}', '{Dumbbell}', 'Intermediate', 'fitness_center'),
('Hip thrust con barra', 'Strength', 'Dominio de cadera', null, 'Espalda alta apoyada en banco, pies firmes; empuja caderas hasta alinear rodillas.', 'Compound', '{Glutes}', '{Barbell,Bench}', 'Intermediate', 'fitness_center'),
('Hip thrust unilateral', 'Strength', 'Dominio de cadera', null, 'Misma posición que hip thrust, levanta una pierna y empuja con la otra.', 'Compound', '{Glutes}', '{Bench}', 'Intermediate', 'fitness_center'),
('Hip thrust en máquina', 'Strength', 'Dominio de cadera', null, 'Ajusta asiento y plataforma; empuja con caderas usando trayectoria guiada.', 'Compound', '{Glutes}', '{Machine}', 'Beginner', 'fitness_center'),
('Hip thrust en multipower', 'Strength', 'Dominio de cadera', null, 'Barra guiada y banco firme; pies cerca de caderas, extiende caderas al máximo.', 'Compound', '{Glutes}', '{Smith Machine,Bench}', 'Beginner', 'fitness_center'),
('Extensión cuádriceps máquina', 'Strength', 'Cuádriceps', null, 'Siéntate con espalda apoyada y eje de rodilla alineado; extiende piernas.', 'Isolation', '{Quads}', '{Machine}', 'Beginner', 'fitness_center'),
('Sissy squat', 'Strength', 'Cuádriceps', null, 'Pies a la anchura de caderas; lleva rodillas hacia delante mientras separas talones.', 'Compound', '{Quads}', '{Bodyweight}', 'Intermediate', 'fitness_center'),
('Cyclist squat', 'Strength', 'Cuádriceps', null, 'Pie delantero elevado sobre plataforma baja, torso vertical; baja cadera.', 'Compound', '{Quads}', '{Bodyweight,Wedge}', 'Intermediate', 'fitness_center'),
('Step–down controlado', 'Strength', 'Cuádriceps', null, 'Apoya un pie en plataforma; baja talón opuesto hacia el suelo.', 'Compound', '{Quads}', '{Step}', 'Intermediate', 'fitness_center'),
('Curl femoral de pie unilateral', 'Strength', 'Femoral / Isquios', null, 'Con la máquina ajustada, fija la cadera y flexiona la rodilla llevando el talón al glúteo.', 'Isolation', '{Hamstrings}', '{Machine}', 'Beginner', 'fitness_center'),
('Curl femoral tumbado', 'Strength', 'Femoral / Isquios', null, 'Boca abajo, eje de rodilla alineado; flexiona ambas rodillas llevando talones al glúteo.', 'Isolation', '{Hamstrings}', '{Machine}', 'Beginner', 'fitness_center'),
('Curl femoral sentado', 'Strength', 'Femoral / Isquios', null, 'Sentado con respaldo, alinea el eje de la máquina con tus rodillas; flexiona hacia el glúteo.', 'Isolation', '{Hamstrings}', '{Machine}', 'Beginner', 'fitness_center'),
('Nordic curl', 'Strength', 'Femoral / Isquios', null, 'Con rodillas aseguradas, inclina el torso recto hacia adelante usando isquios.', 'Compound', '{Hamstrings}', '{Bodyweight,Anchor}', 'Advanced', 'fitness_center'),
('Curl deslizante slider', 'Strength', 'Femoral / Isquios', null, 'Pies en sliders, caderas elevadas; desliza pies hacia los glúteos.', 'Isolation', '{Hamstrings,Core}', '{Sliders}', 'Intermediate', 'fitness_center'),
('Romanian kettlebell swing', 'Strength', 'Femoral / Isquios', null, 'Bisagra de caderas atrás, usa impulso de isquios y glúteos para elevar la kettlebell.', 'Compound', '{Hamstrings,Glutes}', '{Kettlebell}', 'Intermediate', 'fitness_center'),
('Elevación gemelos de pie', 'Strength', 'Gemelos', null, 'Coloca parte delantera de pies en plataforma; empuja talones hacia arriba.', 'Isolation', '{Calves}', '{Machine,Step}', 'Beginner', 'fitness_center'),
('Elevación gemelos sentado', 'Strength', 'Gemelos', null, 'Siéntate con almohadilla sobre muslos; flexiona tobillos elevando talones.', 'Isolation', '{Calves}', '{Machine}', 'Beginner', 'fitness_center'),
('Elevación gemelos burro', 'Strength', 'Gemelos', null, 'Con torso apoyado y caderas flexionadas; apoya empeines en plataforma.', 'Isolation', '{Calves}', '{Machine}', 'Beginner', 'fitness_center'),
('Curl con barra', 'Strength', 'Bíceps', null, 'De pie, agarre supino a la anchura de hombros; codos fijos al costado.', 'Isolation', '{Biceps}', '{Barbell}', 'Beginner', 'fitness_center'),
('Curl barra Z', 'Strength', 'Bíceps', null, 'Agarres semi-pronos en barra Z para aliviar muñecas; mantiene codos pegados.', 'Isolation', '{Biceps}', '{EZ-Bar}', 'Beginner', 'fitness_center'),
('Curl con mancuernas', 'Strength', 'Bíceps', null, 'Alterno o simultáneo; muñecas neutrales, rota a supinación al subir.', 'Isolation', '{Biceps}', '{Dumbbells}', 'Beginner', 'fitness_center'),
('Curl martillo con mancuernas', 'Strength', 'Bíceps', null, 'Agarre neutro; codos al costado, levanta mancuernas hacia los hombros.', 'Isolation', '{Biceps,Forearms}', '{Dumbbells}', 'Beginner', 'fitness_center'),
('Curl con barra en polea baja', 'Strength', 'Bíceps', null, 'Polea ajustada al nivel del suelo; tira barra hacia los hombros.', 'Isolation', '{Biceps}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Curl predicador con barra Z', 'Strength', 'Bíceps', null, 'Pecho y axilas apoyados en banco predicador; manos en barra Z.', 'Isolation', '{Biceps}', '{EZ-Bar,Preacher Bench}', 'Beginner', 'fitness_center'),
('Curl predicador en máquina', 'Strength', 'Bíceps', null, 'Asiento y almohadilla alineados con articulación; agarre ergonómico.', 'Isolation', '{Biceps}', '{Machine}', 'Beginner', 'fitness_center'),
('Curl predicador unilateral con mancuerna', 'Strength', 'Bíceps', null, 'Un brazo a la vez en banco predicador; codo fijo.', 'Isolation', '{Biceps}', '{Dumbbell,Preacher Bench}', 'Beginner', 'fitness_center'),
('Curl predicador unilateral en polea', 'Strength', 'Bíceps', null, 'Polea baja con mango en banco predicador; lleva maneral al hombro.', 'Isolation', '{Biceps}', '{Cable Machine,Preacher Bench}', 'Beginner', 'fitness_center'),
('Curl sentado en banco inclinado', 'Strength', 'Bíceps', null, 'Banco a 45–60°; brazos colgando detrás del torso, sube mancuernas.', 'Isolation', '{Biceps}', '{Dumbbells,Incline Bench}', 'Intermediate', 'fitness_center'),
('Curl bayesian en polea', 'Strength', 'Bíceps', null, 'Polea baja con agarre en cuerda; comienza con brazos extendidos.', 'Isolation', '{Biceps}', '{Cable Machine,Rope}', 'Intermediate', 'fitness_center'),
('Curl bayesian en polea unilateral', 'Strength', 'Bíceps', null, 'Mismo gesto con un brazo; enfatiza el estiramiento inicial.', 'Isolation', '{Biceps}', '{Cable Machine,handle}', 'Intermediate', 'fitness_center'),
('Extensión de polea', 'Strength', 'Tríceps', null, 'De pie frente a la polea alta; codos fijos al costado, empuja hacia abajo.', 'Isolation', '{Triceps}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Extensión con cuerda de polea alta', 'Strength', 'Tríceps', null, 'Polea alta con cuerda; abre ligeramente las puntas al final.', 'Isolation', '{Triceps}', '{Cable Machine,Rope}', 'Beginner', 'fitness_center'),
('Extensión con barra en polea alta', 'Strength', 'Tríceps', null, 'Agarre recto en polea; codos cerca del cuerpo, baja hasta los muslos.', 'Isolation', '{Triceps}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Extensión unilateral en polea alta', 'Strength', 'Tríceps', null, 'Sujeta maneral con un brazo; codo pegado, extiende antebrazo verticalmente.', 'Isolation', '{Triceps}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Extensión por encima de cabeza con cuerda', 'Strength', 'Tríceps', null, 'De pie o sentado; polea alta detrás de la cabeza, extiende brazos hacia arriba.', 'Isolation', '{Triceps}', '{Cable Machine,Rope}', 'Intermediate', 'fitness_center'),
('Extensión por encima de cabeza unilateral', 'Strength', 'Tríceps', null, 'Mismo gesto con un brazo; torso erguido y codo fijo.', 'Isolation', '{Triceps}', '{Dumbbell}', 'Intermediate', 'fitness_center'),
('Press francés con mancuerna', 'Strength', 'Tríceps', null, 'Tumbado en banco plano; baja mancuerna en semicírculo hacia la frente.', 'Isolation', '{Triceps}', '{Dumbbells,Bench}', 'Intermediate', 'fitness_center'),
('Press francés con barra Z', 'Strength', 'Tríceps', null, 'Misma mecánica con barra Z; controla bajada hasta frente.', 'Isolation', '{Triceps}', '{EZ-Bar,Bench}', 'Intermediate', 'fitness_center'),
('Press francés en polea', 'Strength', 'Tríceps', null, 'Tumbado en banco, polea al nivel de la cabeza; empuja agarre hacia abajo.', 'Isolation', '{Triceps}', '{Cable Machine,Bench}', 'Intermediate', 'fitness_center'),
('Kaz press en multipower', 'Strength', 'Tríceps', null, 'Acostado en banco, barra guiada; codos a 90° delante de frente.', 'Compound', '{Triceps}', '{Smith Machine,Bench}', 'Advanced', 'fitness_center'),
('Elevación lateral con mancuernas', 'Strength', 'Deltoides', 'https://youtube.com/shorts/wzNMU0Alz8o?feature=share', 'De pie con mancuernas a los costados; eleva brazos lateralmente hasta hombros.', 'Isolation', '{Shoulders}', '{Dumbbells}', 'Beginner', 'fitness_center'),
('Elevación lateral en polea unilateral', 'Strength', 'Deltoides', 'https://youtube.com/shorts/dGC1vLxSo6s?feature=share', 'Con polea baja, agarra el mango y eleva el brazo lateralmente.', 'Isolation', '{Shoulders}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Elevación lateral en máquina', 'Strength', 'Deltoides', null, 'Ajusta asiento y agarres a la altura de hombros; abre los brazos hacia afuera.', 'Isolation', '{Shoulders}', '{Machine}', 'Beginner', 'fitness_center'),
('Elevación frontal en polea', 'Strength', 'Deltoides', null, 'Con polea baja, sujeta el mango y eleva en arco frontal hasta los ojos.', 'Isolation', '{Shoulders}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Elevación frontal con mancuernas alterno', 'Strength', 'Deltoides', null, 'De pie, alterna elevaciones frontales con mancuernas; mantén torso estable.', 'Isolation', '{Shoulders}', '{Dumbbells}', 'Beginner', 'fitness_center'),
('Pájaros en máquina', 'Strength', 'Deltoides', null, 'Pecho apoyado en respaldo inclinado; separa los agarres llevando codos atrás.', 'Isolation', '{Shoulders}', '{Machine}', 'Beginner', 'fitness_center'),
('Extensión horizontal de hombro en polea', 'Strength', 'Deltoides', null, 'De espaldas a una polea media, empuja el mango hacia atrás.', 'Isolation', '{Shoulders}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Elevación horizontal de hombro en polea', 'Strength', 'Deltoides', null, 'De pie frente a la polea, separa el mango hacia el costado.', 'Isolation', '{Shoulders}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Aperturas en máquina (contractora)', 'Strength', 'Abducciones de hombro', 'https://youtube.com/shorts/uAr8d4vuGRw', 'Ajusta agarres a la altura del pecho; junta brazos en semicírculo.', 'Isolation', '{Chest}', '{Machine}', 'Beginner', 'fitness_center'),
('Cruces de polea (altura media, de pie)', 'Strength', 'Abducciones de hombro', null, 'Poleas a nivel hombro; traza arco al frente y comprime pectoral.', 'Isolation', '{Chest}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Cruces de polea desde arriba', 'Strength', 'Abducciones de hombro', 'https://youtube.com/shorts/LezWBVZgWFM?feature=share', 'Poleas altas; desciende manerales al ombligo.', 'Isolation', '{Chest}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Cruces de polea desde abajo', 'Strength', 'Abducciones de hombro', null, 'Poleas bajas; sube manerales en arco ascendente hasta esternón.', 'Isolation', '{Chest}', '{Cable Machine}', 'Beginner', 'fitness_center'),
('Cruces de polea sentado (altura media)', 'Strength', 'Abducciones de hombro', 'https://youtube.com/shorts/-aJJkW35PNA?feature=share', 'Banco entre poleas; junta manerales al centro.', 'Isolation', '{Chest}', '{Cable Machine,Bench}', 'Beginner', 'fitness_center'),
('Cruces de polea desde abajo sentado', 'Strength', 'Abducciones de hombro', 'https://youtube.com/shorts/1mv7Gu2gdfk?feature=share', 'Misma posición, poleas bajas; arco ascendente a la cara anterior del hombro.', 'Isolation', '{Chest}', '{Cable Machine,Bench}', 'Beginner', 'fitness_center'),
('CMJ', 'Cardio', 'Saltos bilaterales', null, 'Comienza en semi–sentadilla, dip explosivo y salto vertical.', 'Compound', '{Legs}', '{Bodyweight}', 'Intermediate', 'bolt'),
('Squat jump', 'Cardio', 'Saltos bilaterales', null, 'Desde sentadilla profunda, impulsa con pies al mismo tiempo.', 'Compound', '{Legs}', '{Bodyweight}', 'Intermediate', 'bolt'),
('Box jump', 'Cardio', 'Saltos bilaterales', null, 'Salto explosivo desde semi–sentadilla al centro de la caja.', 'Compound', '{Legs}', '{Box}', 'Intermediate', 'bolt'),
('Drop jump', 'Cardio', 'Saltos bilaterales', null, 'Cae desde plataforma baja, absorbe y salta inmediatamente.', 'Compound', '{Legs}', '{Step}', 'Advanced', 'bolt'),
('Depth jump', 'Cardio', 'Saltos bilaterales', null, 'Desde plataforma alta, desciende al suelo y rebota en salto vertical.', 'Compound', '{Legs}', '{Box}', 'Advanced', 'bolt'),
('Broad jump', 'Cardio', 'Saltos bilaterales', null, 'Salto horizontal desde semi–sentadilla; impulsa con caderas.', 'Compound', '{Legs}', '{Bodyweight}', 'Intermediate', 'bolt'),
('Lateral bound', 'Cardio', 'Saltos unilaterales / laterales', null, 'Salta lateral de una pierna a la otra, impulsando con cadera.', 'Compound', '{Legs,Balance}', '{Bodyweight}', 'Intermediate', 'bolt'),
('Skater hop', 'Cardio', 'Saltos unilaterales / laterales', null, 'Salto lateral imitando patinador; torso estable.', 'Compound', '{Legs,Balance}', '{Bodyweight}', 'Beginner', 'bolt'),
('Single–leg hop', 'Cardio', 'Saltos unilaterales / laterales', null, 'Salto vertical o horizontal con una sola pierna.', 'Compound', '{Legs,Balance}', '{Bodyweight}', 'Advanced', 'bolt'),
('Hurdle hops', 'Cardio', 'Saltos unilaterales / laterales', null, 'Saltos rápidos sobre vallas bajas; rebotes ágiles.', 'Compound', '{Legs}', '{Hurdles}', 'Intermediate', 'bolt'),
('Pogo jumps', 'Cardio', 'Saltos unilaterales / laterales', null, 'Saltos pequeños y rápidos con mínima flexión de rodillas.', 'Compound', '{Calves}', '{Bodyweight}', 'Beginner', 'bolt'),
('Bounding', 'Cardio', 'Saltos unilaterales / laterales', null, 'Zancadas pliométricas exageradas; empujando fuerte caderas.', 'Compound', '{Legs}', '{Bodyweight}', 'Advanced', 'bolt'),
('Plyo push–up', 'Cardio', 'Potencia tren superior', null, 'Push–up explosivo, despega manos del suelo.', 'Compound', '{Chest,Shoulders}', '{Bodyweight}', 'Advanced', 'bolt'),
('Medball chest pass', 'Cardio', 'Potencia tren superior', null, 'Empuja balón medicinal con potencia desde el pecho.', 'Compound', '{Chest}', '{Medicine Ball}', 'Beginner', 'bolt'),
('Medball overhead slam', 'Cardio', 'Potencia tren superior', null, 'Eleva balón sobre la cabeza y suéltalo con fuerza al suelo.', 'Compound', '{Full Body,Core}', '{Medicine Ball}', 'Beginner', 'bolt'),
('Medball side throw', 'Cardio', 'Potencia tren superior', null, 'Gira cadera y lanza balón lateralmente contra pared.', 'Compound', '{Core,Shoulders}', '{Medicine Ball}', 'Beginner', 'bolt'),
('Medball scoop toss', 'Cardio', 'Potencia tren superior', null, 'Agáchate, toma balón bajo y lánzalo en arco hacia adelante.', 'Compound', '{Glutes,Shoulders}', '{Medicine Ball}', 'Beginner', 'bolt'),
('Battle–rope whip', 'Cardio', 'Potencia tren superior', null, 'Genera oleadas explosivas con cuerdas; core estable.', 'Compound', '{Shoulders,Core}', '{Battle Ropes}', 'Beginner', 'bolt'),
('KB push–press balístico', 'Cardio', 'Potencia tren superior', null, 'Desde militar, añade un dip ligero y empuja kettlebell explosivo.', 'Compound', '{Shoulders,Legs}', '{Kettlebell}', 'Intermediate', 'bolt'),
('Kettlebell swing balístico', 'Cardio', 'Global / balístico', null, 'Hip hinge explosivo para elevar kettlebell; core firme.', 'Compound', '{Glutes,Hamstrings}', '{Kettlebell}', 'Intermediate', 'bolt'),
('Medicine–ball overhead throw', 'Cardio', 'Global / balístico', null, 'Desde semi–sentadilla, extiende caderas y brazos para lanzar balón.', 'Compound', '{Full Body}', '{Medicine Ball}', 'Beginner', 'bolt'),
('Cat–Camel', 'Mobility', 'Columna & escápula', null, 'A cuatro patas, alterna arquear y redondear la columna.', 'Isolation', '{Spine}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Rotación torácica', 'Mobility', 'Columna & escápula', null, 'Apoya antebrazo, gira cadera opuesta separando mano hacia el techo.', 'Isolation', '{Back}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Open book', 'Mobility', 'Columna & escápula', null, 'Acostado de lado con rodillas flexionadas, lleva brazo superior sobre el cuerpo.', 'Isolation', '{Back,Chest}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Angel en la nieve', 'Mobility', 'Columna & escápula', null, 'Supino, desliza brazos manteniendo contacto con el suelo.', 'Isolation', '{Shoulders}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Scapular push–up', 'Mobility', 'Columna & escápula', null, 'En plancha alta, hunde hombros para protracción.', 'Isolation', '{Shoulders}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Dislocaciones banda', 'Mobility', 'Columna & escápula', null, 'Pasa manos por encima de cabeza manteniendo brazos rectos.', 'Isolation', '{Shoulders}', '{Resistance Band}', 'Beginner', 'accessibility'),
('Y–T–W–L', 'Mobility', 'Columna & escápula', null, 'Forma las letras Y, T, W y L con brazos; aprieta escapulas.', 'Isolation', '{Shoulders}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Prone swimmers', 'Mobility', 'Columna & escápula', null, 'Prono, mueve brazos como si nadaras, rotando hombros.', 'Isolation', '{Shoulders}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Press militar + rotaciones', 'Mobility', 'Columna & escápula', null, 'Combina press militar con rotación externa al bloqueo.', 'Compound', '{Shoulders}', '{Light Weights}', 'Beginner', 'accessibility'),
('90–90 hip switch', 'Mobility', 'Cadera / tren inferior', null, 'Sentado con piernas en ‘90-90’, alterna lados rotando caderas.', 'Isolation', '{Hips}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Spiderman lunge + T–spine reach', 'Mobility', 'Cadera / tren inferior', null, 'Desde zancada profunda, apoya mano interior y lleva brazo al techo.', 'Compound', '{Hips,Back}', '{Bodyweight}', 'Beginner', 'accessibility'),
('World’s Greatest Stretch', 'Mobility', 'Cadera / tren inferior', null, 'Combina zancada, reach torácico y aducción de cadera.', 'Compound', '{Full Body}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Hip flexor stretch dinámico', 'Mobility', 'Cadera / tren inferior', null, 'Zancada con impulsos cortos de cadera hacia adelante.', 'Isolation', '{Hips}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Adductor rock–back', 'Mobility', 'Cadera / tren inferior', null, 'A cuatro patas, desliza glúteos hacia talones para estirar aductores.', 'Isolation', '{Hips}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Cossack shift dinámico', 'Mobility', 'Cadera / tren inferior', null, 'Desplaza cadera lateral flexionando pierna y alterna.', 'Compound', '{Hips,Adductors}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Frog stretch pulsado', 'Mobility', 'Cadera / tren inferior', null, 'En cuatro patas, desliza rodillas hacia afuera y da pulsos.', 'Isolation', '{Hips}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Knee–to–wall dorsiflexión tobillo', 'Mobility', 'Cadera / tren inferior', null, 'De frente a pared, adelanta pie y lleva rodilla a la pared.', 'Isolation', '{Ankles}', '{Bodyweight,Wall}', 'Beginner', 'accessibility'),
('Squat & Pull', 'Mobility', 'Cadera / tren inferior', null, 'En sentadilla profunda, tira de codos hacia arriba.', 'Compound', '{Hips,Back}', '{Bodyweight}', 'Beginner', 'accessibility'),
('Band pull–apart', 'Warm-up', 'Activación global', null, 'Abre brazos hasta alinear hombros activando serrato.', 'Isolation', '{Shoulders}', '{Resistance Band}', 'Beginner', 'rebase_edit'),
('Monster walk', 'Warm-up', 'Activación global', null, 'Pasos diagonales con miniband; enfatiza abductores.', 'Isolation', '{Glutes}', '{Miniband}', 'Beginner', 'rebase_edit'),
('Crab walk', 'Warm-up', 'Activación global', null, 'Pasos laterales en semi-sentadilla con banda.', 'Isolation', '{Glutes}', '{Miniband}', 'Beginner', 'rebase_edit'),
('Glute bridge isométrico', 'Warm-up', 'Activación global', null, 'Pies cerca de glúteos; eleva caderas y mantén contracción.', 'Isolation', '{Glutes}', '{Bodyweight}', 'Beginner', 'rebase_edit'),
('Dead bug reach', 'Warm-up', 'Activación global', null, 'Supino, extiende brazo y pierna opuestos sin arquear lumbar.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'rebase_edit'),
('Bird–dog', 'Warm-up', 'Activación global', null, 'A cuatro patas, extiende brazo y pierna opuestos.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'rebase_edit'),
('Plancha frontal', 'Strength', 'Anti–extensión', null, 'Apoya antebrazos, cuerpo en línea; aprieta core y glúteos.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'shield'),
('Roll–out rueda', 'Strength', 'Anti–extensión', null, 'De rodillas, extiende cuerpo desplazando rueda al frente.', 'Isolation', '{Core}', '{Ab Roller}', 'Intermediate', 'shield'),
('Roll–out TRX', 'Strength', 'Anti–extensión', null, 'Inclina el tronco sujetando asas de TRX y vuelve.', 'Isolation', '{Core}', '{TRX}', 'Intermediate', 'shield'),
('Dead bug', 'Strength', 'Anti–extensión', null, 'Supino con brazos y piernas en 90°; extiende opuestos.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'shield'),
('Hollow hold', 'Strength', 'Anti–extensión', null, 'Hombros y piernas elevados formando “banana”.', 'Isolation', '{Core}', '{Bodyweight}', 'Intermediate', 'shield'),
('Cruce abdominal', 'Strength', 'Anti–extensión', null, 'Desde supino, lleva rodilla al codo opuesto alternando.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'shield'),
('Plancha lateral', 'Strength', 'Anti–lateral', null, 'Apoya antebrazo y lateral del pie; tensa oblicuos.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'shield'),
('Suitcase carry', 'Strength', 'Anti–lateral', null, 'Sostén peso en un lado y camina erguido.', 'Compound', '{Core,Shoulders}', '{Dumbbell}', 'Beginner', 'shield'),
('Copenhagen plank', 'Strength', 'Anti–lateral', null, 'Apoya antebrazo superior en banco; cuerpo en línea.', 'Isolation', '{Core,Adductors}', '{Bench}', 'Advanced', 'shield'),
('Pallof press de pie', 'Strength', 'Anti–rotación', null, 'Lateral a cable, empuja frente al pecho resistiendo giro.', 'Isolation', '{Core}', '{Cable Machine}', 'Beginner', 'shield'),
('Pallof press medio arrodillado', 'Strength', 'Anti–rotación', null, 'Igual que de pie, pero arrodillado para estabilidad.', 'Isolation', '{Core}', '{Cable Machine}', 'Beginner', 'shield'),
('Medball chop & lift isométrico', 'Strength', 'Anti–rotación', null, 'Sostén balón en posición de corte y resiste rotación.', 'Isolation', '{Core}', '{Medicine Ball}', 'Beginner', 'shield'),
('Russian twist controlado', 'Strength', 'Rotacional controlada', null, 'Sentado con torso reclinado 45°; rota lento.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'shield'),
('Cable wood–chop', 'Strength', 'Rotacional controlada', null, 'Cable alto, tira diagonal hacia cadera opuesta.', 'Compound', '{Core}', '{Cable Machine}', 'Beginner', 'shield'),
('Landmine rotation', 'Strength', 'Rotacional controlada', null, 'Barra anclada, mueve extremo en arco controlado.', 'Compound', '{Core}', '{Barbell,Landmine}', 'Intermediate', 'shield'),
('Farmer carry', 'Strength', 'Carries', null, 'Sostén pesas en cada mano y camina erguido.', 'Compound', '{Full Body,Grip}', '{Dumbbells}', 'Beginner', 'shield'),
('Overhead carry', 'Strength', 'Carries', null, 'Carga sobre cabeza con brazos extendidos; camina.', 'Compound', '{Shoulders,Core}', '{Dumbbell}', 'Intermediate', 'shield'),
('Front–rack carry', 'Strength', 'Carries', null, 'Barra o mancuernas en rack frontal; camina.', 'Compound', '{Core,Shoulders}', '{Barbell,Dumbbells}', 'Intermediate', 'shield'),
('Cross–body carry', 'Strength', 'Carries', null, 'Kettlebell en mano opuesta; camina resistiendo giro.', 'Compound', '{Core}', '{Kettlebell}', 'Intermediate', 'shield'),
('Crunch abdominal', 'Strength', 'Flexión activa', null, 'Eleva omóplatos contrayendo abs sin tirar de cuello.', 'Isolation', '{Core}', '{Bodyweight}', 'Beginner', 'shield'),
('Elevaciones de piernas colgado', 'Strength', 'Flexión activa', null, 'Sujeta barra, eleva piernas al frente.', 'Isolation', '{Core,Hip Flexors}', '{Pull Up Bar}', 'Intermediate', 'shield'),
('Toes–to–bar', 'Strength', 'Flexión activa', null, 'De barra de dominadas, eleva pies hasta la barra.', 'Compound', '{Core,Back}', '{Pull Up Bar}', 'Advanced', 'shield'),
('Leg–raise en paralelas', 'Strength', 'Flexión activa', null, 'Apoyado en paralelas, eleva piernas extendidas.', 'Isolation', '{Core}', '{Parallel Bars}', 'Intermediate', 'shield'),
('Hip extension GHD', 'Strength', 'Extensión / glúteo–espinal', null, 'En banco GHD, bisagra de caderas.', 'Compound', '{Back,Glutes,Hamstrings}', '{GHD Machine}', 'Advanced', 'shield'),
('Superman hold', 'Strength', 'Extensión / glúteo–espinal', null, 'Prono, eleva simultáneo brazos y piernas.', 'Isolation', '{Back}', '{Bodyweight}', 'Beginner', 'shield');
